### ISSUE TITLE
Styled Component API

### ISSUE THREAD

**Issue by sastan** [tw-in-js/twind#102]
The [styled API](https://emotion.sh/docs/styled) is commonly used within the react community. Although twind is framework agnostic it may be nice to provide a styled module as well.

The API proposed here is inspired by emotion, styled-component and goober. The idea is to add two new modules:

- twind/styled - ready to use with react
- twind/styled/preact - ready to use with preact

The main discussion is about what type (CSS or tailwind) the styled API uses. Most editors support some CSS based styled component. Our `apply` method can be used within `css` and we could have the best of both worlds. That is why I'd like start fresh and propose the following API:

**styled**: thin wrapper around `css`

```jsx
import { styled, theme } from 'twind/styled'

const Button = styled.button`
  color: ${theme('colors.gray.500)};
`
```

To use Tailwind within styled the `@apply` helper can be used:

```jsx
import { styled, theme } from 'twind/styled'

const Button = styled.button`
  color: ${theme('colors.gray.500)};
  @apply bg-gray-50;
`
```

**twind**: thin wrapper around `apply`

To have tailwind styled component we could use a `twind` export (https://github.com/tw-in-js/twind/pull/7#issuecomment-753470395):

```jsx
import { twind } from 'twind/styled'

const Button = twind.button`
  text(base blue-600)
  rounded-sm
  border(& solid 2 blue-600)
  m-4 py-1 px-4
`
```

Support for CSS would be available via `css`:

```jsx
import { twind, css } from 'twind/styled'

const Button = twind.button`
  text(base blue-600)
  ${css`
     some: css props;
  `}
`
```

`styled` and `twind` components both used an style object internally and can be used together. They differ only in how the styles are defined.

----

**Adapting based on props**

```jsx
const Button = styled.button`
  color: ${(props, { theme }) => theme(props.primary ? 'colors.purple.600' : 'colors.blue.600')};
`

const Container = twind.div`flex ${(props) => props.column && 'flex-col'}`
```

**Combine different styling** https://github.com/tw-in-js/twind/pull/7#issuecomment-752716310

```jsx
// Passing a callback that receives props and returns list of various stylings
const Button = twind.button(({ primary }) => [
  // tagged template
  tw`font-bold`,

  // plain string
  'px-4 py-2 rounded-full',

  // prop condition (no need for ${} interpolation)
  primary ? 'bg-red-600 text-white' : 'bg-white text-gray-800',

  // CSS object notation
  css({ fontSize: '14pt' })
])
```

**Styling any component**

any component can be styled  as long as it accepts a `className` prop:

```jsx
const Basic = ({ className }) => <div className={className}>Some text</div>

const Fancy1 = styled(Basic)`color: darkgreen;`
const Fancy2 = twind(Basic)`text-purple-600`
```

**Extending Styles**

```jsx
const Button = twind.button`
  text(base blue-600)
  rounded-sm
  border(& solid 2 blue-600)
  m-4 py-1 px-4
`

const PurpleButton = twind(Button)`
  text-purple-600 border-purple-600
`
```

**`as` prop**

To use styles from a styled component but change the element that’s rendered, you can use the `as` prop.

```jsx
const Button = twind.button`text-purple-600`

render(
  <Button as="a" href="https://github.com/tw-in-js/twind">
    Twind on GitHub
  </Button>,
)
```

The `as` prop is only used by styled when it’s not forwarded to the underlying element. By default, this means that the `as` prop is used for html tags and forwarded for components. To change this, you can pass a custom `shouldForwardProp` which returns `true` for `'as'` to forward it or returns `false` for `'as'` to use it and not forward it.

**Attaching additional props**

To avoid unnecessary wrappers that just pass on some props to the rendered component, or element, you can use the `.attrs` function. It allows you to attach additional props (or "attributes") to a component.

```jsx
// we can define static props
const Input = twind.input.attrs({
  type: 'text',
})`
  rounded-md
  border(& 4 indigo-600)
`

// Or we can define dynamic ones
const SizedInput = Input.attrs((props) => ({
  size: props.size || '1em',
}))
```

Notice that when wrapping styled components, `.attrs` are applied from the innermost styled component to the outermost styled component.

This allows each wrapper to override nested uses of `.attrs`, similarly to how css properties defined later in a stylesheet override previous declarations.

```jsx
const PasswordInput = twind(Input).attrs({
  type: 'password',
})`
  border-blue-600
`
```

> `className` and `class` properties are merged into one string. They do **not** override each other.

**Referring to other components**

We can nest selectors using `&`:

```jsx
const Child = twind.div`text-purple-600`
const Parent = styled.div(
  css({
    [`& ${Child}`]: {
      color: 'green',
    },
  }),
)
```

> Currently this can only work when using CSS (either `styled` or `css` within `twind`)

**`shouldForwardProp`**

`styled` is smart enough to filter non-standard attributes automatically for you. By default, `styled` passes all props to custom components and only props that are valid html attributes for string tags.

You can customize this by passing a custom `shouldForwardProp` function. It works much like the predicate callback of `Array.filter`. A prop that fails the test isn't passed down to underlying components.

Optionally, `shouldForwardProp` can take a second parameter that provides access to the default validator function (`@emotion/is-prop-valid`) which is used by styled internally. This function can be used as a fallback, and of course, it also works like a predicate, filtering based on known HTML attributes.

```jsx
const H1 = twind('h1', {
  shouldForwardProp: (prop, defaultValidator) => prop !== 'hidden' && defaultValidator(prop),
})`
  text-2xl underline
  ${(props) => props.hidden && 'sr-only'}
`

render(<H1 hidden>Screen Reader Only</H1>)
```

**Refs**

Passing a `ref` prop to a styled component will give you one of two things depending on the styled target:

- the underlying DOM node (if targeting a basic element, e.g. `twind.div`)
- a React component instance (if targeting a custom component e.g. extended from `React.Component`)

```jsx
const Input = twind.input`
  rounded-sm m-2 p-2
  text-pink-500
  bg-yellow-200
`

const Form = () => {
  const inputRef = useRef()

  return (
    <Input
      ref={inputRef}
      placeholder="Hover to focus!"
      onMouseEnter={() => {
        inputRef.current.focus()
      }}
    />
  )
}
```

**Using custom tw instance**

`styled` uses the named `tw` export from the `twind` module. You can use a custom instance:

```js
import { create } from 'twind'
import { styled } from 'twind/styled'

const { tw } = create(/* addtional config */)

const myStyled = styled.bind(tw)
```

/cc @tw-in-js/contributors

**Comment by mattrossman** [comment]
> To use Tailwind within styled the `apply` helper can be used

I imagine `tw` would also work in this context? Just want to check since that's what I'm used to from twin.macro (and it's shorter to type)

**Comment by sastan** [comment]
> > To use Tailwind within styled the `apply` helper can be used
> 
> I imagine `tw` would also work in this context? Just want to check since that's what I'm used to from twin.macro (and it's shorter to type)

It could but I would advise to use `apply`. With `tw` each class is added to the className which may result in unwanted styling. By using `apply` all those styles are merged into one class (the twin.macro behavior) and that allows to use passed in classNames to always override component styles.

**Comment by sastan** [comment]
Superseded by twind/style API
