### ISSUE TITLE
Discussion: Worth escaping user-provided values in generated markup

### ISSUE THREAD

**Issue by ggoodman** [tw-in-js/twind#111]
## Description

When used in an SSR context, `getStyleTag` is designed to produce a `<style>` tag suitable for embedding in generated HTML so that the initial payload has all critical CSS inlined.

The act of embedding anything into server-generated HTML introduces an XSS risk. That risk is proportional to the likelihood that user-submitted content might find its way into the generated markup. In the general case, this risk seems quite low for a tool like `twind`.

That being said, I suspect some creative folks will realize that `twind` is an unusually effective way of rendering similar markup with different themes in the same page. They may also think that it would be interesting to allow users to create and share their own themes. At this point we're pretty far into the realm of the hypothetical and should think about balancing risk vs cost.

Below, I present some links where similar issues have been brought for other frameworks living in the same space as `twind`.

My conclusion is that on the balance of risk and cost, a strategic replacement of `</` (and maybe html comments?) would go a long way in closing the XSS window at a very small cost.

## Research

1. 2018 to treat escaping as the problem of the implementer of `styled-components`: styled-components/styled-components#1828.
2. 2020: Proposal to sanitize interpolated strings in `styled-components`: https://github.com/styled-components/styled-components/issues/1105#issuecomment-574729345
3. 2020: Discussion of XSS risk in SSR styles in `jss`: cssinjs/jss#1265

## Tools

When injecting JavaScript of JSON into HTML, my go-to solution is [jsesc](https://github.com/mathiasbynens/jsesc#isscriptcontext).

**Comment by joaovpmamede** [comment]
Not really concerning the issues that @ggoodman brought up but would it be possible to have what tailwind does with postcss and extract the styles used on the components to a separate css file?

**Comment by ggoodman** [comment]
@joaovpmamede seems like the machinery underpinning `getStyleTag` could be used to produce _just_ the styles so that you could do whatever you'd like with them. Is that what you're after?

**Comment by sastan** [comment]
@joaovpmamede Something like this should work:

1. Setup your static extraction using one of the following:
  - [twind/shim](https://twind.dev/docs/handbook/getting-started/using-the-shim.html#static-extraction)
  - [Extract Styles aka SSR](https://twind.dev/docs/handbook/advanced/ssr.html)
  - [Framework Examples](https://twind.dev/docs/handbook/recipes/use-with/react.html)
2. Create file
  ```js
  import { getStyleTagProperties } from 'twind/sheets'
  
  // Do your setup and rendering see above
  
  const { textContent } = getStyleTagProperties(sheet)
  fs.writeFile(cssFile, textContent)
  ```

**Comment by sastan** [comment]
Closing for now. Please re-open if needed.
