### ISSUE TITLE
Looking a way to parse classes to style string

### ISSUE THREAD

**Issue by kasec** [tw-in-js/twind#116]
Hi Guys.
I'm working with twind and looks pretty good, but I have a question.

Exist a way to parse to styles string with classes reference?

I've used `getStyleTag` but it returns a style string with its elements and I would to know if it could set classes instead. 

Thanks for your job!

**Comment by sastan** [comment]
I'm not sure if I understand. Could you provide an example of what you want to achieve? What would be your input and your expected output?

**Comment by kasec** [comment]
Yesterday start with this resolution #96.
```jsx
function App() {
     return (
         <div className="relative min-h-screen bg-green-200 bg-cover flex flex-col justify-center">
                <buttton className="bg-red-500 p-2 m-5 rounded">red button<button/>
                <buttton className="bg-green-500 p-2 m-5 rounded">green button<button/>
         </div>
     )
}
```

```jsx
// render.jsx
import ReactDOMServer from 'react-dom/server'
import App from './App'

import { setup } from 'twind'
import { virtualSheet, getStyleTag } from 'twind/sheets'

const sheet = virtualSheet()

setup({ sheet })

export function render() {
  sheet.reset()
  
  const html = ReactDOMServer.renderToString(<App />)
  const styleTag = getStyleTag(sheet)

  return [
    html,
    styleTag
  ]
}
```

```js
//build.js
// Pre-render the app into static HTML.
// run `yarn generate`

const fs = require('fs')
const path = require('path')

const toAbsolute = (p) => path.resolve(__dirname, p)

const template = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Mangos Web site</title>
  <!--add meta tags-->
</head>
<body>
  <div id="root"><!--app-html--></div>
  <script type="module" src="/src/main.tsx"></script>
</body>
</html>`

const { render } = require('.renderjsx')
;(async () => {
    const [appHtml, styles] = await render()

    const html = template.replace(`<!--app-html-->`, appHtml).replace(`<!--add meta tags-->`, styles)

    const filePath = `dist/index.html`

    fs.writeFileSync(toAbsolute(filePath), html)
    
    console.log('static file created ', filePath)
})()
```
It generates styles but does not match. At the moment I thought that was something about overwriting styles. But now watching the docs see [this example](https://twind.dev/docs/handbook/getting-started/using-the-shim.html#static-extraction), changed everything.

Now it works.

I was thinking that get styles by class would be a better approach, something similar as vue, or I don't know if you currently are doing it.

For example: with the above component it returns styles string similar to :
```
// obviously tailwind styles parsed to vanilla css

.tw-qwew {
  relative min-h-screen bg-main-wallpaper bg-cover flex flex-col justify-center
}
.tw--zxcx {
  bg-red-500 p-2 m-5 rounded
}
.tw--asdas {
  bg-green-500 p-2 m-5 rounded
}
```
With this approach we can create webpack, snowpack, rollup, vite plugins to create CSS modules by component or something similar. It's just my opinion at the moment my problem was resolved with [this example](https://twind.dev/docs/handbook/getting-started/using-the-shim.html#static-extraction)

You can close the issue if you want it.
