### ISSUE TITLE
Support Grid customization

### ISSUE THREAD

**Issue by m0t0r** [tw-in-js/twind#133]
Hello,

As far as I see there is no support to customize any of the grid properties (e.g. `gridTemplateColumns`). I tried to search in issues and discussions but didn't find any information. Is there any plans to add such support ?

Thanks

**Comment by sastan** [comment]
Good catch. These are now supported (fdc4118) and released in 0.15.8. Please let me know if there are any issues.

**Comment by m0t0r** [comment]
@sastan amazing! Thanks a lot!
