### ISSUE TITLE
Using `twind/shim` with Next.js SSR?

### ISSUE THREAD

**Issue by jevakallio** [tw-in-js/twind#136]
I'd like to be able to use the default `className=""` syntax in my Next.js application, so I'm using `twind/shim`.

Looking at the [`twind/shim/server` SSR example on the website](https://twind.dev/docs/modules/twind_shim_server.html), I'm not sure how to integrate this with Next.js?  The `shim` function expects a `htmlString` as input, and I don't know where in the Next.js render process to hook this in.

Is it possible?

**Comment by sastan** [comment]
Yes. https://github.com/tw-in-js/example-next/blob/with-shim/pages/_document.js

Sorry. We are working on an update for the docs.

**Comment by jevakallio** [comment]
Whoa, thank you for an extraordinarily quick response! 🙏

**Comment by sastan** [comment]
We are planning on creating a next.js twind plugin that would simplify the code to something like this:

```js
import Document from 'next/document'
import { withTwind } from '@twind/next'

import twindConfig from '../twind.config'

export default class MyDocument extends Document {
  static getInitialProps = withTwind({ ...twindConfig, shim: true })
}
```


Here is a raw sketch of the plugin
```js
import Document from 'next/document'
import * as React from 'react'
import { setup, shim, asyncVirtualSheet, getStyleTagProperties } from 'twind/server'

export function withTwind({ shim: useShim, ...config } = {}, getInitialProps = Document.getInitialProps) {
  const sheet = asyncVirtualSheet()

  setup({ ...config, sheet })
  
  return function getInitialPropsWithTwind(ctx) {
    sheet.reset()
    
    const originalRenderPage = ctx.renderPage

    ctx.renderPage = async (options) => {
      let { html, head } = await originalRenderPage(options)

      if (useShim) {
        html = shim(html)
      }
      
      const { id, textContent } = getStyleTagProperties(sheet)
      
      return {
        html,
        head: [
          ...head,
          React.createElement('style', {
            id: '__next' + id,
            key: id,
            dangerouslySetInnerHTML: {
              __html: textContent,
            },
          })
        ],
      }
    }

    return getInitialProps(ctx)
  }
}
```

**Comment by sastan** [comment]
The plugin has been released: @twind/next – https://github.com/tw-in-js/use-twind-with/tree/main/packages/next

That should simplify things a lot.

**Comment by LonJonn** [comment]
Unfortunately, even with this plugin, I get errors on my clientside.

Although both shim & non-shim versions function correctly, when using the shim version, I get a client-server prop mismatch saying  
`Warning: Prop 'className' did not match. Server: "sm:hover:bg-blue-500 sm:hover:text-green-500" Client: "sm:hover:(bg-blue-500 text-green-500)"`

Another thing I noticed is that whenever Next HMRs, I get a  console.warn stating `Error: [LATE_SETUP_CALL] {}`.

**Comment by sastan** [comment]
I know of both problems.

> Warning: Prop 'className' did not match. Server: "sm:hover:bg-blue-500 sm:hover:text-green-500" Client: "sm:hover:(bg-blue-500 text-green-500)"

That is because the server shim expands the groups within the class attributes. During the hydration react detects that the class attributes do no match. This can be ignored – **but** I would love to see a solution here as well. Just didn't have the time to find one.

> Another thing I noticed is that whenever Next HMRs, I get a console.warn stating Error: [LATE_SETUP_CALL] {}.

Some here.  This can be ignored – **but** I would love to see a solution here as well. Just didn't have the time to find one.

**Comment by LonJonn** [comment]
The first problem seems similar to when trying to use a library like styled-components with next. They solve that problem with a babel plugin. I'm not too sure about this since I haven't looked into it much.

As for the Late setup call, a solution might involve using an internal flag to determine whether the setup function has already been called and then ignoring future setup calls.

**Comment by sastan** [comment]
> The first problem seems similar to when trying to use a library like styled-components with next. They solve that problem with a babel plugin. I'm not too sure about this since I haven't looked into it much.

For babel based frameworks like next that may be a good option.

> As for the Late setup call, a solution might involve using an internal flag to determine whether the setup function has already been called and then ignoring future setup calls.

That is what I thought. Maybe detect if hot reloading is used (`module.hot`) and act on that.

**Comment by surjithctly** [comment]
Same error for me when using `hash: true`; Is there any workaround for this? Any way to run this on the server-side instead of the client?

**Comment by sastan** [comment]
> Same error for me when using `hash: true`; Is there any workaround for this? Any way to run this on the server-side instead of the client?

What do you mean with `run this on the server-side instead`? @twind/next does run on the server for SSR.

**Comment by surjithctly** [comment]
@sastan Currently the page loads normal class and then changes to hashed one `tw-xyzabc` I can literally see that changing in the devtools. Which means the changing happens on the client. Because of this, I have FOUC. 

or am I doing it wrong?
