### ISSUE TITLE
Shim doesn't work for colors/gradients

### ISSUE THREAD

**Issue by dnnsjsk** [tw-in-js/twind#140]
Hey,

I tested the shim using one of our generic templates built with Tailwind, however, it seems like the shim is not converting colors correctly. Check this codepen:

https://codepen.io/DennisYo/pen/WNoYvbJ

**Comment by sastan** [comment]
Twind is compatible with Tailwindcss v2 which has a different color palette.

- [Tailwindcss v2 Colors](https://tailwindcss.com/docs/customizing-colors)
- [Tailwindcss v1 Colors](https://v1.tailwindcss.com/docs/customizing-colors#default-color-palette)
