### ISSUE TITLE
Add important for all styles

### ISSUE THREAD

**Issue by dnnsjsk** [tw-in-js/twind#142]
Hey,

Are there plans to add the "important: true" feature from Tailwind? (https://tailwindcss.com/docs/configuration#important)

The reason why I am asking is that I am using Twind with WordPress new Gutenberg Editor and some of the classes have lower specificity than the styles provided by Gutenberg. I know adding a ! after the styles will make it important, but I would rather specify this in the setup.

Thanks!

**Comment by sastan** [comment]
Sounds reasonable. Adding it to the TODO list and will keep you updated here.

**Comment by sastan** [comment]
Fixed in 0.16.3

**Comment by wpsix** [comment]
is this working in v1?
