### ISSUE TITLE
Adopted stylesheets support

### ISSUE THREAD

**Issue by 43081j** [tw-in-js/twind#15]
It would be useful if we could target a constructed stylesheet which we can then use via `shadowRoot.adoptedStyleSheets = [twindSheet]`.

This would allow us to create the stylesheet once and re-use it across multiple web components without having the side effect of polluting the root document's styles.

I've had a read through the source and it seems the current "sheet" implementation is using CSSOM to add rules to a stylesheet already. However, its default target is a style tag appended to the DOM.

So maybe its as simple as having a different target in the existing cssom sheet? A reference to a sheet rather than one we have in DOM.

Though then the question is, how do we get hold of that per web component?

```ts
class SomeElement extends HTMLElement {
  // ...

  connectedCallback() {
    // how do we get hold of this sheet?
    this.shadowRoot.adoptedStyleSheets = [REF_TO_TWIND_SHEET];
  }

  // Assume this just ends up appending to this.shadowRoot
  render() {
    return `<div class="${tw`bg-black`}">Foo</div>`;
  }
}
```

As you can see, we'd probably need to create the stylesheet ourselves and tell twind to append to it. Like during `setup()` of twind.

Though that leaves us with a choice to make too:

* a monolithic global twind sheet (i.e. we can only setup() once, which means we can only have one tailwind stylesheet to contain everything)
* somehow per-module tell twind which sheet to use (like a setup() per es module)

Could do with some christmas coding so would be happy to have a go at this once i get my head around it

**Comment by 43081j** [comment]
Could in fact also have a lit-element sheet which can append the stylesheet to the static `styles` property of the component.

Which raises another question: how would consumers choose which sheet implementation to use? is that doable via setup()?

**Comment by sastan** [comment]
Thanks for the great write up. That helped a lot.

You are right. Docs where missing. I took your examples and _adopted_   (😄 ) them:

- [Web Components](https://github.com/tw-in-js/twind/blob/main/docs/examples.md#web-components)
- [LitElement](https://github.com/tw-in-js/twind/blob/main/docs/examples.md#litelement)

I hope these help... Let us know what we can improve! Cheers...

**Comment by 43081j** [comment]
For the lit example you can use the static styles property:

```ts
class Foo extends LitElement {
  static styles = [componentStyles];
}
```

So you don't need to mess with custom render roots. 

Also am I understanding correctly in that this means:

- one stylesheet instance
- multiple tw instances (probably one per component)

Would this be any less performant than one tw instance we pass around?

**Comment by sastan** [comment]
> For the lit example you can use the static styles property:
> 
> ```ts
> class Foo extends LitElement {
>   static styles = [componentStyles];
> }
> ```
I'll update the docs. Could not use that in esm.codes

> Also am I understanding correctly in that this means:
> 
> * one stylesheet instance
Jep.

> * multiple tw instances (probably one per component)
Just one as well. A sheet should always be associated with exactly one tw instance. The `tw` is defined in the module scope and used by all component instances.

> Would this be any less performant than one tw instance we pass around?
Performance should be fine. Memory _may_ be an issue because of the caching if you have a lot of tw instance. I have no idea what a lot means here. We'll need to investigate memory usage a little more.

**Comment by 43081j** [comment]
I guess it means in your example, a stylesheet would exist per component. Whereas if we reused the same one across modules, we could have one monolithic TW stylesheet many components can adopt. 

Not sure if either way is better than the other. This way we keep each component contained at least, so each one has its own tw stylesheet. Which can mean some duplication but less risk of side effects etc

**Comment by sastan** [comment]
We added a target prop to the sheet which make the code more readable i hope:

[docs - Lit Element](https://github.com/tw-in-js/twind/blob/main/docs/examples.md#litelement)

```js
// 1. Create separate CSSStyleSheet
const sheet = cssomSheet({ target: new CSSStyleSheet() })

// 2. Use that to create an own twind instance
const { tw } = create({ sheet })

class TwindElement extends LitElement {
  // 3. Apply the same style to each instance of this component
  static styles = [sheet.target]

  render() {
    // 4. Use "own" tw function
    return html`
      <main class="${tw`h-screen bg-purple-400 flex items-center justify-center`}">
        <h1 class="${tw`font-bold text(center 5xl white sm:gray-800 md:pink-700)`}">
          This is Twind!
        </h1>
      </main>
    `
  }
}
```

What do you think?

**Comment by 43081j** [comment]
I like it, maybe you could default to newing one up too if the consumer hasn't passed one. 

Meanwhile I'll have a look at the browser compatibility when I get chance. For the lit usage. It'll need a bit more work I think but will figure it out

**Comment by sastan** [comment]
> I like it, maybe you could default to newing one up too if the consumer hasn't passed one.

In that case we use cssom with a stylesheet `id=__twind` (the existing one or a new one) in the browser and in node we fallback to a no-op sheet:

https://github.com/tw-in-js/twind/blob/main/src/twind/configure.ts#L125

**Comment by 43081j** [comment]
Ah fair enough I completely forgot it's used for the other cases too!

Looks fine to me how it is then :D

Nice work again on this stuff in general. It's a good interesting project

**Comment by sastan** [comment]
Thanks. That means a lot. Closing it now.

Feel free to reopen if you something is not working as expected.

**Comment by sastan** [comment]
@43081j I have opened an PR #19 which would allow to use separate twind/shim instances. Could you share your insight if this makes sense and take a look at https://github.com/tw-in-js/twind/blob/twind-observe/docs/observe.md#example if that example is valid and useful.
