### ISSUE TITLE
Force twind shim to render sheet with all classes even if not present in the dom

### ISSUE THREAD

**Issue by jordwalke** [tw-in-js/twind#155]
Hi, I'm building a utility that will allow you to use twind to render multiple different versions of the style sheet (I'm doing so in an iframe as I have found that twind is pretty "global" in nature - yes, I've read all of the examples about `.reset()`). What I'm doing right now with rendering twind in an iframe to force isolation works fine. I render the `domSheet()` in an iframe and report back the generated stylesheet to the main document. This allows me to non-destructively/statelessly try out different configs (almost like hot reloading). The problem is that the generated stylesheet will only render classes that are actually used in the document. Is there a way to tell the `setup()` to render all classes even if they're not used yet?

I have also tried using the "non shim" version of the module to no avail. Here's my example:

```javascript
            import *  as twindShim from 'https://cdn.skypack.dev/twind/shim';
            twindShim.setup({
              preflight: true, // do not include base style reset (default: use tailwind preflight)
              mode: 'warn', // throw errors for invalid rules (default: warn)
              hash: false, // hash all generated class names (default: false)
              theme: {
                colors: MY_COLORS
              }, // define custom theme values (default: tailwind theme)
              darkMode: 'class', // use a different dark mode strategy (default: 'media')
              sheet: domSheet()
            });
            window.parent.postMessage(
              {
                messageType: "styleData",
                styleInnerHTML: document.querySelectorAll('style')[0].innerHTML
              },
              "*"
            );

```

**Comment by danielweck** [comment]
This feature could also be used at development time to get auto-completion of all possible Tailwind / Twind CSS classe names directly in the web browser / web inspector.

Now, I must say that I wouldn't personally use this development workflow, because I use a build system with near-instant refresh (Preact WMR). But in cases where the DX is slower, the ability to try out styles directly in the web inspector (i.e. without any compile step whatsoever) may be desirable. Caveat: once the classes are entered in the live DOM, they have to somehow be copy/pasted back into the source JSX/whatever ... that's one more reason why I wouldn't personally bother relying on this workflow, but perhaps it would help some developers out there :)

**Comment by jordwalke** [comment]
My workflow doesn't use a build, watcher, or server so that's why it's useful to me (I hope to others as well).

> Caveat: once the classes are entered in the live DOM, they have to somehow be copy/pasted back into the source JSX/whatever ... 

I'm not sure what you meant, and it might be that I miscommunicated. My goal is to just get a single css stylesheet for all the tailwind classes (including dark mode), along with my customizations to the theme. Once I obtain that, I would inject it into the doc as a `<style>` tag, and then manually reference those classes as in `<div class="bg-blue-100">` etc. Did I communicate that part effectively?

**Comment by jordwalke** [comment]
The shim seems to generate that css file - but only for the classnames that are _currently_ referenced in the current DOM. I want to generate it "offline" without knowing what will end up in the DOM, and then use twind without the twind runtime in production, which also gives me the ability to generate multiple themes ahead of time and switch between them by replacing the `<style>` tag. I assume twind has the set of all valid classes somewhere since it is able to warn/error when referencing an unknown class. It stands to reason it could simply generate all of them based on that information into a style sheet.

**Comment by danielweck** [comment]
> My goal is to just get a single css stylesheet for all the tailwind classes...

Sorry, my bad for not being clear: I meant that being able to generate a complete stylesheet of all possible outcomes based on a given Twind configuration (i.e. preflight, plugins, theme etc.) would open another useful development-time feature.

**Comment by danielweck** [comment]
> and then use twind without the twind runtime in production,

That's also my goal in a side project / experiment with Preact WMR static SSR + hydration (see my discussion thread in this repo, it is actually quite a complex issue, depending on the dev/prod framework).

However I would never want to ship a full unpruned stylesheet in my webapp, as this would negate all the byte savings I am aiming for everywhere else :)
And introducing a pruning stage would basically be like working with TailwindCSS (before they introduced their Just In Time compiler), so not really in line with Twind's design principles.

In your use case, do you really intend to ship all TailwindCSS classes in your final production build, or just at development time? (sorry if I misunderstand your goals)

**Comment by jordwalke** [comment]
@danielweck I would probably ship all of the css classes, and only later prune them if it became a bottleneck. With dynamically rendered apps it's very hard to determine which classes will certainly not be rendered. From the root of the app all classes are theoretically "reachable". There are framework level solutions which probably do a good job, but I'm creating a new framework so existing out of the box ones won't work for me.

Is there a way to do what I want with tailwind entirely in the browser? I was interested in twind because it appeared to offer a browser-only solution, and then also some of the "escape hatches" twind has to use JS when necessary (if I ever need it).

**Comment by danielweck** [comment]
just as a point of reference relating to the dev time feature i was describing, see:

https://github.com/windicss/vite-plugin-windicss#design-in-devtools
and
https://twitter.com/antfu7/status/1372368366179028996?s=21

(Twind already provides the mutation observer aka shim, all that’s needed is the “full” stylesheet so that class names can be auto completed directly from the web inspector)

![DCF81178-0ED6-4342-98E4-4B5205522ADE](https://user-images.githubusercontent.com/625201/112135411-a51ea800-8bc5-11eb-9875-e758205bf90c.jpeg)

**Comment by danielweck** [comment]
> Is there a way to do what I want with tailwind entirely in the browser?

Have you looked into Tailwind CSS Just In Time compiler? Sounds like this would hit the sweet spot for you. Although I’m not sure about escape hatches allowing for custom styling (Twind provides a pretty flexible APi, which I value in equal measure to Tailwind’s opinionated design system)

What I am struggling to understand fully is the reason why you are seeking to eliminate Twind runtime whilst you seem ok with including a large stylesheet. Is this motivated by <noscript>?

**Comment by danielweck** [comment]
I am starting to think/realise that I am going off-tangent with my inquisitive comments about Twind runtime :)
If I understand correctly, you just want to collect all the styles in your utility app, but performance isn’t your primary concern?

**Comment by sastan** [comment]
If you do not know which classes will be used the twind runtime and maybe observe/shim are the right way to go.

That leaves us with the implicit global state. Could you render the themed parts of your site within a web component. That would prevent leaking of global styled. Each component would have its own twind instance and stylesheet.

The example in the docs uses tw but twind/observe should work just as well. It would create styles for all elements with that component.

https://twind.dev/docs/handbook/recipes/use-with/web-components.html

**Comment by sastan** [comment]
@danielweck Please do not forget about @twind/cli. Our tool to generate a CSS file - works just like the new tailwindcss jit, but without postcss

**Comment by danielweck** [comment]
> @danielweck Please do not forget about @twind/cli. Our tool to generate a CSS file - works just like the new tailwindcss jit, but without postcss

On that point:

https://github.com/tw-in-js/twind-cli/issues/1

;)

**Comment by danielweck** [comment]
> Please do not forget about @twind/cli. Our tool to generate a CSS file

Sure, but @jordwalke stated:

> The problem is that the generated stylesheet will only render classes that are actually used in the document. Is there a way to tell the setup() to render all classes even if they're not used yet?

**Comment by sastan** [comment]
That leaves: https://github.com/tw-in-js/twind/issues/155#issuecomment-804827343

**Comment by jordwalke** [comment]
> That leaves us with the implicit global state. Could you render the themed parts of your site within a web component? That would prevent leaking of global styles. Each component would have its own twind instance and stylesheet.

That is pretty much what I am doing with an iframe. I'm just wondering why there is even global state in twind.

**Comment by jordwalke** [comment]
I'll look into the cli, but it's idea to do this in the browser.
The reason why I am okay with having a large css file is that I can generate the entire thing at dev time with no build step or dev server (designer friendly), and then later trim out dead css after rendering the page.

**Comment by sastan** [comment]
> I'm just wondering why there is even global state in twind.

There can be several twind instances (`tw`) but we expose one as the default via `import {tw} from 'twind'`. This one can be configured via the `setup` export. This way you can write use components from different packages without worrying about passing the right instance around. Component libraries use the default `tw` import and apps use `setup` for customization.

The instance is responsible for generating the styles and keep them in the right order within its style sheet. It not simply appending styles that would not work with most utilities. Because the order within the stylesheet is important.

**Comment by sastan** [comment]
Could please help me understand your problem better:

1. Do you know which classes should be generated?
2. Should all possible classes including variants permutations be generated?

**Comment by jordwalke** [comment]
Okay, I think that makes sense. I tried instances but it didn't work and I thought somehow instances were "broken" when customizing the theme but now I think that's not the case - it's just that I didn't have any DOM nodes in the page that used the classes for twind to discover which is why it wasn't generating the necessary classes.

**Comment by jordwalke** [comment]
I tried minifying the entire tailwind generated css file, and after compressing with gzip it's only 300kb. That doesn't seem extreme for many use cases. In some cases, the simplicity of not having to run a build step, watcher, server would be worth it imho.
Then imagine adding a couple of config values in `setup()` where you can strip out certain feature you are pretty sure you won't need (either a blacklist or whitelist approach). Wouldn't be surprised if most people could quickly get the file size down to about 150kb without any other worry about dev servers/watchers or build steps. Perhaps not suitable for the fastest site in the world, but universally compatible with any framework, existing or to-be-invented, and very low friction.

**Comment by jordwalke** [comment]
Could please help me understand your problem better:

> Do you know which classes should be generated?

No, I do not know at the point of generating the css.

> Should all possible classes including variants permutations be generated?

I would say yes - at least for this workflow that accommodates the lowest friction use case. I'm not advocating dropping the size optimization features of twind (those are awesome make-or-break features important for many production cases). I'm just suggesting a very low friction workflow for starting projects. I was surprised at how much friction tailwind css required to setup. I think it's an opportunity for twind to offer an easier on-ramp, while being more flexible, *and* without sacrificing the more advanced performance sensitive use cases.

**Comment by sastan** [comment]
Then my question again: Why not use the shim or observe with a custom stylesheet?

**Comment by jordwalke** [comment]
> Why not use the shim or observe with a custom stylesheet? That would allow generating all styles needed.

The shim would generate all styles even if they are not present on the page at the time of generation? I need to capture the generated css and store it in a variable. The reason is that I need to do this multiple times for multiple different themes. I tried using the shim, and it only generated style rules for elements that were currently on the page.

> Why do you need more styles than being used on the page? I'm struggling to understand what you are trying to achieve.
Because I want to eliminate the twind runtime, and I can't anticipate which classes will be necessary ahead of time.

**Comment by sastan** [comment]
> > Why not use the shim or observe with a custom stylesheet? That would allow generating all styles needed.
> 
> The shim would generate all styles even if they are not present on the page at the time of generation?

Yes.

> I need to capture the generated css and store it in a variable. The reason is that I need to do this multiple times for multiple different themes. I tried using the shim, and it only generated style rules for elements that were currently on the page. I also need to customize the setup in a way that can't be configured with an inline `<script type=twind-config>` because I programmatically generate the color pallet.

```js
import { create } from 'twind'
import { virtualSheet, getStyleTag, getStyleTagProperties } from 'twind/sheets'

const sheet = virtualSheet()
const { tw } = create({
  sheet,
  theme: { /* .. */ }
})

// generate all styles here - see next section
tw(allTheStylesArray)

// retrieve the style
getStyleTag(sheet)
// => '<style>...</style>'

const { textContent } = getStyleTagProperties(sheet)
// => just the styles
```

How to get a list of all style rules? In the typescript plugin we do something like that. Maybe we could extract that as an API. Or at least generate a JSON file with all the classes.

> Because I want to eliminate the twind runtime, and I can't anticipate which classes will be necessary ahead of time.

You want to replace a 13kb runtime with 300kb of CSS?

**Comment by jordwalke** [comment]
> You want to replace a 13kb runtime with 300kb of CSS?

Yes, because the runtime is something that costs cpu (correct if I'm wrong) and the css bundle is something that is cached by the browser and can be trimmed with a variety of methods.

**Comment by sastan** [comment]
The script can be cached by the browser. You are assuming the a 300kb CSS files has benefits over a 13kb JS file?

Who does the trimming when?

**Comment by jordwalke** [comment]
The script also executes additional instructions, no? Maybe my understanding is incorrect but I believed that the twind runtime would execute code when the page starts up or when elements are appended to the DOM.

> How to get a list of all style rules? In the typescript plugin we do something like that. Maybe we could extract that as an API.

This seems to be the missing piece. If I had that list I wouldn't need anything else from twind in the first place because I would just make a `<div>` with all those classes before setting up tailwind, then grab all the generated styles.

**Comment by jordwalke** [comment]
Do you have a link to where the list of all the style rules (or at least the list of class names that twind will generate style rules for?)

**Comment by sastan** [comment]
> The script also executes additional instructions, no? Maybe my understanding is incorrect but I believed that the twind runtime would execute code when the page starts up or when elements are appended to the DOM. (Compared to a css file which is cached by the browser, and wouldn't block the execution of other JS instructions).

Have you done any performance tests that may indicate a problem?

**Comment by sastan** [comment]
> Do you have a link to where the list of all the style rules (or at least the list of class names that twind will generate style rules for?)

Which variants do you need? All? In which combinations? `:hover:focus:disabled`?

**Comment by jordwalke** [comment]
@sastan It would be nice to pass a list of variants, and have the set of classnames for those variants. `tw(classesForVariants('hover', 'focus', 'focus-in', 'dark', 'md'))` etc.

**Comment by jordwalke** [comment]
> The CSS file must be parsed as well! A full Tailwind CSS file has blown up several browser tabs already.

That is true. But I was thinking that trimming unneeded css is a solved problem in general (not even framework specific). `trim(cssFile, myHTML) == trimmedCSS`.

My argument for the tradeoff in file size was not "I'd rather have the entire tailwind css file instead of the runtime of twind because it's smaller and faster" it was "I want the simplest possible developer workflow with no build step for multiple themes that I can switch between, and I'll take a file size hit in development mode because it's not _that_ bad for most use cases and trimming the unneeded style rules out later has many solutions and should be a solved problem in general that I assume is solved somewhere in a css-framework agnostic way"

**Comment by sastan** [comment]
Your flow would be:

1. generate all CSS
2. develop
3. purge the CSS
4. use purged CSS in production 

Why not use the twind + shim in development? We can figure out the theming stuff.

And for production use the shim to extract all required rules to generate a static CSS file.

**Comment by sastan** [comment]
> It would be nice to pass a list of variants, and have the set of classnames for those variants. `tw(classesForVariants('hover', 'focus', 'focus-in', 'dark', 'md'))` etc.

That would be quite limiting.

> But I'd even take all possible variants to start if that's the only option.

That would be a several 10.000 CSS rules!

**Comment by sastan** [comment]
> I want the simplest possible developer workflow with no build step for multiple themes

And that is the twind/shim

**Comment by jordwalke** [comment]
Regarding concerns for file size: For development mode: A 6mb css file takes 100ms to parse by the browser and is served "locally" off my file system in about 30ms. The size is not a concern for development mode imho.

**Comment by sastan** [comment]
How about parsing and excuting twind?

**Comment by jordwalke** [comment]
> Why not use the twind + shim in development? We can figure out the theming stuff.

> And for production use the shim to extract all required rules to generate a static CSS file.

It wasn't clear how to do this in a way that allows:
- Multiple different themes/instances computed for elements that are not yet injected into the DOM. Imagine something like a search interaction that doesn't even render into the DOM until interacted with. How does one use twind in development mode with the shim, for multiple themes, then extract all of the styles that _will_ possibly be necessary depending on which interactions will be performed?

Maybe it's documented but it wasn't clear to me.

**Comment by sastan** [comment]
> extract all of the styles that will possibly be necessary depending on which interactions will be performed

If this is so highly dynamic why not use the shim in production and be done with it.

**Comment by jordwalke** [comment]
It seems to me that if one wants to pre-render a stylesheet, the only way to do so with 100% accuracy and not knowing which interactions/frameworks might use which css classes is to take the entire stylesheet with all the variants, which brings me back to the original problem. The only solution here seems to be to include the twind runtime even in production, or to render out all possible classes. Some in this thread have suggested some other third alternative - which is to use twind in development mode, but then somehow take pre-computed stylesheets for production. But that's what I was after in the first place.

**Comment by sastan** [comment]
You talked about a simple no build step process. But want to create a large css file with thousands of rules and the purge it. 

Compare that with import twind/shim. Could you show me some performance stats that show an impact?

**Comment by jordwalke** [comment]
> You talked about a simple no build step process. 

For *development* mode.

For production mode the build step would be done automatically when the user does Chrome "Save As". It's a [very different workflow](https://jordwalke.github.io/paradoc/README.html), so I understand why this might be a round peg in a square hole for twind.

**Comment by sastan** [comment]
But then use them shim in development mode. And then [twind/shim/server](https://twind.dev/docs/modules/twind_shim_server.html) to parse the HTML to generate the styles.

**Comment by jordwalke** [comment]
> But then use them shim in development mode. And then twind/shim/server to parse the HTML to generate the styles.

I would like to do that but it wasn't clear it was even possible to generate multiple themes using only the shim, and toggle between those themes.

**Comment by sastan** [comment]
With https://twind.dev/docs/modules/twind_observe.html you can do that. That is the base module for the shim.

**Comment by jordwalke** [comment]
Even with the server mode, I think I run into issues where there is markup not yet rendered on the page, so it won't generate all the necessary rules.

**Comment by sastan** [comment]
How would then purged the styles?

**Comment by jordwalke** [comment]
I was thinking of some kind of a config where I would "opt in" to various segments of tailwind features. Like "spacing"(includes flex), "colors", and variants ("focus", "focus-in") etc.

**Comment by sastan** [comment]
I still recommend the shim for production you could inline these UMD files

```html
<scrip src="https://unpkg.com/twind/twind.umd.js"></script>
<script src="https://unpkg.com/twind/observe/observe.umd.js"></script>
<script>
  twind.setup({ theme: {}})
  twindObserver.observe(document.documentElement)
</script>
```

**Comment by jordwalke** [comment]
@sastan Is there a way with the shim to be able to later reconfigure the setup/theme? I tried this and my naive approach did not work. The second setup/theme did nothing.
Also, I wanted to have an entirely different theme depending on whether the user was in dark mode or not (I would use that to switch the theme). The issue with tailwind is that the color pallets aren't really easily customizable based on whether or not you are in dark mode. The requirements for normalizing color contrast in different dark/light modes are different.

**Comment by jordwalke** [comment]
For example, I wanted to try using tailwind without having to always specify all of the `dark:` styles in the majority of cases. I think it's possible if you can allow there to be a different color theme for dark mode than for light mode. `bg-grey-400 -> bg-grey-500` would darken if in light mode, but it would lighten if in dark mode. With the right color scheme generator I believe it's possible based on my experience. Of course, you'd still want the ability to specify `dark:` classes if you truly need to do something custom in dark mode but not light mode etc.

**Comment by sastan** [comment]
That is possible. Not reconfigure but start a new instance that would take over with a new theme. It is getting late here. Just to summarize:

- use the shim/observe in development but allow different themes
- use the shim/observe in production within one specific theme

**Comment by jordwalke** [comment]
Why was my second call to setup() not having any effect when I tried this?

**Comment by sastan** [comment]
setup can only be called once

**Comment by jordwalke** [comment]
Cool, if you do get a chance some time I'd love to see an example of calling twind multiple times with different themes using the shim imported from script tags like you were describing.

**Comment by sastan** [comment]
Here is the outline for development:

```js
import { create, observe, cssomSheet } from 'twind/observe'

let activeElement
let activeObserver
function switchTheme(theme) {
  const element = document.head.appendChild(document.createElement('style'))

  element.appendChild(document.createTextNode(''))

   const sheet = cssomSheet({ target: element.sheet })

   if (activeObserver) activeObserver.disconnect()

   activeObserver = observe(document.documentElement, create({ sheet, theme }))

   if (activeElement) activeElement.parentNode.removeChild(activeElement)
   activeElement = element
}

// kick of
switchTheme({ /* ... */ })
```

Not tested. But it should give you a starting point.

**Comment by jordwalke** [comment]
I'll give it a try! Thanks for the help!

**Comment by merodiro** [comment]
@jordwalke about using the unpurged tailwind classes in development. did you watch Adam Wathan's video about how slow it can make your browser if you enable too many variants?

also if you only need to change few variables from the theme in runtime like colors you can use CSS variables

**Comment by jordwalke** [comment]
> also if you only need to change few variables from the theme in runtime like colors you can use CSS variables

Yes, I realized that as well, and was prototyping something.

I didn't see the video discussing the perf of having many unused variants.

**Comment by jordwalke** [comment]
Btw, when debugging I noticed that in Chrome using twind runtime (maybe it's just the approach most recently suggested), there were caught exceptions of the type `"VM57135:1 Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '::-moz-focus-inner{border-style:none;padding:0}'."`

Is there a way to not insert style rules that raise exceptions (even if caught and disregarded)? Depending how hot the code path is, catching an exception can deoptimize the JIT.

**Comment by sastan** [comment]
That is from the preflight. It is valid CSS. Would it be in a CSS file the browser would ignore unknown pesudo-elements. But when using CSSOM insertRule it fails. 

I thought that we have an error handler for that: https://github.com/tw-in-js/twind/blob/main/src/twind/inject.ts#L44

Did you saw it while debugging? 

There is not much that we can do. We just do not know before if the rule will be valid. A try-catch-ignore is the best I think.

**Comment by jordwalke** [comment]
Yeah, probably not much you can do. The browser throws the exception, and it does appear to be caught.

**Comment by sastan** [comment]
Is the proposed solution working for you? I try to find some time later to add the runtime outline.

**Comment by jordwalke** [comment]
Yeah, this seems to be working well, thanks!
If you document this (or if someone links to this issue) - it's worth noting that the style element needs to be appended to the head before using it as the target for twind (at least in my tests).

**Comment by sastan** [comment]
That may be because the `element.sheet` is only available if it exists in the DOM. 🤔

**Comment by sastan** [comment]
Much simplified in v1:

```js
import { setup } from 'twind'

// kick of and call as many times as you want
setup({ /* ... */ })
```

Please give it a try. Here are some links to get you started:

- [The v1 branch](https://github.com/tw-in-js/twind/tree/next)
- [Reference](https://github.com/tw-in-js/twind/blob/next/documentation/40-reference/README.md) until the website is ready
- [Examples](https://github.com/tw-in-js/twind/tree/next/examples) — the [CDN example](https://github.com/tw-in-js/twind/tree/next/examples/twind-cdn) could be a good start

Closing this for now. Feel free to re-open.
