### ISSUE TITLE
Having trouble setting up twind with tsdx 

### ISSUE THREAD

**Issue by sibasishm** [tw-in-js/twind#156]
I am having trouble making tsdx work with twind as there is no documentation on the same and I have to no clue where and how to call `setup()` and how to make it work in example playground compiled using parcel.
Please add documentation on how to setup twind with [tsdx](https://tsdx.io).

**Comment by sastan** [comment]
I do not understand. there is no special configuration for any bundler.

Calling setup is optional. If you need to include something like this in your application entrypoint:

```js
import { setup } from 'twind'

setup({
 /* ... */
})
```

**Comment by sibasishm** [comment]
Yes. It works like charm. I was misunderstood.
Anyway thanks for the response. 🙏

**Comment by sastan** [comment]
Great! If you have any issues please reach out.
