### ISSUE TITLE
Global style injection in plugins doesn't work for twind/shim

### ISSUE THREAD

**Issue by sibbng** [tw-in-js/twind#168]
[Reproduction](https://jspm.org/sandbox#H4sIAAAAAAAAA4VRPW+DMBDd+RVXL2mlJFajTghY2szp0KVbDHbAwtgnfLRFEf+9fEWBLp387u7de6fn6OHt9Prx+X6EgiqTBNHwgBE2j5myDAotpbJJABAVSsgB9NBntUYCalHFrHKyMYpNIwBdoasJrl5Rg1sQiKbt4FK7ClhBhD7kPJN278sWRVbupfri9K2t5L7QFQtmmXH98TpXAGiaXFsfwr0FkDZEzq57AJswNy4VZvN3cF8Yrzrjz+4FsN0dIDUuK88rcreouu3SlP4XuC13T1NgfEpszJHfgoxSJ9s50ekwyIzwPma9BUtIeZoPPkR8Aiv2kvG8ZPR4VO6thk/9BYN7knzkAQAA)

I was expecting "test button1" button to have same paddings as "test button2" button which is takes its styles from `btn` class.

**Comment by danielweck** [comment]
That's not how `plugins` works. The `button` property does not automatically associate with all `button` HTML elements. You need to add `class="button"` in order to "trigger" the `button` plugin, which in turn instantiates a `:global` style.

I personally never use a plugin to inject global styles. Instead, I use Twind's `css()` directive (similar syntax).

**Comment by danielweck** [comment]
Try this:

```html
<!DOCTYPE html>
<html lang="en" hidden>
  <head>
    <script type="module">
      import {setup} from "https://cdn.skypack.dev/twind/shim"
      import {tw, apply} from "https://cdn.skypack.dev/twind"
      import {css} from "https://cdn.skypack.dev/twind/css"

      setup({
        plugins: {
          btn: '!bg-black !text-white'
        }
      })
      

      tw(css({
         ':global': {
           ':root button': apply`px-4 py-2 block bg-red-600 text-green-400`
         }
      }))
    </script>
  </head>
  <body>
    <button class="btn">test button2</button>
    <button>test button1</button>
  </body>
</html>
```

Note the CSS "important" `!` on the foreground and background colour rules. That's because of the higher selector specificity in the `:global` button style.

**Comment by sastan** [comment]
@sibbng As Daniel said: Plugins must be applied to be used. 

If you want all `button` the style you mentioned you can use preflight:

```html
<!DOCTYPE html>
<html lang="en" hidden>
  <head>
    <script type="module">
      import {setup, apply} from "https://cdn.skypack.dev/twind/shim"

      setup({
        preflight: {
           button: apply`px-4 py-2 block`
        },
        plugins: {
          btn: apply`px-4 py-2 block`
        }
      })
    </script>
  </head>
  <body>
    <button class="btn">test button2</button>
    <button>test button1</button>
  </body>
</html>
```

**Comment by sibbng** [comment]
I got it. Same approach was working in twind/cli. Looks like it's a bug with it. It applies plugins without checking installed or not.

**Comment by danielweck** [comment]
Ah yes, Twind CLI does a static analysis of the source code based on a relatively complex set of syntactic rules, so its report may be slightly inaccurate. Would you mind filing a bug in the CLi repository?

**Comment by sibbng** [comment]
Hi, I was trying @sastan's suggestion to define default styles. It was working in the first place but adding background color broke it.

[Repro](https://jspm.org/sandbox#H4sIAAAAAAAAA4WSPW/DIBCGZ/tXXFmSSHFIo3aJ7Cxt51Zql26xDTHIGJA5t7Wi/Pfij1jOUJWFV9zLc8cd8d3z69PH59sLCKzUIYy7DVSqi4RwTUBIxrg+hACx4CnrhJcur6VFwNbyhFSGNYqTIQQgK2tqhDM4jo1dQ2qtauECp9pUQASidXtKc6Y3rmxtmpcbxr8ofkvNqBOyImEQBBOEmepdcI5XwOI/gPe6RTjW0pewPHfEoA/tJ+BytR5NALbmJyUL4cPn6dCvrEE0ej884Wh/ogewbbSDTJm8hKyIas6ix+32OF26zKCqKaR2t8gM/8LNGKO6rIZm06Hb/QzodQhxZlg7TmMoE3KVOpcQn4IckDscy9/FdBA37rnjfu7wuif7VN2H+AXL2MguIAIAAA==)

If you remove `bg-red-500` paddings will come back. I tried with important modifier `!px-4 !py-2` but didn't even apply `!important` on rules.

**Comment by danielweck** [comment]
This works (and `important` is not needed thanks to using `preflight` with a plain `button` selector instead of the `:global` `css()` which I gave as an example (where the `:root` "prefix" in the selector increased its specificity):

```html
<!DOCTYPE html>
<html lang="en" hidden>
  <head>
    <script type="module">
      import {setup} from "https://cdn.skypack.dev/twind/shim"
      import {tw, apply} from "https://cdn.skypack.dev/twind"
      import {css} from "https://cdn.skypack.dev/twind/css"

      setup({
      preflight: {
      	'button': apply('px-4 py-2 block bg-red-600 text-green-400')
      },
        plugins: {
          btn: 'bg-black text-white'
        }
      })
      

/*
      tw(css({
         ':global': {
           ':root button': apply`px-4 py-2 block bg-red-600 text-green-400`
         }
      }))
      */
    </script>
  </head>
  <body>
    <button class="btn">test button2</button>
    <button>test button1</button>
  </body>
</html>
```

**Comment by danielweck** [comment]
> I tried with important modifier `!px-4 !py-2` but didn't even apply `!important` on rules.

In my experience, using `!` as a prefix or suffix (both syntaxes are now supported) for Tailwind classes passed to the `apply()` directive does not work.

**Comment by sibbng** [comment]
> This works 

No it doesn't. I run your code, result, no paddings:

![image](https://user-images.githubusercontent.com/19991745/113455785-5ee4f800-93c0-11eb-879b-a55c63e58ca3.png)

> In my experience, using `!` as a prefix or suffix (both syntaxes are now supported) for Tailwind classes passed to the `apply()` directive does not work.

That makes sense but could be supported.

**Comment by danielweck** [comment]
> No it doesn't. I run your code, result, no paddings:

Yes, I filed a bug (seems to affect other property combinations too):

https://github.com/tw-in-js/twind/issues/171

**Comment by sastan** [comment]
apply is fixed in twind v1.

Please give it a try. Here are some links to get you started:

- [The v1 branch](https://github.com/tw-in-js/twind/tree/next)
- [Reference](https://github.com/tw-in-js/twind/blob/next/documentation/40-reference/README.md) until the website is ready
- [Examples](https://github.com/tw-in-js/twind/tree/next/examples) — the [CDN example](https://github.com/tw-in-js/twind/tree/next/examples/twind-cdn) could be a good start

Closing this for now. Feel free to re-open.
