### ISSUE TITLE
in preflight, weird bug when applying padding selectively on x/y axis (affects other rules combinations too)

### ISSUE THREAD

**Issue by danielweck** [tw-in-js/twind#171]
Repro [esm.codes](https://esm.codes/#aW1wb3J0IHsgaCwgcmVuZGVyIH0gZnJvbSAiaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXYvcHJlYWN0IgppbXBvcnQgaHRtIGZyb20gImh0dHBzOi8vY2RuLnNreXBhY2suZGV2L2h0bSIKCmltcG9ydCB7IHNldHVwLCBhcHBseSwgdHcgfSBmcm9tICJodHRwczovL2Nkbi5za3lwYWNrLmRldi90d2luZCIKCmltcG9ydCB7IGNyZWF0ZU9ic2VydmVyIH0gZnJvbSAiaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXYvdHdpbmQvb2JzZXJ2ZSIKCmNvbnN0IGh0bWwgPSBodG0uYmluZChoKQoKY29uc3QgdHdpbmRPYnNlcnZlciA9IGNyZWF0ZU9ic2VydmVyKCkKdHdpbmRPYnNlcnZlci5vYnNlcnZlKGRvY3VtZW50LmRvY3VtZW50RWxlbWVudCkKCgoKCgpzZXR1cCh7CnByZWZsaWdodDogewogIGJvZHk6IHsKICAgICdAYXBwbHknOiAncC00IGJnLWdyYXktNDAwJywKICB9LAogICdidXR0b24nOiB7CiAgICAnQGFwcGx5JzogJ3JvdW5kZWQteGwgYm9yZGVyLXJlZC0yMDAgYm9yZGVyLTQnLAogICAgJyYnOiB7CiAgICAgICdAYXBwbHknOiAncC0xNiBiZy1ibGFjayB0ZXh0LXJlZC0yMDAnCiAgICB9CiAgfQp9LApwbHVnaW5zOiB7CiAgJ2J1dHQyJzogewogICAgJ0BhcHBseSc6ICdweC00IHB5LTQgcm91bmRlZCBib3JkZXIteWVsbG93LTIwMCBib3JkZXItMiBiZy1ncmF5LTgwMCB0ZXh0LWJsdWUtMjAwJywKICB9LAp9LAp9KQoKY29uc3QgQXBwID0gKCkgPT4gewogIHJldHVybiBodG1sYAogIDxidXR0b24gY2xhc3M9ImJ1dHQxIj50ZXN0IGJ1dHRvbiAxPC9idXR0b24+CiAgPGJ1dHRvbiBjbGFzcz0iYnV0dDIiPnRlc3QgYnV0dG9uIDI8L2J1dHRvbj4KICBgCn0KCnJlbmRlcihodG1sYDwke0FwcH0gLz5gLCBkb2N1bWVudC5ib2R5KQ==)

Change the `p-16` in `preflight` > `button` > `@apply` as per the self-explanatory screenshots below:

```js
import { h, render } from "https://cdn.skypack.dev/preact"
import htm from "https://cdn.skypack.dev/htm"

import { setup, apply, tw } from "https://cdn.skypack.dev/twind"

import { createObserver } from "https://cdn.skypack.dev/twind/observe"

const html = htm.bind(h)

const twindObserver = createObserver()
twindObserver.observe(document.documentElement)

setup({
preflight: {
  body: {
    '@apply': 'p-4 bg-gray-400',
  },
  'button': {
    '@apply': 'rounded-xl border-red-200 border-4',
    '&': {
      '@apply': 'p-16 bg-black text-red-200'
    }
  }
},
plugins: {
  'butt2': {
    '@apply': 'px-4 py-4 rounded border-yellow-200 border-2 bg-gray-800 text-blue-200',
  },
},
})

const App = () => {
  return html`
  <button class="butt1">test button 1</button>
  <button class="butt2">test button 2</button>
  `
}

render(html`<${App} />`, document.body)
```

# `p-16` ok

<img width="1022" alt="Screenshot 2021-04-03 at 07 48 59" src="https://user-images.githubusercontent.com/625201/113471100-09f1c200-9452-11eb-92bf-e59959f5793a.png">

# `px-16` ok

<img width="1022" alt="Screenshot 2021-04-03 at 07 49 48" src="https://user-images.githubusercontent.com/625201/113471107-1544ed80-9452-11eb-9b50-636f45f63744.png">

# `py-16` ok

<img width="1022" alt="Screenshot 2021-04-03 at 07 50 11" src="https://user-images.githubusercontent.com/625201/113471117-242ba000-9452-11eb-9101-87efc8506604.png">

# `px-16` + `py-16` BREAK!

<img width="1022" alt="Screenshot 2021-04-03 at 07 50 43" src="https://user-images.githubusercontent.com/625201/113471129-34437f80-9452-11eb-9cee-ee51edd7e2c2.png">

# `p-16` ok (alternative `&` selector)

<img width="1022" alt="Screenshot 2021-04-03 at 07 51 37" src="https://user-images.githubusercontent.com/625201/113471149-4ae9d680-9452-11eb-93a6-6d3aa45e72ad.png">

# `px-16` (or `py-16`) BREAK!

<img width="1022" alt="Screenshot 2021-04-03 at 07 52 06" src="https://user-images.githubusercontent.com/625201/113471153-56d59880-9452-11eb-843e-15dc2f24ca64.png">

**Comment by danielweck** [comment]
Here is another combination of CSS rules that breaks (nothing to do with padding, in this case):

# ok

<img width="1022" alt="Screenshot 2021-04-03 at 08 05 25" src="https://user-images.githubusercontent.com/625201/113471332-92bd2d80-9453-11eb-944e-3af860f9d85b.png">

# add border color => text color BREAKS!

<img width="1022" alt="Screenshot 2021-04-03 at 08 06 05" src="https://user-images.githubusercontent.com/625201/113471338-9e105900-9453-11eb-9519-c5ae4c62c13b.png">

**Comment by danielweck** [comment]
I inspected `document.stylesheets` and the styles are not generated (which means that it is not a problem of incorrect generated styles, it is that the style resolution algorithm somehow fails to yield the correct CSS rules when combined in a certain way).

**Comment by sastan** [comment]
Yeah. `apply` does not work in some cases because it merges the styles without respecting the precedence. I'm still thinking about a good way to have consistent results.

These are the requirements:

1. same precedence/order
2. support important
3. utilities have a higher specifity

I have several ideas:

given `apply('p-16 bg-black text-red-200') text-blue-500`

1. use `:is`: `tw-XXXX p-16 bg-black text-red-200 text-blue-500`
  
  `:is` has the same specificity as utility classes

  ```css
  :is(.tw-XXXX.p-16) { /* ... */ }
  :is(.tw-XXXX.bg-black) { /* ... */ }
  :is(.tw-XXXX.text-red-200) { /* ... */ }
  .text-blue-500 { /* ... */ }
  ```

2. use `:where`: `tw-XXXX p-16 bg-black text-red-200 text-blue-500`

  `:where` has the zero specificity

  a)
  
  ```css
  :where(.tw-XXXX.p-16) { /* ... */ }
  :where(.tw-XXXX.bg-black) { /* ... */ }
  :where(.tw-XXXX.text-red-200) { /* ... */ }
  .text-blue-500 { /* ... */ }
  ```

  b)
  
  ```css
  .p-16:where(.tw-XXXX) { /* ... */ }
  .bg-black:where(.tw-XXXX) { /* ... */ }
  .text-red-200:where(.tw-XXXX) { /* ... */ }
  .text-blue-500 { /* ... */ }
  ```

3. use our internal methods to calculate specificity and merge rules based on that

**Comment by danielweck** [comment]
Thank you for your detailed analysis, it helps 👍

**Comment by sastan** [comment]
apply has been fixed in twind v1.

Please give it a try. Here are some links to get you started:

- [The v1 branch](https://github.com/tw-in-js/twind/tree/next)
- [Reference](https://github.com/tw-in-js/twind/blob/next/documentation/40-reference/README.md) until the website is ready
- [Examples](https://github.com/tw-in-js/twind/tree/next/examples) — the [CDN example](https://github.com/tw-in-js/twind/tree/next/examples/twind-cdn) could be a good start

Closing this for now. Feel free to re-open.
