### ISSUE TITLE
Using twind to generate css files using theme/default values.

### ISSUE THREAD

**Issue by jordwalke** [tw-in-js/twind#173]
I have a specific use case, which I believe twind can help with.
My problem is that most of my site is using the tailwind pattern, which works well since I control the rendering code - and therefore I can apply classes onto elements. However, a part of my site uses a markdown renderer, and I have some very complex css selectors that are used to render that markdown nicely. I don't control the DOM generation. However, I would like things like colors and spacings to use some of the values from my twind setup. It thought that the css-in-js section of the docs would cover this, but it doesn't look like it does (or maybe the docs just need to clarify?)

For example I would like to generate a css string to be included in a `.css` file that has something like:

```javascript
var myCssText = `
  .markdown-root > p > a {
    color: ${twind.theme.blue.300}
  }
`
```

Is this workflow supported and/or documentation explaining how to do this?

I'm also curious how one would specify variants as well where the answer to "what is the css inline style for `dark:bg-0`?" is not "`background: black`", but rather "well, it depends on if your page has dark mode enabled, and that depends on if your theme was set up with `darkMode:class` or not. So the answer to the question would not necessarily be a style but selector + style.

**Comment by jordwalke** [comment]
For example I tried:

```
var styles = twindCss.css({
  '&::before': { content: '"🙁"' },
  '&::after': { content: '"😊"' },
})

twind.tw(styles)
```

which outputs `"tw-y2b4k1"`, which is not what I'm looking for. I'm looking for the actual styles.

**Comment by danielweck** [comment]
In my project I recently migrated more of my "global" styles to `setup()` `preflight` (by "global" I mean a design escape hatch that is "selector-oriented" rather than the baseline method of combining styles with "utility classes").

Twind's API is super versatile (i.e. many ways of combining `css()` `style()` and `apply()`, in `preflight`, `variants` and `plugins`) ... but as a result I still get confused sometimes :)

The following code snippet is just for illustration purposes, but this shows the kind of high-specificity selector I tend to use in order to enforce certain styles in designated DOM fragments:

```js
preflight: (preflight, { theme }) => {
  const serif = theme('fontFamily.serif');
  return css(preflight, {
    ':root > body h1': {
      'font-family': `"Roboto Slab",${serif}`,
    },
    ':root > body a:not([class])': {
      '@apply': 'text-blue-600',
      '&:hover': {
        '@apply': 'text-blue-800',
      },
    });
},
```

I also like using `setup()` `plugins` to scope DOM fragments:
(note the use of raw CSS)

```js
plugins: {
'test-scope': {
    '&': apply('p-4 m-4 bg-black text-white'),
    '&> p': {
        '@apply': 'p-8 bg-red-100 text-blue-800',
        '&> span': apply('underline px-4 py-4 text-3xl'),
    },
    '& h4': apply('uppercase font-extrabold'),
    '&> h4': css`
        padding: 1em;
        background-color: red;
    `,
},
}
```

```html
<div class="test-scope">
    <p>
    this is a paragraph <span>with a child span</span> element.
    </p>
    <h4>heading</h4>
</div>
```

=>

<img width="632" alt="Screenshot 2021-04-06 at 10 28 16" src="https://user-images.githubusercontent.com/625201/113689985-d4074480-96c2-11eb-9677-5383f56f85fd.png">

**Comment by sastan** [comment]
You can combine Daniels solution with the extraction and dark mode support from [this example](https://jspm.org/sandbox#H4sIAAAAAAAAA6VW3W7bNhS+rp7iRAtqO4iktMWwwZWFAFm3XaxFgbR3uwgtHUtsKFIgKTuGYWDv0Dfsk+yQkvyTZEWaXdgSyXO+7/x8pJieFCq36wahsrXIgnR4ICuyACCt0TLIK6YN2lnY2kX0a7hfkKzGWbjkuGqUtiHkSlqUZLjiha1mBS55jpEfnAOX3HImIpMzgbNXBJMmHU86V8Xao5pc88aC0fksrKxtzDRJWtnclnGu6sSuuCy6/7iti/iLCbM06Xye7G4qRGv6x/NhcmPc73sA7hUgOYMrjcwiUCFbY1VNlTCWyRzBKihRonarNdO3hVpJMA3mfMFzMHYt0MBZ4nGotoZicmHDDHwQ110OS65ty4QfjScHxhsyg+1gHec+jPHGWwA0GheCl5WdwoIJg+f9vKcYBkkCrfGhC2YMFBQk1KpACs5FXa5dDqZSKyj4YoGauj/EzSUoidCwkgbjAhesFcQ1qrHgbDTpCRziewKkBU8x2jGfgbIValCN5ZTOUIftJAhe+OXfcMGJoEc2j9erm+tLcEUNo6bd9BQvIYMGhnoAXLKmEWuYl1Gp2Tp6dXEBzV30Bpp19PrtYLWzzqgqe19HKJSewummqzbFXuN45GdNPBctRj9fXIwm2x0SbIOjZ/foghukc93Fv1D6oPZHGfrpZ+X3C+Vn8c7usn0b/I/kXn83uZtgyOiPh4If9EJSIuBe432S5PHZcFnCZSnUnAmnt4otEeLBP9JKWWDUfxSYW6rU3vXkBHq3QhGFJMM1YZu2cQcWLJnmTJJ0vv3zldxJ58Kili46o0TrdAdzFKTuHeQZ/E4MXsP7PUBbZAqX3eTY7SvUJvLFodPOlWrqujShDXm6cW9b2pU9ol2NH2vdkO2+B/fyPWzO6aYr4fZgLva6eHlI+aA1Q28mwXGphzOp6Hf9YW1X3Fb/JUVv/YG+CV6PN7uwvP20j2OvhHd3VL/c+p7vKY93MZmlfiaL45jOWP/6yBb/xMp7p2KJ9rpfGXtFTQbADS/otCG80bnX/1X31erntsfom0OT/WH6kOSjVg1qy9Ec0vk/+sa2NbnH7jsXc0mp/vnp/V+E1bX7RUqayahczi+2TBNs/EVxOR79LWlTpYlbD46aTYxDG/tHWvBl14JZeKSVcHAlnuxoZQopg4r0Ogt/CjMGgsvbNGGDfZoQZBY8gn+62fV6ewR/uPBsdKeTHepTEvNWP5bbff4n5Nez/ECKO5IHA9f4/ZWBbkLdFYhuRP4C9i+lej0/mAkAAA==):

**Comment by danielweck** [comment]
PS: I've updated my `'test-scope'` plugin example with the functional form, to illustrate how to use `theme`.

**Comment by gojutin** [comment]
Just want to shout out to @jordwalke - Love your work :)

**Comment by sastan** [comment]
This is now possible in twind v1.

```js
import { twind, virtual, css, stringify } from 'twind'
const tw = twind({ /* config */ }, virtual())

const myCssText = css`
  .markdown-root > p > a {
    color: theme(colorsblue.300);
  }
`
// start fresh
tw.clear()
// inject styles
tw(myCssText)
// grep css strings
const cssString = stringify(tw.target)
```

Please give it a try. Here are some links to get you started:

- [The v1 branch](https://github.com/tw-in-js/twind/tree/next)
- [Reference](https://github.com/tw-in-js/twind/blob/next/documentation/40-reference/README.md) until the website is ready
- [Examples](https://github.com/tw-in-js/twind/tree/next/examples) — the [CDN example](https://github.com/tw-in-js/twind/tree/next/examples/twind-cdn) could be a good start

Closing this for now. Feel free to re-open.
