### ISSUE TITLE
"Unknown utility" TS warning on certain class names

### ISSUE THREAD

**Issue by bryceknz** [tw-in-js/twind#174]
Since migrating to Twind, I have noticed some class names throwing TS warnings.

This is by no means an exhaustive list, but I've noticed them on the following class names:
- `flex-gap-4`
- `mx-auto`
- `mt-auto`

---

### Screenshots:
![image](https://user-images.githubusercontent.com/25199713/113700020-3ade2b00-96ce-11eb-817d-418809d2e271.png)
![image](https://user-images.githubusercontent.com/25199713/113700061-46c9ed00-96ce-11eb-8981-914722f8b6ba.png)

**Comment by lukejacksonn** [comment]
Thanks for reporting this, I think `flex-gap` is a missing custom plugin type definition. The margin errors should come with the Twind dev tools so will try get a fix in for that asap 👍

**Comment by sastan** [comment]
@bryceknz Which twind version are you using? The margin errors should be fixed in one of the latest version (currently in mobile, can not check which version).

**Comment by bryceknz** [comment]
Hi @sastan, thanks for that info! I'm running `0.16.7`, I can see now that it's resolved in a later release, cheers! 🎉

**Comment by sastan** [comment]
The VS-Code and the typescript plugin haven't been updated to work with the next branch. That is still an open issue.

**Comment by IgnusG** [comment]
> I'm using the `next` branch and it's still present in most of the tw classes. And I've noticed that neither VSCode Tailwind official plugin nor Twind plugin are working as expected.
> 
> Is it something broken or am I doing something wrong / not enabling something?

Support for v1 for intelli tracked in https://github.com/tw-in-js/vscode-twind-intellisense/issues/7 I believe
