### ISSUE TITLE
Is there a way to obfuscate the Class Name?

### ISSUE THREAD

**Issue by lamualfa** [tw-in-js/twind#18]
## Problem

To complicate the theft of components that have been made, I usually obfuscate the existing class names, so that the thief has difficulty refactoring the code he took on the original website.

But, this library is run at runtime, I am confused about how to obfuscate the existing class names. Do you have any suggestions?

### My Expectation

**Input**
```js
tw`text-gray-100 bg-green-200 relative`
```

**Output**
```js
"a b c"
```
- `text-gray-100` has been obfuscated to `a`
- `bg-green-200` has been obfuscated to `b`
- `relative` has been obfuscated to `c`

> The obfuscating process above is only doing in the Production stage.

Thanks.

**Comment by sastan** [comment]
I think what your are looking for is https://github.com/tw-in-js/twind/blob/main/docs/setup.md#hash

```js
import { tw, setup } from 'twind'

setup({ hash: true })

tw`h-screen bg-purple-400 flex items-center justify-center`
// => tw-s71qpw tw-15v4579 tw-1sv1rgs tw-6q7m7e tw-1u5qtu
```

[Live and interactive demo](https://esm.codes/#aW1wb3J0IHsgdHcsIHNldHVwIH0gZnJvbSAnaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXYvdHdpbmQnCgpzZXR1cCh7IGhhc2g6IHRydWUgfSkKCmRvY3VtZW50LmJvZHkuaW5uZXJIVE1MID0gYAogIDxtYWluIGNsYXNzPSIke3R3YGgtc2NyZWVuIGJnLXB1cnBsZS00MDAgZmxleCBpdGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXJgfSI+CiAgICA8aDEgY2xhc3M9IiR7dHdgZm9udC1ib2xkIHRleHQoY2VudGVyIDV4bCB3aGl0ZSBzbTpncmF5LTgwMCBtZDpwaW5rLTcwMClgfSI+CiAgICAgIFRoaXMgaXMgVHdpbmQhCiAgICA8L2gxPgogIDwvbWFpbj4KYA==)

**Comment by lamualfa** [comment]
@sastan Yeah, thanks.
