### ISSUE TITLE
Specified hash function doesn't affect `apply`?

### ISSUE THREAD

**Issue by johncomposed** [tw-in-js/twind#190]
Hi!

So I was looking into integrating this library into a project and was surprised that I couldn't change the hashing that happens via `apply` when I pass in a hash function the the setup. I think (though I'm not sure) this is because [/twind/configure.ts#L229](https://github.com/tw-in-js/twind/blob/v0.16.16/src/twind/configure.ts#L229) directly calls `cyrb32` instead of `(hash || cyrb32)` like className does a few lines below. 

Is there any reason for that to not just be `(hash || cyrb32)`? 

Alternatively, is there another way I could adjust how `apply` creates class names?

**Comment by sastan** [comment]
> Is there any reason for that to not just be (hash || cyrb32)?

The reason is that the `hash` option may be no-op (which is default). We can not use a JSON stringified name as a classname. Therefore we always use cyrb32 to create a unique name. 

> Alternatively, is there another way I could adjust how apply creates class names?

We could change the line you pointed out to check if the `hash` option is infact no-op and only then use `cyrb32`. 

May I ask why you want to adjust the class name generated for `apply`? Is for debugging / labeling?

**Comment by johncomposed** [comment]
> May I ask why you want to adjust the class name generated for apply? Is it for debugging / labeling?

Bingo. I was hoping for something similar to `@emotion/css`'s [labels](https://emotion.sh/docs/labels). 


I figured the cleanest way to do this would be a utility plugin-type thing to allow classnames like `label:btn`, which my hash fn would look for to generate out something like `btn::[css hash]`. And for handling the apply'd classnames (let's say I'm adding on a set of styles that include `label:ghost`) I'd also look for the `::` (or whatever separator I use) of the already hashed styles and when they show up in the hash fn again I'd concat them into something like `btn-ghost::hash`. 

Details notwithstanding, convenient debugging and having some way of seeing where your generated styles came from would be huge. I started pulling this lib into my project on a new branch but never merged it in cause that was one tradeoff I didn't quite want to give up on. 🤷 If there's something I'm missing here lmk!

**Comment by sastan** [comment]
Debugging/Labeling is really a weak spot right now. It may be difficult to get this into the current architecture. But it is one of the features that are a _must_ for the v1 release.

We already have an open issue for that #76. I will close this one but reference your idea of contacting labels.

**Comment by sastan** [comment]
@johncomposed If that isn't what you want feel free to re-open.
