### ISSUE TITLE
fix: expanded support for deep nested colors in the theme

### ISSUE THREAD

**Issue by marbemac** [tw-in-js/twind#192]
Related to https://github.com/tw-in-js/twind/pull/31 - might it make sense to support nested colors in all the core plugin spots that deal with color? E.g. `backgroundColor`, `borderColor`, etc.

**Comment by sastan** [comment]
This should work in twind v1.

Please give it a try. Here are some links to get you started:

- [The v1 branch](https://github.com/tw-in-js/twind/tree/next)
- [Reference](https://github.com/tw-in-js/twind/blob/next/documentation/40-reference/README.md) until the website is ready
- [Examples](https://github.com/tw-in-js/twind/tree/next/examples) — the [CDN example](https://github.com/tw-in-js/twind/tree/next/examples/twind-cdn) could be a good start

Closing this for now. Feel free to re-open.

**Comment by marbemac** [comment]
Alllmost works! However, if a theme value leverages nested pattern, and then is spread into another area, there seems to be an issue.

```ts
// @ts-expect-error https://github.com/tw-in-js/twind/issues/257
export default defineConfig({
  theme: {
    colors: {
      current: 'currentColor',
      gray: {
        DEFAULT: 'var(--color-gray-500)',
        100: 'var(--color-gray-100)',
        200: 'var(--color-gray-200)',
        300: 'var(--color-gray-300)',
        400: 'var(--color-gray-400)',
        500: 'var(--color-gray-500)',
        600: 'var(--color-gray-600)',
        700: 'var(--color-gray-700)',
        800: 'var(--color-gray-800)',
        900: 'var(--color-gray-900)',
      },
    },

    backgroundColor: ({ theme }) => ({
      ...theme('colors'),
    }),
  },
});

// ... and then using somewhere else, this doesn't seem to work
tw('bg-gray');
```

Not a huge deal for now, I've just flattened the colors to avoid the nesting thing. A nice to have, but it might break compat with folks using twind pre v1.
