### ISSUE TITLE
Extract out grouping syntax in JS bundles

### ISSUE THREAD

**Issue by rschristian** [tw-in-js/twind#195]
## Problem Description
A fair number of the apps I write these days are too small to really justify the runtime cost of Twind. Nothing wrong with that, my use case isn't a common one. So what I'm trying to do is work out a decent prerendering system for Twind, minus the runtime.

What I'm currently doing is using `@twind/wmr`'s prerender functionality, but not its hydration. The issue I'm running into is with the group syntax. While the prerender extracts the classes out of the group syntax (`text(2xl blue)` -> `text-2xl text-blue`), this syntax is not extracted out for the JS bundles. This results in broken styling when the JS that's still using the grouped syntax hydrates on the page.

## Solution
So in essence what I'm looking for is for Twind to provide the grouping expansion as a standalone utility of sorts (looks to mostly be [parse.ts](https://github.com/tw-in-js/twind/blob/main/src/twind/parse.ts), but I might be missing some pieces).

As a standalone, users could use it to say rewrite JS bundles as a CLI tool, or plugin for their build system. It'd be really cool to have a Rollup plugin or something rewrite this:

```
function $e(e){return W`<h3 class="text(3xl blue)">${e.name}</h3>`}
``` 

into this:

```
function $e(e){return W`<h3 class="text-3xl text-blue">${e.name}</h3>`}
```

I get that this would be one more thing to maintain, and might be super niche, but I think it'd be pretty cool and useful!

Edited for clarity

**Comment by rschristian** [comment]
Finally got back around to this.

@sastan Would it be reasonable to additionally export [`configure()`](https://github.com/tw-in-js/twind/blob/94dd8e14546daf9f6e47ec3c7362bc51579f1853/src/twind/configure.ts#L67)? Being able to leverage twind to generate valid classnames from grouped syntax (for example) would be quite nice. Users could then easily utilize this in a wide number of tools, avoiding the need for a runtime when it's not actually required.

Granted I've only skimmed the repo, so maybe this isn't the best way to get this functionality? Thinking of the end goal being something like:

```js
import { configure } from 'twind';

const twind = configure({
  theme: { ... }
});

const validClasses = twind.process('text(blue 2xl) md:(hover:(text(red 3xl) bg-green))');
// -> 'text-blue text-2xl md:hover:text-red md:hover:text-3xl md:hover:bg-green'
```

**Comment by sastan** [comment]
I can see that this might be helpful.

To recap:

> We want a function that parses a grouped classnames string and returns an expanded classnames string.
>
> We do do not care about theme values or any context related stuff. Just expand all groupings.

`parse` returns an array of rules. We would need to re-create classnames from that (https://github.com/tw-in-js/twind/blob/94dd8e14546daf9f6e47ec3c7362bc51579f1853/src/twind/configure.ts#L54:L62).

Something like:

```js
// Name is open for debate: maybe expand
export const ungroup = (className) => parse(className).map(rule => stringify(rule)).join(' ')
```

**Comment by rschristian** [comment]
What I've been doing currently is just vendoring `parse` and recreating the class names from the rules. If you're willing to go a step further than simply adding `parse` to the public API, but adding a way to convert a grouped set of class names, then that's all the better.

I can definitely write up a PR here, just wanted to gauge your feelings on it first.

**Comment by sastan** [comment]
I wouldn't like to expose `parse` as it may change and I see it as an internal function. If you could hack a PR that would be great otherwise I will try to do it on the weekend..

Here are some pointers:

- move [stringify and stringifyVariant](https://github.com/tw-in-js/twind/blob/94dd8e14546daf9f6e47ec3c7362bc51579f1853/src/twind/configure.ts#L54:L62) into another file (maybe https://github.com/tw-in-js/twind/blob/94dd8e14546daf9f6e47ec3c7362bc51579f1853/src/twind/helpers.ts) and rename `stringify` to `stringifyRule`
- create `src/twind/ungroup.ts` with `export const ungroup = (className) => parse(className).map(rule => stringifyRule(rule)).join(' ')` – name is update for debate
- re-exports `src/twind/ungroup` from `src/index.ts` 

That should work. Thanks in advance. Very much appreciated.

Do we need to update the react, preact, next integrations to prevent the mismatch error?

**Comment by rschristian** [comment]
Gotcha, alright. I'll see if I could get a PR together here, though with end-of-the-year stuff at work and the holidays coming up, not sure I'll have something by this weekend. But we'll see.

The mismatch error only occurs if you prerender and do not include Twind in the client-side bundle. As far as I know none of the integrations do this by default, this is strictly an issue I and a few others have brought upon ourselves. I don't think there's anything that will need updates.
