### ISSUE TITLE
Not compatible with Tailwind 2.2

### ISSUE THREAD

**Issue by dbackeus** [tw-in-js/twind#203]
Noticed that 2.2 features were not implemented when I tried the "[shorthand color opacity syntax](https://blog.tailwindcss.com/tailwindcss-2-2#shorthand-color-opacity-syntax)". Eg. `bg-white/40` instead of `bg-white bg-opacity-40`.

Full list of changes: https://blog.tailwindcss.com/tailwindcss-2-2

**Comment by u3u** [comment]
Any news? Other than that there are more new features that we are looking forward to using in twin:
https://tailwindcss.com/docs/just-in-time-mode#new-features

- Color opacity shorthand
- Per-side border colors
- Pseudo-element variants
- Content utilities
- Exhaustive pseudo-class support
- Caret color utilities
- Sibling selector variants
- Simplified transform, filter, and backdrop-filter composition

**Comment by dbackeus** [comment]
Looks like ETA is October. From the twind Discord when asked about this issue:

<img width="592" alt="Screenshot 2021-09-13 at 09 38 15" src="https://user-images.githubusercontent.com/3461/133043102-f83d0cc7-e792-4ccd-920a-54322b2f8378.png">

**Comment by sastan** [comment]
Took longer than oktober. Twind v1 is almost ready. It is compatible to Tailwind v3.

Please give it a try. Here are some links to get you started:

- [The v1 branch](https://github.com/tw-in-js/twind/tree/next)
- [Reference](https://github.com/tw-in-js/twind/blob/next/documentation/40-reference/README.md) until the website is ready
- [Examples](https://github.com/tw-in-js/twind/tree/next/examples) — the [CDN example](https://github.com/tw-in-js/twind/tree/next/examples/twind-cdn) could be a good start

Closing this for now. Feel free to re-open.
