### ISSUE TITLE
Twind works with JS disabled?

### ISSUE THREAD

**Issue by fikse** [tw-in-js/twind#204]
I visited https://twind.dev/ with Javascript disabled in both Chrome and Firefox, but the pages are still styled as expected.

What is this dark magic?

**Comment by rschristian** [comment]
Sure, you can statically extract styles, see https://twind.dev/usage-guides/ssr.html

**Comment by lukejacksonn** [comment]
The documentation site is also a vitepress site and so doesn;t use twind all that much internally 😅  either way as @rschristian points out, you can achieve this on a Twind only site using SSR and static extraction!

Closing here, if you have further questions on this, matter feel free to open up a discussion.
