### ISSUE TITLE
Square bracket syntax is not generating any styles when a comma is present (constructable stylesheets)

### ISSUE THREAD

**Issue by dnnsjsk** [tw-in-js/twind#206]
Hey,

I am using Twind with Constructable Stylesheets inside Stencil.js components and using following utilility:

```js
import { create, cssomSheet } from 'twind';
import 'construct-style-sheets-polyfill';
import * as colors from 'twind/colors';

export function cssTw(el) {
  const sheet = cssomSheet({ target: new CSSStyleSheet() });
  const { tw } = create({
    sheet,
    theme: {
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        black: colors.black,
        white: colors.white,
        'blue-gray': colors.blueGray,
        'cool-gray': colors.coolGray,
        gray: colors.gray,
        'true-gray': colors.trueGray,
        'warm-gray': colors.warmGray,
        red: colors.red,
        orange: colors.orange,
        amber: colors.amber,
        yellow: colors.yellow,
        lime: colors.lime,
        green: colors.green,
        emerald: colors.emerald,
        teal: colors.teal,
        cyan: colors.cyan,
        sky: colors.lightBlue,
        blue: colors.blue,
        indigo: colors.indigo,
        violet: colors.violet,
        purple: colors.purple,
        fuchsia: colors.fuchsia,
        pink: colors.pink,
        rose: colors.rose,
      },
    },
  });
  el.adoptedStyleSheets = [sheet.target];

  return tw;
}
```

Everything works, however, classes that are generated using the bracket syntax and contain a comma have no styles in them:
![PixelSnap 2021-08-08 at 21 12 58@2x](https://user-images.githubusercontent.com/73965001/128643215-6784ecea-df2c-4ddc-a91e-81dd45ffaa98.png)

**Comment by sastan** [comment]
It seems that we generate invalid css value. That is because we just take the value in between the brackets and use it as a value. We should differentiate between plain values, list values, etc...

**Comment by sastan** [comment]
This will be fixed once v1 is released. 

But please noite that you should use `_` as [replacement for a space](https://tailwindcss.com/docs/adding-custom-styles#handling-whitespace): `grid-cols-[1fr_500px_2fr]`

**Comment by brycefranzen** [comment]
This is still broken if using responsive utility helpers:
`lg:grid-cols-[3fr_1fr]`

Results in this:
```
@media (min-width: 1024px) {
    .lg\:grid-cols-\[3fr_1fr\] {
    }
}
```

It works fine without the `lg:` modifier
