### ISSUE TITLE
Css order 

### ISSUE THREAD

**Issue by Chetan11-dev** [tw-in-js/twind#209]
in tailwind  p-4 px-2 results in the final  padding: 16px 8px
in twind  p-4 px-2 results in the final  padding: 16px 16px
px-2 should come after p-4 but the opposite happens.

**Comment by rockmandash** [comment]
You can't rely on CSS class order, it's based on when the rules are registered.

That's why there's an `override` variant, so you will have to do this `p-4 override:px-2`
