### ISSUE TITLE
CSS `content` property is dropped by twind/css directive

### ISSUE THREAD

**Issue by DavidJones418** [tw-in-js/twind#21]
I haven’t been able to get the examples in the [`twind/css` docs](https://github.com/tw-in-js/twind/blob/main/docs/css-in-js.md) to work as the [`content` property](https://developer.mozilla.org/en-US/docs/Web/CSS/content) doesn’t seem to be processed by the CSS directive. Other properties (`background` in the example) are passed through and displayed when `::before` or `::after` content is set manually.

### Repro [[pen](https://codepen.io/davidjones418/pen/RwGjmom)]

```js
import { css } from "https://cdn.skypack.dev/twind/css";

const styles = css({
  "&::before": { background: "red", content: "🙁" },
  "&::after": { background: "green", content: "😊" }
});

document.body.innerHTML = `
  <style>
    /* override */
    .${styles}::after { content: "👋" }
  </style>
  <p class="${styles}">Hi!</p>
`;
```

**Actual render:** ![image](https://user-images.githubusercontent.com/67751672/103172209-c7fd2280-4849-11eb-8cca-cbc4e1d69b39.png)

**Expected render:** ![image](https://user-images.githubusercontent.com/67751672/103172201-adc34480-4849-11eb-80fc-f3d6e94f86dd.png)

**Comment by lukejacksonn** [comment]
Good spot, I wonder why.. will look into it. Thanks for the repro 🙇

**Comment by lukejacksonn** [comment]
Ahh ok, I have seen this before somewhere.. the reason the `content` keys are being stripped is because the values should be wrapped in quotes and the translate process will strip these usually.

So the following works because the resolved value is `'😊'` as supposed to `😊`:

```js
const styles = css({
  "&::before": { background: "red", content: "'🙁'" },
  "&::after": { background: "green", content: "'😊'" }
});
```

**Comment by sastan** [comment]
The [content property](https://developer.mozilla.org/en-US/docs/Web/CSS/content) can have several values that are not in quotes. User that are using `content` must use a valid CSS value. In this case `'"😊"'` (notice the additional `'` ).

We should adjust the examples.

**Comment by DavidJones418** [comment]
Ah that makes sense! Now that you've explained it this feels like normal CSS-in-JS behavior, including in tailwindcss plugins. I'll open a PR to fix the examples in the docs.
