### ISSUE TITLE
tailwind plugin config - daisyUI

### ISSUE THREAD

**Issue by Zegoverno** [tw-in-js/twind#211]
On tailwind these are the steps:
1. Install DaisyUI: npm i daisyui
2. Then add DaisyUI to your tailwind.config.js: 
module.exports = {
    plugins: [
      require('daisyui'),
    ],
  }

On twind I couldn't pass a node-module to the plugin, any ideas?

**Comment by rschristian** [comment]
See #32

Current API isn't compatible

**Comment by sastan** [comment]
Difficult to implement because both APIs are quite different. 

Closing it. If there is still a need to have this please re-open.

**Comment by esphoenixc** [comment]
is it still not supported??

**Comment by craigerskine** [comment]
I'd really like this too. Hoping it's not impossible.

**Comment by justinmchase** [comment]
> Closing it. If there is still a need to have this please re-open.

There is still a need.

**Comment by Sleepful** [comment]
I am not going to use twind if it does not support very essential tailwind plugins 🤷 
your API is broken if it cannot work well with tailwindcss plugins

**Comment by craigerskine** [comment]
> I am not going to use twind if it does not support very essential tailwind plugins 🤷
> your API is broken if it cannot work well with tailwindcss plugins

I wouldn't go that far. Twind's grouping syntax is a billion times better than anything out there right now. I can live without Daisy. For me it's just a "nice-to-have".

Your only other option is UnoCSS and that has some big issues and NO shortcut/grouping options (attributify does not count).

Personally, I'd rather they add options for auto foreground color contrast similar to auto dark mode.

**Comment by justinmchase** [comment]
> Twind's grouping syntax is a billion times better than anything out there right now.

Can you make a PR to tailwindcss and contribute the improvement there so the plugins can work here? I agree with @Sleepful I am basically unable to use this tool without this feature. I understand some people are going to be fine or even enjoy making an entire component library from scratch and this is going to work well for them but I really just need something that looks half-way decent out of the box with some basic customization 9/10 times.

So I have no problem with twind, looks cool but I literally cannot figure out how to use it at all without making everything from scratch.

**Comment by rschristian** [comment]
> > Twind's grouping syntax is a billion times better than anything out there right now.
> 
> Can you make a PR to tailwindcss and contribute the improvement there so the plugins can work here?

Do you mean add grouping to Tailwind? That cannot be done with their current approach, it requires a runtime or build time transform.

**Comment by Sleepful** [comment]
The smugness in that last comment, damn! 

“you don't know what you want, go use one of those dirty component frameworks”

Attitudes speak volumes for the quality of a project.

**Comment by rschristian** [comment]
Sorry, but I think you misunderstood. It's not smugness at all, nor is there anything wrong with using component libraries. They're very, very popular for a reason.

It just doesn't really make much sense to use a CSS framework when your desired outcome is prebuilt components. CSS frameworks are to help you write CSS, after all.

I'm also completely unaffiliated with the project; I donate to it, and have made a few tiny patches, but that's the extend of it.

**Comment by craigerskine** [comment]
I've successfully used [MUI](https://mui.com/material-ui/) and Twind together. Best of both worlds IMO.

**Comment by justinmchase** [comment]
No, he's right thats exactly what I want is a component library. But isn't that the request of this issue? The component library is daisyui, its built using tailwind, it seems like it could be compatible with twind...

I am just playing around with deno fresh, it came with twind out of the box, I'm trying to plug in a component library of some kind because I want to make an app not make an entire component library from scratch. But yeah there appear to be no compatible component libraries for twind so I don't know what to do. My options appear to be to do my whole ui from scratch or figure out how to take twind out of fresh and get tailwind / daisy or some other library in?

It just seems to me like the whole point of twind is to make component libraries which people then go forth and use... so to have no component libraries at all seems quite perplexing.

**Comment by rschristian** [comment]
> it seems like it could be compatible with twind

Unfortunately, not out of the box, no. It's built using Tailwind's plugin API, which Twind differs from. You could probably port it, but it would require a time investment.

> My options appear to be to do my whole ui from scratch or figure out how to take twind out of fresh and get tailwind / daisy or some other library in?

I don't believe so? You should be able to use any standard (p)react component framework with Fresh. Twind is just a (blessed) option if you want to use it as your CSS framework. You don't, so I'd probably look into pure component libraries instead.

chakra, radix, and rmwc could be valid options, they're all quite popular and I believe they all work with Preact.

Full disclosure, I'm on the Preact core team. You can certainly let me know if you run into issues.

> It just seems to me like the whole point of twind is to make component libraries which people then go forth and use

The point of Tailwind, and Twind by extension, is that it's a CSS framework meant for aiding in quickly building out components. Co-locating styles and markup makes it very easy to rapidly make changes and understand the styles of your component without having to view it rendered. In addition, it places an upper limit on the size of your CSS bundles and hopefully kills off the dreaded "append-only stylesheet", as it's clear what classes are being used where and for what purposes.

Personally, I think it's actually a very poor choice to build a component library on top of -- you lose the main benefits (you're not going to be delving into `node_modules` (or equivalent) to read the components, so what does it matter if the component has readable styles?) and it comes with a rather large amount of CSS even with minimal use. I love Tailwind/Twind for writing components, but I not consuming. Of course, opinions will vary. 

Daisy UI, and others built on Tailwind, I think are best if you're looking for a component lib & a CSS framework, as an all-in-one sort of deal. If that's not what you're after, I think there are some better options out there for you., such as the aforementioned component libraries.

Just my thoughts though.

**Comment by Sleepful** [comment]
> It just doesn't really make much sense to use a CSS framework when your desired outcome is prebuilt components.

No, you are the one that doesn't understand how DaisyUI works. Let me put it this way: DaisyUI is a seamless integration into everything that you can do with TailwindCSS. It is fine if you don't want it, but don't make claims about how “sense” it makes for other people. Bottom line is: twind has limitations in its features in comparison with goold old `npx tailwindcss init`.

**Comment by Sleepful** [comment]
> (you're not going to be delving into node_modules (or equivalent) to read the components, so what does it matter if the component has readable styles?)

See? This is completely wrong. The way DaisyUI works is no different from https://tailwindcss.com/docs/typography-plugin which you seem to consider useful enough for your library.

A JavaScript component lib is **not** a good alternative to DaisyUI. If you are dismissing DaisyUI in favor of JavaScript component libraries, then you are equally dismissing TailwindUI components, which is a very bold statement to make.

**Comment by rschristian** [comment]
> No, you are the one that doesn't understand how DaisyUI works. Let me put it this way: DaisyUI is a true seamless integration into everything that you can do with TailwindCSS, it is a “configurable extension”

I'm well aware: 

>Daisy UI, and others built on Tailwind, I think are best if you're looking for a component lib & a CSS framework, as an all-in-one sort of deal. 

---

> It is fine if you don't want it, but don't make claims about how much “sense” it makes for other people.

Per the user, this seems to have been exactly what they were after.

> Bottom line is: `twind` has limitations in its features in comparison with good old `npx tailwindcss init`.

In the same way a React component cannot be consumed directly by Vue. They're different tools, with no compatibility layer. That's not a limitation really, but I digress.

I get that you're frustrated, but this isn't productive and isn't the language you should be using in an OSS repo.
