### ISSUE TITLE
twind and LitElement - Extended theme config not being applied

### ISSUE THREAD

**Issue by simon-bigsofa** [tw-in-js/twind#221]
I'm using twind with LitElement and following the setup here: https://twind.dev/usage-guides/lit-element.html

**twind** v0.16.16
**lit** v2.02

This has been working great but extending the theme using `setup()` is not creating and applying the extended styles.

There are also a couple of puzzling console warnings:

<img width="415" alt="Screenshot 2021-10-23 at 17 02 24" src="https://user-images.githubusercontent.com/24222511/138563450-19fb8fed-835e-4f83-9d87-6a917bb8c06b.png">

CodeSandbox here: https://codesandbox.io/s/twind-extend-config-issue-uuqkr?file=/src/DemoComponent.js

If you inspect `sheet.target` you can see that none of the extended styles have been created.

Extended theme styles _are_ correctly applied as expected when not using LitElement.

**Comment by sastan** [comment]
It seems this has been resolved. Closing it. Please re-open if that wasn't the case.
