### ISSUE TITLE
TypeScript issues

### ISSUE THREAD

**Issue by albingroen** [tw-in-js/twind#223]
I get this issue when I try to build my project that uses [twind](https://twind.dev) for styling.

```
Module '"../node_modules/twind/twind"' has no exported member 'tw'. Did you mean 'TW'
```

Twind version: `v0.16.16`

Here's how I import it:

```javascript
import { tw, setup } from "twind";
```

Am I doing something wrong or is something broken?

**Comment by rschristian** [comment]
What build tool are you using? Likely an issue there.

[That usage should work just fine](http://esm.codes/#Ly8gUXVpY2sgVHdpbmQgZGVtbwovLyAtLS0tLS0tLS0tLS0tLS0tCgppbXBvcnQgeyB0dyB9IGZyb20gJ2h0dHBzOi8vY2RuLnNreXBhY2suZGV2L3R3aW5kJwogIApkb2N1bWVudC5ib2R5LmlubmVySFRNTCA9IGAKICA8bWFpbiBjbGFzcz0iJHt0d2BoLXNjcmVlbiBiZy1wdXJwbGUtNDAwIGZsZXggaXRlbXMtY2VudGVyIGp1c3RpZnktY2VudGVyYH0iPgogICAgPGgxIGNsYXNzPSIke3R3YGZvbnQtYm9sZCB0ZXh0KGNlbnRlciA1eGwgd2hpdGUgc206Z3JheS04MDAgbWQ6cGluay03MDApYH0iPlRoaXMgaXMgVHdpbmQhPC9oMT4KICA8L21haW4+CmA7), and [twind definitely exports `tw` in their typings](https://www.runpkg.com/?twind@0.16.16/twind.d.ts#608)

**Comment by kaustubhkagrawal** [comment]
I am also facing the same issue, is this issue resolved? I am setting it up with tsdx. I want to create a component library for my project. 
I have installed it as npm package and default tsdx configurations.

**Comment by sastan** [comment]
@kaustubhkagrawal @albingroen 

Could you please provide an example repo or codesandbox to investigate this problem. Thank you.

**Comment by sastan** [comment]
Closing this for now. If you can please provide a reproduction and re-open this issue.
