### ISSUE TITLE
Is twind working with Angular?

### ISSUE THREAD

**Issue by ahmed-abdulmoniem** [tw-in-js/twind#224]
Hello

I checked the docs but I didn't find section for Angular.

Is it supported?

Thanks

**Comment by sastan** [comment]
It should just-work. Try to start with the [shim](https://twind.dev/handbook/the-shim.html) or use the [`tw` function](https://twind.dev/handbook/styling-with-twind.html). There is no SSR integration yet.

**Comment by sastan** [comment]
I will eventually add support for in twind v1. Until then you could try the [CDN example](https://github.com/tw-in-js/twind/tree/next/examples/twind-cdn).

Please give it a try. Here are some links to get you started:

- [The v1 branch](https://github.com/tw-in-js/twind/tree/next)
- [Reference](https://github.com/tw-in-js/twind/blob/next/documentation/40-reference/README.md) until the website is ready
- [Examples](https://github.com/tw-in-js/twind/tree/next/examples)

Closing this for now. Feel free to re-open.
