### ISSUE TITLE
TypeError on Cordova with ios

### ISSUE THREAD

**Issue by JanMP** [tw-in-js/twind#228]
Trying to use twind with Cordova on iOS (have not got to Android yet)I get this Error:

```TypeError: (0, import_url.pathToFileURL) is not a function. (In '(0, import_url.pathToFileURL)(__filename)', '(0, import_url.pathToFileURL)' is undefined) ```

at this position in modules.js:

```js
// node_modules/distilt/shim-node-cjs.js
var import_url = __toModule(require("url"));
var shim_import_meta_url = /* @__PURE__ */ (0, import_url.pathToFileURL)(__filename);
```

(rendering the web-view fails entirely)

**Comment by sastan** [comment]
I know nothing about Cordova. This function is available since [Node v10.12.0](https://nodejs.org/dist/latest-v16.x/docs/api/url.html#urlpathtofileurlpath). Which runtime is Cordova using?

**Comment by JanMP** [comment]
I am a little confused. My build system is running on Node 14.18.2, but what has Node got to do with the runtime? I am pretty sure Node is not running on iOS (or android)...

**Comment by sastan** [comment]
That is want I meant when I said _I know nothing about Cordova_. That file is should only be used within Node.JS environments. I guess during you build the wrong file is picked for bundling. But I can not know or help without any re-production or example repo.

**Comment by JanMP** [comment]
there you go: https://github.com/JanMP/twind-repo
