### ISSUE TITLE
Twind not working with Gatsby according to docs

### ISSUE THREAD

**Issue by LinnJS** [tw-in-js/twind#231]
Good afternoon Twind maintainers 👋 

I found Twind on twitter a couple weeks ago and since I found it I have been migrating away from twin.macro and to twind in favor of the more simplistic approach and bundle size.

I am currently re-writing my `gatsby-scalable-starter` template to use Twind and am removing all unnecessary packages.

I am looking at the [docs here](https://twind.dev/usage-guides/gatsby.html) that say how to use Twind with Gatsby and I am copying the docs line for line but am getting a build error when trying to start the project.

Error:
![image](https://user-images.githubusercontent.com/23741323/147414803-1ed2b910-c23d-4952-8dc4-14d473b43c21.png)

Repo/code:
https://github.com/LinnJS/gatsby-scalable-starter/pull/20

Any advice on how to resolve this error would be super helpful more than willing to update the documentation as well 😃

**Comment by LinnJS** [comment]
So I removed all instances of regular Tailwind classNames with `className={tw`tailwind-class`}` and dev server runs but when running build I get the error below which seems to be the same error just popping up in a different place.

![image](https://user-images.githubusercontent.com/23741323/147594522-4fba5f35-7fb9-453f-8d84-0a26e4a712d3.png)

**Comment by LinnJS** [comment]
Created a brand new Gatsby project to help debug and getting the same error just looks a little different

![image](https://user-images.githubusercontent.com/23741323/147614029-c26125cb-a59a-4144-81c2-10abf1b66918.png)

**Comment by LinnJS** [comment]
@sastam @gojutin would love any insights if you all have any. I see you two originally wrote these docs.

**Comment by rschristian** [comment]
You're using an outdated version of Node.

Prior to v14.18, the `node:` protocol was not supported with `require(...)`, see: [Node docs](https://nodejs.org/api/esm.html#node-imports)

**Comment by LinnJS** [comment]
@rschristian thanks for responding I have been struggling with this for a while now and really want to use Twind with Gatsby.

I have no idea `node:` was mot supported with `require(...)` good information!

Although after making the changes and running `gatsby clean && gatsby build` I get the same error:

![image](https://user-images.githubusercontent.com/23741323/147761614-d2d59777-3f3e-4355-9e6f-bb7e01ebac28.png)


code:
```
import { setup } from 'twind';
import { asyncVirtualSheet, getStyleTagProperties } from 'twind/server';
import { createElement } from 'react';
import './src/tailwind.css';

const sheet = asyncVirtualSheet();

setup({ sheet });

export const wrapPageElement = ({ element }) => {
  sheet.reset();

  return element;
};

export const onRenderBody = ({ setHeadComponents, pathname }) => {
  console.log('sheet: ', sheet);
  const { id, textContent } = getStyleTagProperties(sheet);
  console.log('twind props: ', { id, textContent });
  const twindId = `twind-ssr-${id}-${Math.random()}`;

  // eslint-disable-next-line no-unused-vars
  const styleProps = {
    id,
    dangerouslySetInnerHTML: {
      __html: textContent,
    },
  };
  setHeadComponents([
    createElement('style', {
      id: twindId,
      dangerouslySetInnerHTML: {
        __html: textContent,
      },
    }),
  ]);
};

```

**Comment by sastan** [comment]
It seems that webpack does not know about the `node:` prefix. Could you try [configuring webpack](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#onCreateWebpackConfig)

`gatsby-node.js`:

```js
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      alias: {
        "node:async_hooks": "async_hooks",
      }
    }
  });
};
```

source: https://www.mrozilla.cz/blog/gatsby-eslint-vscode-import-alias/

Or this plugin might work as well: https://www.gatsbyjs.com/plugins/gatsby-plugin-alias-imports/

**Comment by LinnJS** [comment]
@sastan thanks so much for taking the time to reply! It this solutions defiantly feels like the right direction. I tried implementing the code as you describe but the error is still persisting. Maybe the path needs to be a little bit different?

I am going to play with it and see if I can get something to build. Will let you know if I find something that works.

Feel free to check out the implementation in this [PR](https://github.com/LinnJS/gatsby-scalable-starter/pull/20/files#diff-9ba357440fe41b3b93d044cabfd228f9e085ed742925e96d59aa5fba3085d327R12)

**Comment by LinnJS** [comment]
Hey y'all still struggling with this Gatsby setup for twind. I have decided I am going to go back to using twin.macro and try to use twind patterns so when I figure this out I can go back to twind.

When I am done merging my PR I will open another PR to play with twind to see if I can resolve this later. Just need to build still and don't have time for config problem right now.

I am going to keep this this issue open, hope it gets resolved.

**Comment by sastan** [comment]
There is a working [gatsby-plugin-twind](https://www.npmjs.com/package/gatsby-plugin-twind) ([Example](https://github.com/tw-in-js/twind/tree/next/examples/gatsby)) for twind v1. 

Right now I do not have the time to update v0.16. If you need this for v0.16 please re-open and we will see what we can do,
