### ISSUE TITLE
Twind intellisense for Webstorm

### ISSUE THREAD

**Issue by sshquack** [tw-in-js/twind#232]
Thank you for this amazing library! It is awesome to see an official [Twind VSCode extension](https://github.com/tw-in-js/typescript-plugin) for code completion. I use [IntelliJ Webstorm](https://www.jetbrains.com/webstorm/) IDE for daily web development. Currently there is an official [Tailwind CSS plugin](https://plugins.jetbrains.com/plugin/15321-tailwind-css) available here. Please consider supporting IntelliSense for that platform.

**Comment by sastan** [comment]
I will not have the time to create a webstorm plugin. But maybe someone else will pick this up.

Closing it for now because there is nothing I could do for now.
