### ISSUE TITLE
Add support for container queries. 

### ISSUE THREAD

**Issue by smeijer** [tw-in-js/twind#237]
Now that we finally have a [proper polyfill](https://github.com/GoogleChromeLabs/container-query-polyfill) for container queries, I think it would be amazing if twind could offer a `container:` modifier to enable container queries as css until.

Loading the polyfill can be left upon the user, as this new polyfill is current-spec-compliant. 

Some background: https://css-tricks.com/a-new-container-query-polyfill-that-just-works/

**Comment by sastan** [comment]
This will most likely implemented as a preset like https://github.com/tailwindlabs/tailwindcss-container-queries
