### ISSUE TITLE
Can't use @apply within the project's native CSS code.

### ISSUE THREAD

**Issue by nimser** [tw-in-js/twind#238]
At present, the `apply` function is only useable within javascript.

It would be great to be able to use it as a css directive `@apply` so that we can get access and apply all Tailwind classes within any CSS file, `<style>` tag of an HTML file or Svelte component, etc...

Ideas for enabling this might be to do it with a vite or postcss plugin.

**Comment by rschristian** [comment]
I'm not sure I understand, you want to use a CSS-in-JS library to instead process CSS source content?

If you're concerned about perf/bundle size, [Twind supports static extraction](https://twind.dev/api/modules/twind_sheets.html#using-for-static-extraction-a-k-a-server-side-rendering-ssr), which is something I'm particularly fond of. 

It sounds to me that what you're asking for is already handled well by the existing ecosystem around Tailwind, and wouldn't really mesh well with other Twind tools AFAIK. That moves into processing of CSS content rather than generating styles from usage.

**Comment by nimser** [comment]
In my particular case, I'm making a Svelte component and want to have the ability to apply Tailwind classes to styles I've written in `<style>` tag of my component. Something like: 

*Component.svelte*
```svelte
<style>
    h1 {  @apply('text(center 2xl)') }
</style>
```

My understanding is that the Twind way of writing CSS rules for a component, while keeping access to `apply` would be to use the `css` Twind function as a replacement for `<style></style>`, and write the styles within the `<script>` tag of a component. I make this all sounds Svelte-specific, but this could be relevant for any HTML/JS project.

I understood from a conversation with @sastan that a separate Vite or Postcss plugin could allow using `apply` in CSS files (or HTML, Svelte files etc...), but I'm not entirely sure how that would work.

It may be something to explore outside Twind development though, so feel free to close this if this is not the right place to track this lack of a capability.

**Comment by danielweck** [comment]
You can use `apply` programmatically, as a function call:
https://twind.dev/handbook/overwriting-styles.html#the-apply-function-recommended

...so assuming your HTML template can result in a `style` element with a given predictable ID (i.e. authored / hard-coded `id` attribute guaranteed to not create ID collisions), then you can invoke `apply` on the `style` element `innerHTML`.

**Comment by danielweck** [comment]
Ah, scrap my comment above :)
I have just re-read your post more carefully and I don't think my suggested solution / workaround would work in practice, especially from a DX perspective (e.g. "intellisense" / code completion, etc.)

**Comment by sastan** [comment]
What I hope to achieve is integration with existing tooling (postcss, vite, webpack, ...) that would allow full static extraction without any config. Basically what you two (@danielweck  and @rschristian) are already doing.

In my opinion, twind should be able to process existing CSS with support `apply`, `theme`, and `screen`. 

```css
@twind {
  h1 {
    @apply text(center 2xl);
  }
}
```

For svelte:

```html
<style lang="twind">
h1 {
	@apply text(center 2xl);
}
</style>
```

**Comment by isakkeyten** [comment]
Additionally, there is no straightforward way to use shim in combination with apply without using apply function programatically.

Use case:
- Shim used in Remix in SSR mode meaning shim is scanning classnames and generating stylesheet.
- Stylesheet is cached and not regenerated on subsequent api calls.
- Not using `tw` function works twofold
  - Twind is not shipped to client and rehydrated for no reason
  - Better copy-pastability from tailwind code means faster development instead of having to prefix all classes with `tw`

Proposed syntax:
- `<h1 className="apply:(text-red-400 px-2 py-4)">Hello</h1>`
- Should also work with nested groups ex.  `<h1 className="apply:(text-red-400 px-2 py-4 md:(text-blue-400 px-4))">Hello</h1>`
- Generates a single `tw-hash` class and adds it to the virtual sheet

**Comment by sastan** [comment]
Something like that is implemented in v1.

- inline apply: styles are generated in order they are declared
  - `@(underline font-bold)` -> `@(underline,font-bold)`
  - `Link@(underline font-bold)` -> `Link#12345`
- inline shortcut: style are generated as defined by twind — same as if they where used alone
  - `~(underline font-bold)` -> `~(underline,font-bold)`
  - `Link~(underline font-bold)` -> `Link#abcdef`

from [Reference](https://github.com/tw-in-js/twind/blob/next/documentation/40-reference/README.md)

For your other suggestion — using twind within `<style>` — that is still on the table and a TODO for me.

**Comment by danielweck** [comment]
> For your other suggestion — using twind within `<style>` — that is still on the table and a TODO for me.

@sastan will no doubt introduce a clean "native" Twind API to handle the `<style>` use case, but in the meantime this can easily be achieved in userland with Twind v1 (Work In Progress "next" version https://github.com/tw-in-js/twind/tree/next )

```javascript
document.querySelectorAll('style[type~="twind/css"]').forEach((e) => {
    tw(css(e.textContent));
});
```

[Click this link to see a demo](https://esm.codes/#aW1wb3J0IHsgdHdpbmQsIGNzc29tLCBkb20sIHN0cmluZ2lmeSwgY3gsIGNzcyB9IGZyb20gJ2h0dHBzOi8vdW5wa2cuY29tL3R3aW5kQDEuMC4wLW5leHQuMjU/bW9kdWxlJzsKaW1wb3J0IHRhaWx3aW5kIGZyb20gJ2h0dHBzOi8vdW5wa2cuY29tL0B0d2luZC9wcmVzZXQtdGFpbHdpbmRAMS4wLjAtbmV4dC4yNT9tb2R1bGUnOwppbXBvcnQgZXh0IGZyb20gJ2h0dHBzOi8vdW5wa2cuY29tL0B0d2luZC9wcmVzZXQtZXh0QDEuMC4wLW5leHQuMjU/bW9kdWxlJzsKCmNvbnN0IHR3ID0gdHdpbmQoeyBwcmVmbGlnaHQ6IGZhbHNlLCBoYXNoOiBmYWxzZSwgcHJlc2V0czogW3RhaWx3aW5kKHsgZW5hYmxlUHJlZmxpZ2h0OiBmYWxzZSB9KSwgZXh0KCldfSwgY3Nzb20oKSk7CgpzZXRUaW1lb3V0KCgpID0+IHsKCmRvY3VtZW50LmJvZHkuc3R5bGUuZm9udFNpemUgPSAiMTEwJSI7Cgpjb25zdCBlbCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoInN0eWxlIik7CmVsLnNldEF0dHJpYnV0ZSgndHlwZScsICd0d2luZC9jc3MnKTsKZWwudGV4dENvbnRlbnQgPSBgQGxheWVyIGJhc2Ugewo6cm9vdCBib2R5IHsKQGFwcGx5IGJnLWJsYWNrOwpib3JkZXI6IDJweCBzb2xpZCByZWQ7CkBhcHBseSB0ZXh0LXdoaXRlOwp9Cjpyb290IGJvZHkgPiBwIHsKQGFwcGx5IHAtOCB0ZXh0LTN4bCBmb250LWJvbGQ7Cn0KOnJvb3QgYm9keSBoMSB7CnRleHQtZGVjb3JhdGlvbjogdW5kZXJsaW5lOwpAYXBwbHkgdXBwZXJjYXNlOwp9Cjpyb290IGJvZHkgcHJlIHsKQGFwcGx5IHNhbnM7Cn0KfWA7CmRvY3VtZW50LmhlYWQuYXBwZW5kKGVsKTsKZG9jdW1lbnQuYm9keS5pbm5lckhUTUwgPSBgPGgxPlN0eWxlIGVsZW1lbnQ6PC9oMT48cHJlIGlkPSJfMSI+IDwvcHJlPjxoMT5Ud2luZCBzdHlsZXNoZWV0OjwvaDE+PHRleHRhcmVhIGlkPSJfMiIgc3R5bGU9IndpZHRoOiAxMDAlOyBoZWlnaHQ6IDIwMHB4Ij4gPC90ZXh0YXJlYT48cD5IRUxMTyBUd2luZCEgOik8L3A+YDsKZG9jdW1lbnQucXVlcnlTZWxlY3RvckFsbCgnc3R5bGVbdHlwZX49InR3aW5kL2NzcyJdJykuZm9yRWFjaCgoZSkgPT4gewpkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgiXzEiKS50ZXh0Q29udGVudCArPSBlLnRleHRDb250ZW50Owp0dyhjc3MoZS50ZXh0Q29udGVudCkpOwpkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgiXzIiKS50ZXh0Q29udGVudCArPSBzdHJpbmdpZnkodHcudGFyZ2V0KTsKfSk7Cn0sIDUwMCk7Cg==).

Full `esm.codes` source:

```javascript
import { twind, cssom, dom, stringify, cx, css } from 'https://unpkg.com/twind@1.0.0-next.25?module';
import tailwind from 'https://unpkg.com/@twind/preset-tailwind@1.0.0-next.25?module';
import ext from 'https://unpkg.com/@twind/preset-ext@1.0.0-next.25?module';

const tw = twind({ preflight: false, hash: false, presets: [tailwind({ enablePreflight: false }), ext()]}, cssom());

setTimeout(() => {

document.body.style.fontSize = "110%";

const el = document.createElement("style");
el.setAttribute('type', 'twind/css');
el.textContent = `@layer base {
:root body {
@apply bg-black;
border: 2px solid red;
@apply text-white;
}
:root body > p {
@apply p-8 text-3xl font-bold;
}
:root body h1 {
text-decoration: underline;
@apply uppercase;
}
:root body pre {
@apply sans;
}
}`;
document.head.append(el);
document.body.innerHTML = `<h1>Style element:</h1><pre id="_1"> </pre><h1>Twind stylesheet:</h1><textarea id="_2" style="width: 100%; height: 200px"> </textarea><p>HELLO Twind! :)</p>`;
document.querySelectorAll('style[type~="twind/css"]').forEach((e) => {
document.getElementById("_1").textContent += e.textContent;
tw(css(e.textContent));
document.getElementById("_2").textContent += stringify(tw.target);
});
}, 500);

```

**Comment by sastan** [comment]
That is an amazing idea!

**Comment by danielweck** [comment]
I ported the quick demo to https://jspm.org which works better than https://esm.codes for repros that involve markup:

[Click here to open the demo](https://jspm.org/sandbox#H4sIAAAAAAAAA41UbWvbMBD+nl9xDYzYLHZeRqEktpdtFDYobNB9K2Uo1iUWlS1PUpp4JfvtO0lJ+jLK9iWOTnfP8+jukbIzrkrbtQiVrWXRy44fZLzoAWQ1WgZlxbRBm/c3dpVc9P2GFVZi8X0rGg5alXcmG4XQqaphNeb9e4HbVmnbh1I1FhtC2Qpuq5zjvSgx8YshiEZYwWRiSiYxnwQOY7sAuFS8gwf6QyBS6Rlo5HO3XLLybq3VpuHJYWdbCYt+b0V8iRG/cAaT6fiNj7WMc9GsKZKeY+1Ce0c0OjEFTnAtyfvWnW5UGuPlLCTrUBOlQdIy00rZo7AFa1vZwXKdLCUpmveWSnMkNdN2B0ZJwYPiQ57FnU0OQvdPkQpoH9Ha5CJkvtvJcJilkvxFRTWhAp/FsVSaWaGaGVA/UEvR4Ily07aoS5L+or7V+MhoWGPc/rOeZKNghszl+xZVk+Ladwkl1jTRGaVMisxBCZ73f9D0qJyWhUsNFvFgpkI8ZjvNTCMLJdN+yDiYg+YzpolBhWJdWWrjeNzuPOqxjOiKz5dXV1/B45/BLCbKotfLTKlFaw8TrBXfSKTxidqZEB7Az3QINFRVD4G7H2M1eUKsOgrv/BbsYaVVDYPK2tbMRqNN096t01LVI1+/mKTjdJw0JCadnr8PLIP5kcUyIf2pXwNZBGdRi+haJcf0f6BS+D8BKfM1rB7dQkMKt5CHVkQPzgMrGRq9YtLgECpmqtMigJoZ3ByFUg02bCnx24tK2MdDpzOKb/eHHkdxTKz0ymycVdKfG9TdNRmntEp/kDIa+LnfuHH9fnrjbgdxulL6kpVVFGEMeUE+PcGs0V4G833svvDIeS5OnTc+hUcG3uaATwPznt1GhBs9izptr2NO/8Y8WSWy25SMSDUEsXdH9FfGe8/dmXBZyOr+Pf0Dsu8zCGcFAAA=)
