### ISSUE TITLE
Arbitrary values not working with space delimited multi argument css values.

### ISSUE THREAD

**Issue by isakkeyten** [tw-in-js/twind#255]
Ex. Flex https://developer.mozilla.org/en-US/docs/Web/CSS/flex

when
`flex-[0 0 auto]` 
expected
`flex: 0 0 auto;`
got...well nothing :) 
in case of 
`flex-[0_0_auto]` <- which is how tailwind handles this
i get a generated
`flex: 0_0_auto;`
which is not valid css...

To reproduce, just use above className
small repro on stackblitz [here](https://stackblitz.com/edit/react-gaz12h)

**Comment by danielweck** [comment]
With `twind` version `1.0.0-next.24`:

`flex-[0_0_auto]` => `.flex-\[0_0_auto\] { flex: 0 0 auto; }`

[Click on this link to open the esm.codes repro](https://esm.codes/#aW1wb3J0IHsgdHdpbmQsIGNzc29tLCBkb20sIHN0cmluZ2lmeSB9IGZyb20gJ2h0dHBzOi8vdW5wa2cuY29tL3R3aW5kQDEuMC4wLW5leHQuMjQ/bW9kdWxlJzsKaW1wb3J0IHRhaWx3aW5kIGZyb20gJ2h0dHBzOi8vdW5wa2cuY29tL0B0d2luZC9wcmVzZXQtdGFpbHdpbmRAMS4wLjAtbmV4dC4yND9tb2R1bGUnOwoKY29uc3QgdHcgPSB0d2luZCh7IHByZWZsaWdodDogZmFsc2UsIGhhc2g6IGZhbHNlLCBwcmVzZXRzOiBbdGFpbHdpbmQoKV19LCBjc3NvbSgpKTsKCmNvbnN0IGNscyA9IHR3KCdmbGV4LVswXzBfYXV0b10nKTsKCnNldFRpbWVvdXQoKCkgPT4gewpjb25zdCBtc2c9IGAke2Nsc31cblxuJHtzdHJpbmdpZnkodHcudGFyZ2V0KX1cbmA7Cgpkb2N1bWVudC5ib2R5LnN0eWxlLmJhY2tncm91bmQgPSAid2hpdGUiOwpkb2N1bWVudC5ib2R5LnN0eWxlLmNvbG9yID0gImJsYWNrIjsKZG9jdW1lbnQuYm9keS5zdHlsZS5mb250U2l6ZSA9ICIyMDAlIjsKZG9jdW1lbnQuYm9keS5pbm5lckhUTUwgPSBtc2cucmVwbGFjZSgvXG4vZywgIjxicj4iKTsKfSwgNTAwKTsK)

Source:

```javascript
import { twind, cssom, dom, stringify } from 'https://unpkg.com/twind@1.0.0-next.24?module';
import tailwind from 'https://unpkg.com/@twind/preset-tailwind@1.0.0-next.24?module';

const tw = twind({ preflight: false, hash: false, presets: [tailwind()]}, cssom());

const cls = tw('flex-[0_0_auto]');

setTimeout(() => {
const msg= `${cls}\n\n${stringify(tw.target)}\n`;

document.body.style.background = "white";
document.body.style.color = "black";
document.body.style.fontSize = "200%";
document.body.innerHTML = msg.replace(/\n/g, "<br>");
}, 500);
```

**Comment by isakkeyten** [comment]
Ah ok well, I'm still on 0.16.16. 
I'm seeing now that the new next version doesn't ship with tailwind support oob.
And if I'm reading this correctly, it's using @antfu's unocss engine?
Is there any performance comparison between 0.16.16 and 1.0.0-next somewhere?
And is there anyway I can contribute?

**Comment by sastan** [comment]
> Ah ok well, I'm still on 0.16.16.
> I'm seeing now that the new next version doesn't ship with tailwind support oob.

You can use [@twind/tailwind](https://github.com/tw-in-js/twind/tree/next/packages/tailwind#readme). Full Tailwind v3.

> And if I'm reading this correctly, it's using @antfu's unocss engine?

No its not. I played around with a similar config format. The end result looks like it but has other features as well.

> Is there any performance comparison between 0.16.16 and 1.0.0-next somewhere?

Not yet.

> And is there anyway I can contribute?

Thanks. If you could try v1 and report your findings would be great. 

Closing this for now. But feel free to re-open.
