### ISSUE TITLE
Shim not working with pseudo classes and content.

### ISSUE THREAD

**Issue by isakkeyten** [tw-in-js/twind#256]
In the docs there is only example of using pseudo classes like `after` in combination with `{ content }` utility.
In the case of using shim, one would assume the syntax would be similar.

Ex.
`<p class="after::content-['*']">I should have an ::after with a * bellow me</div>`
^ except this doesn't work

Is there a different syntax for using pseudo classes and content with shim or is it straight up unsupported?

Small repro can be found [here](https://stackblitz.com/edit/react-4vgpwj?file=src%2FApp.js)

**Comment by danielweck** [comment]
With `twind` version `1.0.0-next.24`:

`after:content['zzz']` => `.after\:content\[\'zzz\'\]:after{content:'zzz'}`

Note the absence of `-` dash character after `content` and before the opening `[` square bracket ... this look like a bug, yet the unit tests currently pass:

https://github.com/tw-in-js/twind/blob/1ed704ae782582e2751f97fec57f92ca536d6faa/packages/preset-tailwind/src/rules.test.json#L1465

@sastan any idea?

[Click on this link to open the esm.codes repro](https://esm.codes/#aW1wb3J0IHsgdHdpbmQsIGNzc29tLCBkb20sIHN0cmluZ2lmeSB9IGZyb20gJ2h0dHBzOi8vdW5wa2cuY29tL3R3aW5kQDEuMC4wLW5leHQuMjQ/bW9kdWxlJzsKaW1wb3J0IHRhaWx3aW5kIGZyb20gJ2h0dHBzOi8vdW5wa2cuY29tL0B0d2luZC9wcmVzZXQtdGFpbHdpbmRAMS4wLjAtbmV4dC4yND9tb2R1bGUnOwppbXBvcnQgZXh0IGZyb20gJ2h0dHBzOi8vdW5wa2cuY29tL0B0d2luZC9wcmVzZXQtZXh0QDEuMC4wLW5leHQuMjQ/bW9kdWxlJzsKCmNvbnN0IHR3ID0gdHdpbmQoeyBwcmVmbGlnaHQ6IGZhbHNlLCBoYXNoOiBmYWxzZSwgcHJlc2V0czogW2V4dCgpLCB0YWlsd2luZCgpXX0sIGRvbSgpKTsKCmNvbnN0IGNscyA9IHR3KCJhZnRlcjpjb250ZW50Wyd6enonXSIpOwoKc2V0VGltZW91dCgoKSA9PiB7CmNvbnN0IG1zZz0gYCR7Y2xzfVxuXG4ke3N0cmluZ2lmeSh0dy50YXJnZXQpfVxuYDsKCmRvY3VtZW50LmJvZHkuc3R5bGUuYmFja2dyb3VuZCA9ICJ3aGl0ZSI7CmRvY3VtZW50LmJvZHkuc3R5bGUuY29sb3IgPSAiYmxhY2siOwpkb2N1bWVudC5ib2R5LnN0eWxlLmZvbnRTaXplID0gIjIwMCUiOwpjb25zdCBlbCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoInAiKTsKZWwuaW5uZXJIVE1MID0gbXNnLnJlcGxhY2UoL1xuL2csICI8YnI+Iik7CmVsLmNsYXNzTGlzdC5hZGQoY2xzKTsKZG9jdW1lbnQuYm9keS5hcHBlbmQoZWwpOwp9LCA1MDApOwo=)

Source:

```javascript
import { twind, cssom, dom, stringify } from 'https://unpkg.com/twind@1.0.0-next.24?module';
import tailwind from 'https://unpkg.com/@twind/preset-tailwind@1.0.0-next.24?module';
import ext from 'https://unpkg.com/@twind/preset-ext@1.0.0-next.24?module';

const tw = twind({ preflight: false, hash: false, presets: [ext(), tailwind()]}, dom());

const cls = tw("after:content['zzz']");

setTimeout(() => {
const msg= `${cls}\n\n${stringify(tw.target)}\n`;

document.body.style.background = "white";
document.body.style.color = "black";
document.body.style.fontSize = "200%";
const el = document.createElement("p");
el.innerHTML = msg.replace(/\n/g, "<br>");
el.classList.add(cls);
document.body.append(el);
}, 500);

```

**Comment by danielweck** [comment]
UPDATE:

Ah, I removed the `ext()` `preset` before the `tailwind()` one, and everything works as expected! :)
(placing the `ext()` `preset` after the `tailwind()` one works too)

`after:content-['zzz']` => `.after\:content-\[\'zzz\'\]:after{--tw-content:'zzz';content:var(--tw-content)}`

👍

**Comment by sastan** [comment]
The preset-ext includes a _Short CSS_ rule. It will catch **all** arbitrary values. It should always be after preset-tailwind.

https://github.com/tw-in-js/twind/tree/next/packages/preset-ext#short-css

**Comment by danielweck** [comment]
Hey, the `preset` order between `ext` and `tailwind` affected my own codebase, unbeknownst to me! Well, now I know :)

**Comment by sastan** [comment]
I will close this issue for now as I currently do plan to work on v0.16. Please re-open if you need that fixed and I  will see what I can do.

**Comment by isakkeyten** [comment]
Ok thanks for the feedback. Closing this.

**Comment by danielweck** [comment]
In my humble opinion, we (as a user community) should resist the temptation to ask @sastan to fix bugs / maintain Twind `0.x`, which by definition is alpha software.

Let's focus on v1 which has been under heavy development in the last few weeks and is now starting to look great! 😃 
https://github.com/tw-in-js/twind/tree/next

**Comment by isakkeyten** [comment]
Makes sense :) Was not aware how far progress on 1.0.

**Comment by danielweck** [comment]
> The preset-ext includes a _Short CSS_ rule. It will catch **all** arbitrary values. It should always be after preset-tailwind.

PSA - this has changed since this commit: https://github.com/tw-in-js/twind/commit/5c1934d9b2977000c755273b8a1723d9b670bfcf
