### ISSUE TITLE
defineConfig does not seem to support theme functions

### ISSUE THREAD

**Issue by marbemac** [tw-in-js/twind#257]
From the `next` branch docs - is the below expected to work already? When added to a `defineConfig()` (from `@twind/tailwind`), ends up throwing a bunch of errors.

<img width="571" alt="Screen Shot 2022-01-25 at 3 32 32 PM" src="https://user-images.githubusercontent.com/847542/151054970-d9a5b881-012a-40f3-9886-7a1020d78fab.png">

**Comment by sastan** [comment]
Thank you for reporting this issue. Typing the theme property is really challenging. After some investigation I got it working like this:

```ts
      theme: {
        simple: {
          a: '1',
        },
        // must use type for section resolvers
        // referencing other theme section
        custom: ({
          theme,
        }: ThemeSectionResolverContext<TailwindTheme>): TailwindTheme['colors'] => ({
          gray: theme('colors.gray'),
        }),
        // overwrite existing section
        fill: ({ theme }: ThemeSectionResolverContext<TailwindTheme>): TailwindTheme['colors'] => ({
          gray: theme('colors.gray'),
        }),
        extend: {
          // types are infered in extend
          // extending existing section
          divideColor: ({ theme }) => ({
            gray: theme('colors.gray'),
          }),
        },
      },
```

I will publish a version with this fix soon. 

If you have any idea how we can omit the types outside `extend` please let me know.

**Comment by marbemac** [comment]
No worries - good ol' `ts-expect-error` to the rescue for now, thanks for the quick response.

> Typing the theme property is really challenging

Oh I believe it! Semi related to https://github.com/tw-in-js/twind/issues/201#issuecomment-1021746623, if I can find the time I'm hoping to dig into how Stitches has put together their typings - they're achieved some voodoo magic over there, surprised re how well they managed to integrate custom themes with typings/autocomplete out of the box.

**Comment by sastan** [comment]
It is little different here in twind. We have to combine themes from the presets with the user provided one. 

If you find a good solution PRs are very welcome.

**Comment by marbemac** [comment]
On `next.26`, seeing the following issues:

**Theme prop not available on the theme function**

It's typed as https://github.com/tw-in-js/twind/blob/next/packages/twind/src/types.ts#L372-L377 (but the code below does actually work at runtime - just a typings issue).

<img width="1329" alt="Screen Shot 2022-01-27 at 5 07 56 PM" src="https://user-images.githubusercontent.com/847542/151451803-045eac99-769f-4e85-bbf5-16f6f696f2f1.png">

**This one has me scratching my head**

If I copy this same config into the `twind` repo `packages/tailwind/src` and import defineConfig from `index.ts`, I don't get the error (just get the error above). So might just be something w my setup, I'll try to dig in further.

<img width="1048" alt="Screen Shot 2022-01-27 at 5 12 55 PM" src="https://user-images.githubusercontent.com/847542/151452371-d72760af-d5a1-417e-8015-b737cf88219a.png">
