### ISSUE TITLE
@next version: Running twind inside nextJS fails due to undefined window.twind

### ISSUE THREAD

**Issue by IgnusG** [tw-in-js/twind#266]
I get the error: `TypeError: Cannot set properties of undefined (setting 'setup')` after running:

```tsx
import type { NextPage } from 'next';

import { setup } from "@twind/tailwind";

const tw = setup({});

const Home: NextPage = () => {
  return (
    <div className={tw("text-lime-400")}>
      Testing
    </div>
  )
}

export default Home
```

It seems that twind on line https://github.com/tw-in-js/twind/blob/7591eef03cf3e2ef6f5eff0e8c4607faba6794ad/packages/tailwind/src/index.ts#L76-L80 checks whether it's run directly which in this case using `yarn dev` from a blank nextJS template seems to evaluate to true:

![image](https://user-images.githubusercontent.com/6438760/151677376-8325041e-b36f-4de4-9009-337b4927c831.png)

![image](https://user-images.githubusercontent.com/6438760/151677232-97e8d075-bada-4d9d-9511-7035c2fc36b9.png)

In this case however window.twind is not defined so setting it's properties fails. Removing these lines from the file fixes the problem but I assume they are meant for when using twind in shim mode.

**Comment by IgnusG** [comment]
I've ran replaced the line with the following patch which seems to fix the error:

```diff
diff --git a/node_modules/@twind/tailwind/tailwind.js b/node_modules/@twind/tailwind/tailwind.js
index 4631440..e9c9d42 100644
--- a/node_modules/@twind/tailwind/tailwind.js
+++ b/node_modules/@twind/tailwind/tailwind.js
@@ -22,7 +22,7 @@ function setup(config, sheet, target) {
     return setup$1(defineConfig(config), sheet, target);
 }
 // If we run in the browser as `<script src="..."></script>` patch twind to use our setup and defineConfig
-if (typeof document != 'undefined' && document.currentScript) {
+if (typeof document != 'undefined' && document.currentScript && self.twind) {
     self.twind.setup = setup;
     self.twind.defineConfig = defineConfig;
 }
```

**Comment by sastan** [comment]
The current code has this check already. Could you please verify this issue exists with 1.0.0-next.28.
