### ISSUE TITLE
@next version: Using apply can incorrectly add named classes through the proxy get hook

### ISSUE THREAD

**Issue by IgnusG** [tw-in-js/twind#268]
Using eg. `apply.apply(...)` will incorrectly add `apply` as the name of a applied class since it will get caught in the `get` hook of the `nested` proxy:

https://github.com/tw-in-js/twind/blob/7591eef03cf3e2ef6f5eff0e8c4607faba6794ad/packages/twind/src/nested.ts#L15-L21

The hook should check if the requested property is not a native one for example like this:

```ts
      get(target, name) {
        // Native accessors (apply, get, bind...) should be skipped
        if (name in nested$) return Reflect.get(nested$, name);

        return function namedNested(
          strings: TemplateStringsArray | Class,
          ...interpolations: Class[]
        ): string {
          return nested$(name as string, strings, interpolations)
        }
```

This bug can cause mismatched SSR/Client class names since it "generates" slightly different class names.

**Comment by sastan** [comment]
Fixed in the upcoming release. Thanks @IgnusG
