### ISSUE TITLE
tailwind-preset `cjs` build issue

### ISSUE THREAD

**Issue by marbemac** [tw-in-js/twind#273]
I noticed that the `.cjs` build output is missing the `dividend` default value on the `ratios` function. This causes the ratios to not get outputted (thus affecting the resolved default config) in a cjs environment.

`let dividend = 1` IS in the source: https://github.com/tw-in-js/twind/blob/next/packages/preset-tailwind/src/defaultTheme.ts#L831

Versus the compiled `cjs` in the distributed npm package:

<img width="1493" alt="Screen Shot 2022-01-31 at 3 06 06 PM" src="https://user-images.githubusercontent.com/847542/151864880-e9691829-ded1-49bc-b22d-054495e287d3.png">

I'm currently on `@twind/preset-tailwind@1.0.0-next.30`, but I don't think this is specific to `30`.

Just in case it's relevant - ran into this while trying to use https://github.com/muhammadsammy/tailwindcss-classnames. Noticed that the `x/y` ratio classes were not present in the generated typings, and tracked it down to this missing default val on the ratios func.

**Comment by danielweck** [comment]
ah! indeed ... https://unpkg.com/@twind/preset-tailwind@1.0.0-next.30/defaultTheme.cjs

**Comment by danielweck** [comment]
... and note that the mjs file simply references the cjs: https://unpkg.com/browse/@twind/preset-tailwind@1.0.0-next.30/defaultTheme.mjs

**Comment by sastan** [comment]
Great catch! If I change it to `var` it works. All other for-loops seem to be ok.

**Comment by sastan** [comment]
Rollup looks good too.

**Comment by sastan** [comment]
> ... and note that the mjs file simply references the cjs: [unpkg.com/browse/@twind/preset-tailwind@1.0.0-next.30/defaultTheme.mjs](https://unpkg.com/browse/@twind/preset-tailwind@1.0.0-next.30/defaultTheme.mjs)

That is because of shared state. A node app could import and require twind which would lead to two states.

**Comment by sastan** [comment]
made a mistake by adding a comment but not fixing the bug. will be fixed in 1.0.0-next.32
