### ISSUE TITLE
@next version: Running twind during SSR causes certain rules to not be included

### ISSUE THREAD

**Issue by IgnusG** [tw-in-js/twind#279]
I've ran into a problem where the server run twind (CJS) does not appear to find classes: `-translate-x-2/4`, `-translate-y-2/4` or `top-1/2`, `left-1/2`. The client bundle however does find these and generates the proper CSS.

This causes twind to return an incorrect class during SSR (preserving the "unknown" classes): 
```
Prop `className` did not match. Server: "top-1/2 left-1/2 -translate-y-2/4 -translate-x-2/4 css#rhaud9" Client: "css#rhaud9"
```

I've been trying to dig into the source code but so far I've not had luck.

**Comment by sastan** [comment]
That was fixed in one of the last version.

**Comment by sastan** [comment]
https://github.com/tw-in-js/twind/issues/273

**Comment by sastan** [comment]
Thank you for trying v1. Your feedback really helps making twind bulletproof.
