### ISSUE TITLE
@next version: the suggested upgrade code when migrating from @twind/tailwind for setup is incorrect

### ISSUE THREAD

**Issue by IgnusG** [tw-in-js/twind#283]
The latest version .35 deprecated @twind/tailwind but the mentioned [upgrade path for `setup`](https://github.com/tw-in-js/twind/releases/tag/1.0.0-next.35) does not pass type checking (presets invalid on `TwindConfig`) and also does not appear to actually add the presets.

Combining `setup` with `defineConfig` seems to work however:
```tsx
import { setup, defineConfig } from 'twind'
import presetAutoprefix from '@twind/preset-autoprefix'
import presetTailwind from '@twind/preset-tailwind'

// setup + defineConfig work together
export default setup(defineConfig({
  presets: [presetAutoprefix(), presetTailwind()],
  /* config */
}))
```

**Comment by sastan** [comment]
Thank you! I will check the typing there.

**Comment by sastan** [comment]
This is not forgotten. I just do not have to time ATM
