### ISSUE TITLE
twind (next) SSR versions not parsing pseudo selectors

### ISSUE THREAD

**Issue by zslabs** [tw-in-js/twind#289]
Hey there! I was doing some testing in both SSR (Remix) and client-side locally and noticed pseudo selectors like `::before` are not being parsed correctly:

### Remix example

https://codesandbox.io/s/cool-dawn-r8gm4?file=/app/routes/index.tsx

In `app/routes/index.tsx` I've added `before:content-['test']` but it's not showing up next to the title

### Client side example

https://codesandbox.io/s/ancient-thunder-uidxu

In `index.html` I've added `before:content-['test']` and it shows up correctly next to the title.

---

Is this potentially something to do with the `inline` function? The VS Code extension (which I think I remember reading elsewhere that it needs to be updated) is parsing this as:

```
before:content-['*']
.before\:content-\[\'\*\'\]:before{align-content:['*']}
```

So this may be unrelated, but wanted to mention that as well. Are there any examples of using SSR with the "library" mode; as I'm curious if the `inline` function would be used in that case. Thanks as always!

**Comment by sastan** [comment]
Thanks for the bug report. I can confirm that there is something broken. When using SSR the following style is added to the document:

```css
.before\:content-\[\&\#x27\;test\&\#x27\;\]:before{--tw-content:&#x27;test&#x27;;content:var(--tw-content)}
```

when run on the client:

```css
.before\:content-\[\'test\'\]:before{--tw-content:'test';content:var(--tw-content)}
```

Someone is escaping `'` and that messes it up. I'll look into it.

---

For _Library Mode_ SSR: `inline` and `extract` are expecting all styles to be in the html and are clearing the `tw` instance before parsing the HTML. After the clearing all styles added by a `tw` call are gone. We do this to only include the used classes. You could replace `inline` with the following code:

```js
import { extract } from 'twind'

function render() {
  const { html, css } = extract(renderApp())

  // inject as last element into the head
  return html.replace('</head>', `<style data-twind>${css}</style></head>`)
}
```

**Comment by sastan** [comment]
It seems like react is already escaping the class name in the class attribute. That escaped class is then used by twind.

**Comment by zslabs** [comment]
Thanks for confirming and the extract example!

**Comment by sastan** [comment]
Fixed in v1.0.0-next.37

**Comment by danielweck** [comment]
For what it's worth, I tested this edge case in my Preact app using JSX `class="before:content-['*']"` as well as `class={"before:content-['*']"}`, no problems:
```
.before\:content-\[\'*\'\]:before{--tw-content:"*";content:var(--tw-content)}
```

Mind you, this is with Preact WMR so the JSX is compiled to `htm`, then executed at pre-rendering time (SSG) through Preact's `options.vnode()` interceptor ... so quite a different dataflow to Remix SSR.

**Comment by zslabs** [comment]
Thanks @sastan that fix worked great!

For the library mode example; I was able to get things working - but noticed that normal `className` props were still being processed - which I'd like to avoid and only use `tx` or `tw` to parse/extract things. I can always create a new issue since that's getting a bit out of scope of the original issue. 

Thanks again!

**Comment by sastan** [comment]
If you don't want to process class names than do not call consume. Only use stringify.
