### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by kaustubhkagrawal** [tw-in-js/twind#292]
Can we use twind with react native. Also if it doesn't support react native right now because I guess that might not be the main focus, can you suggest any workaround or any other package we can use along side twind to make it work in react native.

**Comment by mnik01** [comment]
+1 
Interesting for me

**Comment by sastan** [comment]
I have never used react native and wouldn't know where to start. This may take some time.

**Comment by vicary** [comment]
@sastan I don't think I can make a PR, but I'll chip in what I know hopefully it helps with coming up with an idea.

React Native has no concept of classes, neither `class` nor `className` is available by default.

Taking reference from [Nativewind](https://github.com/marklawlor/nativewind) you may get an idea on how to force a `className` prop for most of the built-in components. Layout frameworks, e.g. React Native Elements or React Native Paper, is another rabbit hole that we shouldn't get into just yet.

It's about making a babel plugin that transforms class names into inline styles, or React Native Stylesheets. Nativewind uses Tailwind CLI, replacing that part of the babel plugin with Twind should in theory do the job.

**Comment by sastan** [comment]
Thank you. That is a good start. I'll take a look.

**Comment by chrisarts** [comment]
Im doing some work on this and I hope to have a preview for tailwind in react native using twind, but the library mode its a bit confusing and the documentation is missing, if you have some time to talk and share we can sit together.
