### ISSUE TITLE
SSR: `bg-slate-400` does not work whereas `bg-purple-400`  does

### ISSUE THREAD

**Issue by activenode** [tw-in-js/twind#295]
Weirdly there is a lot of colors that simply don't work.

Here is the full example that will lead to the problems of saying "UNKNOWN_DIRECTIVE":

```
const sheet = virtualSheet();

const { tw } = create({ sheet });
const classes = tw`text(uppercase amber-300) bg-purple-400`;

const styleTag = getStyleTag(sheet);
```

![image](https://user-images.githubusercontent.com/9058762/155677124-c45ddb62-8924-45a1-b0ca-2ccbb3276310.png)

**Comment by sastan** [comment]
Thanks for the report. Twind v0.16 only supports tailwind v2 and does not include v2 colors like `amber` or `slate` in the default theme (https://github.com/tw-in-js/twind/blob/main/src/twind/theme.ts#L101-L222).

The extended color palette is available via the `twind/colors` module. You can use that and add the additional colors in the theme config (https://twind.dev/handbook/configuration.html#colors).

I hope that helps. Please re-open this issue if you find that this didn't answer your question.

**Comment by activenode** [comment]
Thanks for clarifying.
