### ISSUE TITLE
Update Twind site Discord invitation

### ISSUE THREAD

**Issue by alshdotme** [tw-in-js/twind#301]
Seems the Discord link on the main docs site is invalid so I'm unable to join the Discord community. Maybe the invite has expired?

**Comment by IgnusG** [comment]
Hmm seems like the case. Although I did have trouble with it on the phone and then afterwards it worked on the pc. 

Try the "evergreen" one from the Readme https://chat.twind.style/

**Comment by alshdotme** [comment]
That worked. Thank you very much!

**Comment by sastan** [comment]
I've updated the links. Thanks for reporting!
