### ISSUE TITLE
Error with text colours when retrieved via theme helper

### ISSUE THREAD

**Issue by alshdotme** [tw-in-js/twind#305]
I'm using Twind v0.16.16

Say I have the following setup in my theme:

```
   colors: {
      ...
      brand: {
        darker: 'rgba(7, 87, 0, 1)',
        DEFAULT: 'rgba(11, 138, 0, 1)',
        'tint-25': 'rgba(194, 226, 191, 1)',
      },
     ...
    },
```

and I reference this colour palette for my text colors using the Theme helper:

```
    textColor: theme => ({
      ...
      brand: {
        darker: theme('colors.brand.darker'),
        DEFAULT: theme('colors.brand'),
      },
      ...
    }),
```

Now when trying to apply the class `text-brand-darker` I get the error `Unknown theme value "textColor[brand-darker]"`. 

If I use `bg-brand-darker` this works as expected.

[Here's a sandbox replicating the problem.](https://codesandbox.io/s/nice-worker-gvfbn3)

**Comment by sastan** [comment]
Thanks you the report and the reproduction. I'll take a look.
