### ISSUE TITLE
In Next.js with Apply function, if internal doped with TwindConfig content, it will error

### ISSUE THREAD

**Issue by xlboy** [tw-in-js/twind#309]
code and dependencies: ↓
![203801650430134_ pic](https://user-images.githubusercontent.com/63690944/164152623-521600bc-5228-4ce3-93f3-63ef502bdf21.jpg)

runtime: ↓
![203831650430426_ pic](https://user-images.githubusercontent.com/63690944/164153121-feff41e5-90f0-4687-8273-ac22e84bcb12.jpg)

**Comment by sastan** [comment]
Could you create a codesandbox for reproduction? I'm currently not using react in any project.

**Comment by xlboy** [comment]
> 

ok, The specific code example is in this link. ↓
`https://codesandbox.io/s/ecstatic-diffie-wpokwd?file=/src/pages/index.tsx`

![111651650725305_ pic](https://user-images.githubusercontent.com/63690944/164911052-7c77465f-ad0d-43c8-b782-42edb4835f79.jpg)

**Comment by xlboy** [comment]
Oh, Sorry.

This seems to be the reason why I didn't configure `_document.tsx`

I'll try again later. Thanks for your help. 

Besides, I like this warehouse very much!

**Comment by sastan** [comment]
Thank you. Please report any issues you find.
