### ISSUE TITLE
@next cors error

### ISSUE THREAD

**Issue by mybigman** [tw-in-js/twind#315]
`https://github.com/tw-in-js/twind/tree/next/examples/using-twind-cdn` 

`https://codesandbox.io/s/github/tw-in-js/twind/tree/next/examples/using-twind-cdn` doesn't appear to work CORs error :/

Am I missing something?

**Comment by sastan** [comment]
No you do not. Thanks for the report. I fixed the example to use `https://cdn.jsdelivr.net/npm/@twind/cdn@next` directly.

It seems that a redirect from  `cdn.twind.style` to `cdn.jsdelivr.net` is not allowed. I will see if I can fixed that later.
