### ISSUE TITLE
Serious problem with documentation

### ISSUE THREAD

**Issue by wildfiremedia** [tw-in-js/twind#316]
I still don't understand how to get even the basic hello world set up with Twind could find myself give up this project.

What is the next step I'm suppose to run after:
```
npm i twind
```
and documentations guide is confusing despite with years of programming experience in other area.

**Comment by sastan** [comment]
Very sorry for that. 

What framework are you using? What do you want to achieve? Which twind version are you using?

**Comment by wildfiremedia** [comment]
In my set up, I'm using Alpine.js, HTML and Tailwind 3 (npx) with no framework.

Managed to get it working with Vite which use index.js with the exception that migration from Tailwind to Twind is a big effort. Plan to reuse Tailwind 3 classess and it's strange `text-orange-500` is not appear in orange but other colours are fine. Is Tailwind classes fully compatible with Twind?

**Comment by sastan** [comment]
Tailwind v3 is only supported in the twind v1 beta (https://github.com/tw-in-js/twind/tree/next).

**Comment by bstro** [comment]
Related to this issue, I'm having a lot of trouble figuring out how to get the `next` branch running in my Vite/React 18 app. 

I'm running
```
setup({
  presets: [presetTailwind()],
  /* config */
});
```
in my project root, and trying to use (for example) `tw.theme('colors.blue.500')` from one of my components, but get the error: `Uncaught TypeError: tw.theme is not a function`

Any thoughts?

**Comment by bstro** [comment]
I think my hunch was accurate. I was attempting to use the theme from a `constants.ts` file at the module's top-level. As soon as I turned the constants into a factory function (rather than just directly exporting values from the top-level), everything started working. Have a clearer idea of how twind works now too.

**Comment by sastan** [comment]
@bstro If you are calling/using `tw` in your components module on the top-level then these will run _before_ `setup`in your main entry has run. I typically put the setup code into an extra file like `setup.env.ts`:

```js
import { setup } from 'twind'
import config from './twind.config'
setup(config)
```

And then in your main/app file import that file before your components:

```js
import './setup.env'

// now import app and components
```

I hope this helps.
