### ISSUE TITLE
tw("bg-gray-800") fails with @twind/preset-tailwind-forms@1.0.0-next.37

### ISSUE THREAD

**Issue by KyleJune** [tw-in-js/twind#317]
When I try using presetTailwindForms, I was getting an error in my code. I started getting an uncaught TypeError. I produced a minimal reproduction path for the issue.

```js
import * as twind from "https://esm.sh/twind@1.0.0-next.37?target=deno&pin=v78";
import presetTailwind from "https://esm.sh/@twind/preset-tailwind@1.0.0-next.37?target=deno&pin=v78";
import presetTailwindForms from "https://esm.sh/@twind/preset-tailwind-forms@1.0.0-next.37?target=deno&pin=v78";
import presetTypography from "https://esm.sh/@twind/preset-typography@1.0.0-next.37?target=deno&pin=v78";

export const twindConfig = {
  presets: [
    presetTailwind(),
    presetTailwindForms(),
    presetTypography(),
  ],
};

const tw = twind.setup(twindConfig)

console.log(tw("bg-gray-800"));
```

If I run this with `deno run example.js`, I get the following error.

```
error: Uncaught TypeError: Cannot read properties of undefined (reading '500')
    at s (https://cdn.esm.sh/v78/@twind/preset-tailwind-forms@1.0.0-next.37/deno/preset-tailwind-forms.js:2:1051)
    at preflight (https://cdn.esm.sh/v78/@twind/preset-tailwind-forms@1.0.0-next.37/deno/preset-tailwind-forms.js:2:608)
    at Yt.Object.defineProperties.Object.getOwnPropertyDescriptors.target (https://cdn.esm.sh/v78/twind@1.0.0-next.37/deno/twind.js:2:10767)
    at file:///home/kyle/Projects/deno/udibo/example.js:14:13
```

I found that if I comment out the `presetTailwindForms()` line or add `{ strategy: 'class' }` as the options for it, it works correctly. The expected output is bg-gray-800.

**Comment by sastan** [comment]
Thanks. I'll look into it.

**Comment by sastan** [comment]
I'm not using deno ATM. Do you have the same issue outside of deno? I could not reproduce an issue within the test suite.

**Comment by KyleJune** [comment]
I reproduced the issue on stackblitz but it only occurs with the esm.sh module. So I believe it may be an issue with how esm.sh transforms the module to be compatible with deno.

https://github.com/esm-dev/esm.sh/issues/325

**Comment by KyleJune** [comment]
I found the issue by adding the &dev to the querystring. In the code sample below, `import * as colors from "...";` results in colors being the module instead of it being the default export.

```js
/* esm.sh - esbuild bundle(@twind/preset-tailwind-forms@1.0.0-next.38) deno development */
// esm-build-07a1b388834d79ce4071708cbd8b753e7575eddf-325f36f4/node_modules/@twind/preset-tailwind-forms/preset-tailwind-forms.js
import { toColorValue } from "/v78/twind@1.0.0-next.38/deno/twind.development.js";
import * as colors from "/v78/@twind/preset-tailwind@1.0.0-next.1/deno/colors.development.js";
import defaultTheme from "/v78/@twind/preset-tailwind@1.0.0-next.1/deno/defaultTheme.development.js";
// ...
"border-color": toColorValue(theme("colors.gray.500", colors.gray[500])),
```

If you look at that imported esm.sh file [here](https://esm.sh/v78/@twind/preset-tailwind@1.0.0-next.1/deno/colors.development.js), you'll see the following at the end of the file.

```js
export {
  colors_default as default
};
```

If you look at the actual file [here](https://github.com/tw-in-js/twind/blob/v1.0.0-next.38/packages/preset-tailwind/src/colors.ts) from the npm module, you will see that each key is actually exported as a const like shown below.

```js
export const gray = {
  50: '#f9fafb',
  100: '#f3f4f6',
  200: '#e5e7eb',
  300: '#d1d5db',
  400: '#9ca3af',
  500: '#6b7280',
  600: '#4b5563',
  700: '#374151',
  800: '#1f2937',
  900: '#111827',
} as const
```

The node module uses `import * as colors from "..."` and works correctly. You can see the full file [here](https://github.com/tw-in-js/twind/blob/v1.0.0-next.38/packages/preset-tailwind-forms/src/preset-tailwind-forms.ts#L16).

```
import { toColorValue } from 'twind'
import * as colors from '@twind/preset-tailwind/colors'
import defaultTheme from '@twind/preset-tailwind/defaultTheme'
```

So the issue is basically, in node, `colors.gray` is set correctly. In the esm.sh module, it has to be accessed via `colors.default.gray`. This causes preset-tailwind-forms to fail because it's trying to do `colors.gray` like it can for node.

**Comment by KyleJune** [comment]
I added a comment to the esm.sh for what is causing the issue. It appears to be either an issue with `import * as colors from "...";` or how the exports are transformed from the colors file. I'll close this issue once it is fixed on esm.sh's side. I have a workaround there for getting it to work with deno until that issue is resolved.

**Comment by KyleJune** [comment]
This was resolved in a newer version of esm.sh. esm.sh version 99 works.
