### ISSUE TITLE
@next: Calling `setup()` multiple times leads to orphaned style tag

### ISSUE THREAD

**Issue by rschristian** [tw-in-js/twind#321]
Edit: Sorry in advance for this wall of text.

In short, style tags can be become orphans after calling `setup()` multiple times, leading to flashes of unstyled content. This results in a back-and-forth workflow of styles flashing every other refresh.

## Description / Walkthrough

1. Initial page load
    1. On initial load, without a `sheet` passed as a param, `setup` will call `getSheet()`
    https://github.com/tw-in-js/twind/blob/d7cd293d9de393dcda2d585080461cbc9c8afd2d/packages/twind/src/runtime.ts#L96-L100
    2. This will (can? not sure about all the branches here) lead to a style tag being created in the head of the document, as none exists at this time:
    https://github.com/tw-in-js/twind/blob/d7cd293d9de393dcda2d585080461cbc9c8afd2d/packages/twind/src/sheets.ts#L4-L14
    3. `setup`, after sorting its params, will firstly destroy the active sheet instance. None exists at this time, so nothing happens
    https://github.com/tw-in-js/twind/blob/d7cd293d9de393dcda2d585080461cbc9c8afd2d/packages/twind/src/runtime.ts#L101
    4. The styles get loaded into the previously created style tag and we have styles on the page
    https://github.com/tw-in-js/twind/blob/d7cd293d9de393dcda2d585080461cbc9c8afd2d/packages/twind/src/runtime.ts#L103
2. HMR/Calls `setup` again
    1. Still no `sheet`, so `getSheet()` gets called again
    2. This time it does find an existing style tag, so it returns a reference to that rather than creating a new one.
    3. `active` now exists, so the `.destroy()` occurs. This removes the style tag from the document, though the reference to this tag still exists (the `sheet` param).
    4. The styles get loaded in the now orphaned `sheet`.
    5. User is left without any styles.
3. HMR/Calls `setup` a third time
    1. `getSheet()`
    2. No existing style tag, so creates a new one and returns it.
    3. `active` does exist, but its sheet instance is the orphan. This gets removed again (nothing functionally happens as it's already been removed)
    4. The new style tag is populated with styles.

This then goes on & on, which each odd-numbered refresh resulting in a page with styles, even-numbered is blank.

## Additional

I toyed around with enforcing that `dom` create a new style tag and that "works", but that might not work at scale. Didn't actually run the tests with it, so not sure.

https://github.com/tw-in-js/twind/blob/d7cd293d9de393dcda2d585080461cbc9c8afd2d/packages/twind/src/sheets.ts#L71-L72

~~There's also that problem in that just by trying to destroy the active sheet, Twind doesn't have keep a reference to the Node, but potentially searches for it. We can't simply move the `getSheet()` after the `.destroy()` because of this.~~ Hmm, I actually don't understand what's happening here. Might've written this too soon.

The actual user code is this block:

https://github.com/rschristian/twind-wmr/blob/88d5e648cebce03428f7c4a81560dfda87b9b249/src/index.ts#L14-L20

Is there something else I should be using in this situation? The docs indicate that `setup` can be called multiple times, though this seems like it can (will?) lead to stale references like this.

Thanks as always for this awesome lib!

**Comment by rschristian** [comment]
Sorry if my description is awful, certainly let me know and I can try to rephrase if it didn't make sense.

Can't believe I also forgot a reproduction. Here's one: https://github.com/rschristian/twind-wmr-setup-bug. Simply run the dev server (`npm run start`) and save `public/index.js` a few times to trigger the HMR. It'll flash between Twind styles being applied and then disappearing (due to the style tag being removed and not replaced).

I am still trying to look into it myself, though there's a few bits that I don't understand.

**Comment by sastan** [comment]
should be fixed by [0e2aa5c](https://github.com/tw-in-js/twind/commit/0e2aa5c4f07e5bca3bea37f864773f665935a263) in the next release

**Comment by rschristian** [comment]
@sastan Manually patched and can confirm, working beautifully! Thanks!

I had ended up doing something similar, though forgot to update the PR. Sorry about that.
