### ISSUE TITLE
Style problems when visiting the page for the first time after next.js-twind build

### ISSUE THREAD

**Issue by xlboy** [tw-in-js/twind#323]
After next.js-twind is build, when you visit the page for the first time.

the style cannot be loaded immediately, and there will be a short process of `no style`.

this problem will not appear when it is developed locally, but it will appear after build.

---

This is an example ↓

https://user-images.githubusercontent.com/63690944/167306258-884c8bc0-0e86-4a1a-a7e7-1feffc818ab0.mov

---

If you look at it carefully, you will see that at the beginning, `This is Twind!` The text is on the left

But that was only for a moment, and then style came along

---

This is the related code image ↓

![126941652029239_ pic](https://user-images.githubusercontent.com/63690944/167306990-6284cdd6-b549-4fd0-8206-fec8696c9c7b.jpg)

---

This is a simple code example, you may need to download it locally for testing.  ↓

`https://codesandbox.io/s/nextjs-twind-prod-transition-error-t9r2i8`

```sh
# step 1
yarn
# step 2
yarn build
# step 3
yarn start
```
---

**Comment by xlboy** [comment]
![126981652029682_ pic](https://user-images.githubusercontent.com/63690944/167307337-c6e7206e-f773-4c21-8fba-8acd11de08d1.jpg)

![127001652029692_ pic](https://user-images.githubusercontent.com/63690944/167307347-7d9fccb1-6c98-4cfb-b6f5-ece0c3359a13.jpg)

**Comment by xlboy** [comment]
After testing, I found something.

This problem occurs whenever `tw` is called outside the component.

If it is called inside the component, this problem will not occur.

---

In the example I provided above, it belongs to the nature of external call

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/63690944/167375696-b245a296-9151-479b-ae42-bb16c45edebc.png">

`https://codesandbox.io/s/nextjs-twind-prod-transition-error-t9r2i8?file=/src/pages/index.tsx`

**Comment by xlboy** [comment]
> I can reproduce the issue. It seems the the HTML response those not contain any twind style (the tag is empty). The cause may very likely be the the tw calls outside of render. But I do not know why ATM. Could you try v1 (it is compatible with tailwind v3)? There this issue is certainly fixed.
> 
> https://codesandbox.io/s/nextjs-twind-prod-transition-error-forked-y2chi3?file=/src/pages/index.tsx

Thank you very much, It does solve this problem.

However, I found that after upgrading to `1.0.0-next.38`, it no longer seems to be compatible with `@twind/typescript-plugin`. **(When the version is still `v0`, it can be used normally)**

I don't know if this is a configuration problem on my side. I may need your help. 😂

---
The example of this link is based on the one you provided above. It only adds an extra `@twind/typescript-plugin`. ↓

[`https://codesandbox.io/s/nextjs-twind-prod-transition-error-forked-kuis4j?file=/src/pages/index.tsx`]

(https://codesandbox.io/s/nextjs-twind-prod-transition-error-forked-kuis4j?file=/src/pages/index.tsx)
<img width="500" alt="image" src="https://user-images.githubusercontent.com/63690944/167565134-ba63cec6-7e5a-4f12-a36b-2f0e3b604f85.png">

**Comment by xlboy** [comment]
I tested it here and found that it seems to be the problem on the side of `@twind/preset-tailwind (v1.0.0-next.38)`.

<img src="https://user-images.githubusercontent.com/63690944/167665985-88fbdc02-25c3-4ba9-850f-741f4f4be008.jpg" width="500"></img>

**Comment by sastan** [comment]
The vscode and typescript plugins are not yet compatible with twind@next.

Closing for now. Please re-open if you need to.
