### ISSUE TITLE
Support for arbitrary variants.

### ISSUE THREAD

**Issue by hastebrot** [tw-in-js/twind#324]
Arbitrary variants will be part of Tailwind 3.1.

https://github.com/tailwindlabs/tailwindcss/pull/8299

![FSQBZKcWYAIa0Cq](https://user-images.githubusercontent.com/496255/167308526-9ae360d4-769b-46db-9a00-d06c635f5025.jpg)

**Comment by sastan** [comment]
Thank you for the heads up. I started implementing it.

**Comment by sastan** [comment]
available in the next release
