### ISSUE TITLE
@next: vscode plugin broken?

### ISSUE THREAD

**Issue by bstro** [tw-in-js/twind#338]
The VSCode plugin shows red lines for every class I try to use:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/627290/173206800-909ea377-0b02-4894-a249-8669821ff2c0.png">

I have a `twind.config.ts` file containing the following:
```
import { setup } from "twind";
import presetTailwind from "@twind/preset-tailwind";

setup({
  presets: [presetTailwind()],
  /* config */
});
```

running [v1.0.0-next.38](https://github.com/tw-in-js/twind/releases/tag/v1.0.0-next.38)

**Comment by sastan** [comment]
I didn't had time yet to update the vscode-plugin.
