### ISSUE TITLE
Inject css error on safari for `focus-visible:`

### ISSUE THREAD

**Issue by nicolaiunrein** [tw-in-js/twind#343]
Hey,
My Safari fails on the `focus-visible` pseudo-class.
I wonder whether this should be added to the error ignore pattern in the inject function like its done for 
```
// ::-moz-focus-inner
// :-moz-focusring
```
Safari version:
Version 14.1.2 (14611.3.10.1.7)

**Comment by sastan** [comment]
Do you have still have this issue?

**Comment by sastan** [comment]
Closing for now. Please re-open if you still have this issue.
