### ISSUE TITLE
Wrong CSS outputs.

### ISSUE THREAD

**Issue by SalvadorLekan** [tw-in-js/twind#345]
I'm using Twind in a $fresh project and I ran into this two issues on the first day of using TWind.

1. `grid-cols-[60px,1fr]` generates `grid-template-columns: 60px,1fr;` instead of `grid-template-columns: 60px 1fr;`
2. `bg-[url('/logo.svg')]` generates `background-position: url(/logo.svg);` instead of `background-image: url(/logo.svg);`
The Twind shim comes from [here](https://esm.sh/twind@0.16.17/)

**Comment by sastan** [comment]
I think that are _known_ bugs. Could you try the next branch? 

PS: I think `grid-cols-[60px,1fr]` should be `grid-cols-[60px_1fr]`

**Comment by hanayashiki** [comment]
> I think that are _known_ bugs. Could you try the next branch?
> 
> PS: I think `grid-cols-[60px,1fr]` should be `grid-cols-[60px_1fr]`

`grid-cols-[60px_1fr]` generates `grid-template-columns: 60px_1fr;`

is that a bug?

**Comment by sastan** [comment]
These are issue in twind@v0.16 and should all be fixed in [twind@next](https://github.com/tw-in-js/twind/tree/next). 

If you can not use twind@next please re-open this issue...
