### ISSUE TITLE
Feat: Tailwind 3.x support

### ISSUE THREAD

**Issue by mrbrianhinton** [tw-in-js/twind#346]
A lot of big updates came to Tailwind 3.x that added a lot of advanced styling options. Any plans in place to add 3.x support to twind?

**Comment by xlboy** [comment]
> A lot of big updates came to Tailwind 3.x that added a lot of advanced styling options. Any plans in place to add 3.x support to twind?Tailwind 3.x 进行了许多重大更新，增加了许多高级样式选项。是否有计划为 twind 添加 3.x 支持？

Seems to be in the `next branch` for support

**Comment by renhiyama** [comment]
still its not ready ;-;
would suggest to try to stick with twind current version, theres some import errors with @ next version

**Comment by sastan** [comment]
tailwind 3.0 is supported in the next branch. 3.1 will be added soon.

**Comment by renhiyama** [comment]
@sastan is twind@next working now? (If I can make you recall, 2 months has passed by when I reported you that twind couldn't be used with important plugins that it ships with, is that bug fixed?)

**Comment by smcardle** [comment]
Hi @sastan 

Great project.
Any time line on the 3.1 release ??

Looking forward to getting this into my project.

**Comment by vicary** [comment]
In Deno, importing the next branch via `https://esm.sh/twind@1.0.0-next.38` will crash with the following error

```
error: Uncaught (in promise) TypeError: Import 'https://esm.sh/twind@1.0.0-next.38/sheets' failed: 500 Internal Server Error
    at https://deno.land/x/fresh@1.1.1/plugins/twind.ts:1:30
```

Looking at the contents of https://esm.sh/twind@1.0.0-next.38/sheets shows this error message.
```
open /tmp/esm-build-e6074437d10b0e36e45c0eed3e80cb2ed4c5d9ab-54de2885/node_modules/twind/sheets.mjs: no such file or directory
```

When changing to Skypack via `https://cdn.skypack.dev/twind@1.0.0-next.38`, I got a similar error message.
```
error: Uncaught (in promise) TypeError: Module not found "https://cdn.skypack.dev/-/twind@v1.0.0-next.38-aP2ZS3cw8PA9tHESqgyy/dist=es2019,mode=raw/sheets".
    at https://cdn.skypack.dev/twind@next/sheets:16:23
```

**Comment by renhiyama** [comment]
Bye bye sheets or what? 😱

**Comment by vicary** [comment]
> Bye bye sheets or what? 😱

These CDNs hosts build artifacts directly, their hosted module will throw build errors from within the contents.

My educated guess is the new sheet not being ESM compatible or something.

**Comment by KyleJune** [comment]
That is an esm.sh issue not a twind issue. Try pinning v85 of esm.sh. It works for me. Also I recommend opening an issue on the esm.sh repo for the error you are getting.

**Comment by vicary** [comment]
@KyleJune `https://esm.sh/twind@1.0.0-next.38` is the only URL I was importing. Not planning to use sheets, it must be an internal dependency.

Not sure where does it differs, but using your pinned URL still gets me another error.
```
TypeError: The specifier ""twind/sheets"" backtracks above its prefix ""twind/""
```
<img width="771" alt="image" src="https://user-images.githubusercontent.com/85772/193498528-e79e7682-a657-42b6-ba37-050c38a8016e.png">

This new error looks like a monorepo thing taht esm.sh doesn't support.

**Comment by aadamsx** [comment]
I'm using Deno/Fresh.  Tried adding: https://esm.sh/twind@1.0.0-next.38 to the "twind" import_map.json and got the following: 
```javascript
Download https://esm.sh/twind@1.0.0-next.38/
error: Uncaught (in promise) TypeError: Import 'https://esm.sh/twind@1.0.0-next.38/sheets' failed: 500 Internal Server Error
    at https://deno.land/x/fresh@1.1.1/plugins/twind.ts:1:30
  await import(entrypoint);
  ^
    at async dev (https://deno.land/x/fresh@1.1.1/src/dev/mod.ts:187:3)
    at async file:///Users/xyz/Projects/formspoint_website/dev.ts:5:1
```

**Comment by KyleJune** [comment]
That isn't an esm.sh issue. v0 and v1 are not compatible. Just updating your import map wouldn't get it to work. It sounds like fresh is importing twind/sheets somewhere which would work with v0 but not with v1. So your import map is the problem unless you update the spots where twind is imported to do things the new way.

I don't know enough about fresh to help you but I will say the v1 import I showed works if you use the new API correctly. I use it in a react project of mine.

**Comment by KyleJune** [comment]
It looks like the fresh twind plugin is the problem. The error stack clearly shows that file is importing twind/sheets. You would have to write your own v1 twind plugin for your project to be able to use v1 of twind with fresh.

**Comment by vicary** [comment]
@KyleJune How should I import the new sheets in v1?

**Comment by KyleJune** [comment]
You just import twind. To create a virtual sheet you call `twind.virtual()`. The way to setup twind and getting a style tag is different too. Check the v1 documentation for more details.

https://twind.style/

**Comment by sastan** [comment]
@vicary Please open a new issue to discuss the deno fresh issue. Thank you!

**Comment by sastan** [comment]
@KyleJune Thank you for jumping at these issues and helping other users. Very much appreciated!

**Comment by sastan** [comment]
Closing because twind@next will have tailwindcss v3.1 compatibility in the next release.
