### ISSUE TITLE
Add what version of Tailwind is supported somewhere in the documentation.

### ISSUE THREAD

**Issue by orsi** [tw-in-js/twind#350]
Pretty self-explanatory. I've often looked at the Tailwind documentation to remember classnames, and sometimes find myself troubleshooting why some classes don't work just find out I forgot I'm looking at new Tailwind v3 classes/colors/features/etc.

**Comment by devstein** [comment]
+1 Just went down this rabbit hole as well

**Comment by po-cheng** [comment]
+1 Seriously. Since the twind documentation doesn't have a list of classes that works, at least tell me what version of tailwind's documentation I should be looking at

**Comment by sastan** [comment]
v0.16 supports tailwind v2 and v1 (next branch) supports tailwind v3.0 (working on v3.1 support)

**Comment by orsi** [comment]
> v0.16 supports tailwind v2 and v1 (next branch) supports tailwind v3.0 (working on v3.1 support)

Yes, this issue is to have this stated explicitly in the documentation -- preferably very visible and very hard-to-miss.

**Comment by sastan** [comment]
I have added a compatibility section to each preset like https://twind.style/preset-tailwind#-compatibility. Does that help? And is it enough?
