### ISSUE TITLE
Deno: css function not working / not sure how to use

### ISSUE THREAD

**Issue by JasperSurmont** [tw-in-js/twind#354]
So I have a file with: 
```ts
import { css } from 'twind/css'
import { tw } from 'twind'

const styles = css`
    textDecorationColor: transparent,
    textDecoration: underline,
    transition: .5s,
    &:hover: {
        textDecorationColor: pink,
    }
`;
```
and later in the return of the component there is:
```jsx
<p  className={ tw`${styles}` } >test</p>
```

Is this the correct way to use the css function? If so, it isn't working on my [Deno Fresh project](fresh.deno.dev): the result is that the <p> attribute gets a class `tw-xxxxx` but the actual css for that class is missing.

**Comment by primos63** [comment]
I think you're mixing the [object and template literal](https://twind.dev/handbook/css-in-twind.html#the-css-function) formats. 
You want the following when using a template literal
```javascript
const styles = css`
  textDecorationColor: transparent;
  textDecoration: underline;
  transition: 0.5s;
  &:hover {
    textDecorationColor: pink;
  }
`;
```
and this for the object notation
```javascript
const styles = css({
  textDecorationColor: "transparent",
  textDecoration: "underline",
  transition: "0.5s",
  "&:hover": {
    textDecorationColor: "pink",
  },
});
```
I just started looking at Fresh and Twind, but these formats work in the default Fresh example. Twind docs state that there is a slight performance hit taken using the template literal format. They suggest using the object notation.

**Comment by JasperSurmont** [comment]
Thanks! It works
