### ISSUE TITLE
class columns dose not exist in twind

### ISSUE THREAD

**Issue by munzx** [tw-in-js/twind#356]
Building a component that requires "columns" to adjust to different pages but found out that, unlike TailwindCSS, Twind does not have `columns-{num}` classes.

So I had to use the following and was not happy with it as the purpose of using Twind is to dynamically style pages based on users' preferences.

`
    @media (min-width: 640px) {
        .columns {
            columns: 2;
        }
    }
    @media (min-width: 768px) {
        .columns {
            columns: 3;
        }
    }

    @media (min-width: 1024px) {
        .column {
            columns: 4;
        }
    }

    .columns {
        columns: 1;
    }

`

**Comment by sastan** [comment]
`columns` is a tailwindcss v3 feature that is only supported in [twind@next](https://github.com/tw-in-js/twind/tree/next)
