### ISSUE TITLE
Issue with copying component from tailwind docs

### ISSUE THREAD

**Issue by reggi** [tw-in-js/twind#362]
I'm using Deno / Fresh and I'm trying to copy a component from the docs here:

https://tailwindui.com/components/application-ui/forms/input-groups

Here's what it looks like in fresh locally for me:

![Screen Shot 2022-08-03 at 9 36 15 PM](https://user-images.githubusercontent.com/296798/182744385-2e34e4e7-9e5d-4832-9de5-b3eadaea3504.png)

Here's what it looks like on the site above:

![Screen Shot 2022-08-03 at 9 36 23 PM](https://user-images.githubusercontent.com/296798/182744336-00f337af-2afc-402a-a0dc-47490c4b1c0b.png)

This is because some of the "global" attribute / tag driven styles aren't appearing on the fresh page.  (`input`, `[type="text"]`, `select`)

I'd love to learn if there's a way to fix this so that the components are 1:1 with the tailwind documentation.

**Comment by reggi** [comment]
https://github.com/denoland/fresh/issues/584

**Comment by rschristian** [comment]
It sounds like you might've skipped over the instructions for that component you are copying? It states that it requires the `@tailwindcss/forms` plugin:

>
>  This example requires Tailwind CSS v2.0+ 
>  
>  This example requires some changes to your config:
>  
>  ```
>  // tailwind.config.js
>  module.exports = {
>    // ...
>    plugins: [
>      // ...
>      require('@tailwindcss/forms'),
>    ],
>  }
>  ```
>

Tailwind and Twind plugins are incompatible though, so this is not possible.

> the components are 1:1 with the tailwind documentation.

TailwindUI isn't the Tailwind docs, but a separate product of sorts. v2 of Tailwind's docs (or v3 if you're using `twind@next`) should line up pretty well.

**Comment by reggi** [comment]
Cool thanks for the explanation and tip. 

I'm using deno and switched my import map, to used `next` but didn't work...


```
{
  "imports": {
    "$fresh/": "https://deno.land/x/fresh@1.0.2/",
    "preact": "https://esm.sh/preact@10.10.0",
    "preact/": "https://esm.sh/preact@10.10.0/",
    "preact-render-to-string": "https://esm.sh/preact-render-to-string@5.2.1?external=preact",
    "@twind": "./utils/twind.ts",
    "twind": "https://esm.sh/twind@next/",
    "twind/": "https://esm.sh/twind@next/"
  }
}

```

```
Watcher File change detected! Restarting!
Download https://esm.sh/twind@next/sheets
Download https://esm.sh/twind@next/shim
Download https://esm.sh/twind@next/
Download https://esm.sh/twind@1.0.0-next.38/sheets
Download https://esm.sh/twind@1.0.0-next.38/shim
error: Uncaught (in promise) TypeError: Import 'https://esm.sh/twind@1.0.0-next.38/sheets' failed: 500 Internal Server Error
    at file:///Users/thomasreggi/Desktop/my-fresh/main.ts:12:30
  await import(entrypoint);
  ^
    at async dev (https://deno.land/x/fresh@1.0.2/src/dev/mod.ts:163:3)
    at async file:///Users/thomasreggi/Desktop/my-fresh/dev.ts:5:1
Watcher Process finished. Restarting on file change...

```

**Comment by rschristian** [comment]
Er, well that's because `twind@next/sheets` doesn't exist. The API has changed in `next`. [Here's the migration guide](https://github.com/tw-in-js/twind/blob/next/documentation/migration.md#from-twind-v016)

I'm not familiar with Fresh, but if that's your usage, it will need to be altered, else if that's something the framework is doing, you might need to stick with the stable version instead.

**Comment by sastan** [comment]
I would like to close this in favor of #384.

Please re-open if that is not what you want.
