### ISSUE TITLE
Nuxt 3 support

### ISSUE THREAD

**Issue by pi0** [tw-in-js/twind#367]
Hi @sastan. I discovered twind in an issue made by @tylerforesthauser (https://github.com/nuxt/nuxt.js/issues/14551) and to be honest I really love the idea. Amazing work 🚀 

[Nuxt 3](https://v3.nuxtjs.org/) supports some new hooks that enabled it to fully integrate with SSR of twind 1.x. 

I initially started a local branch to make `with-nuxt` module for Nuxt but there was some tricky setup issues that finally decided to move quick prototype to a standalone repo [nuxt-twind](https://github.com/pi0/nuxt-twind). It is an experiment yet but Would be happy to at some point move it back to twind repo if you like.

**Comment by sastan** [comment]
Thank you for taking the time.Awesome work. I found one little issue in https://github.com/pi0/nuxt-twind/blob/main/src/runtime/twind.nitro.ts#L13: it should be `<style data-twind>${r.css}</style>`

If you like/want to we can move into this repo as @twind/with-nuxt...

**Comment by pi0** [comment]
Nice spot @sastan. I would be happy if you like to move module under monorepo or in tw-in-js org. let me know what you prefer :)

**Comment by sastan** [comment]
Sorry for the delay. Please open a PR. That would really help. If you do not have the time would it be ok if I copy-paste your code (with attribution of cause)?
