### ISSUE TITLE
"sticky" shorthand ends up with an empty translation

### ISSUE THREAD

**Issue by rschristian** [tw-in-js/twind#37]
The mysterious case of `.sticky` lives on! https://github.com/lukejacksonn/oceanwind/issues/43

For whatever reason `sticky` creates an empty translation in the browser. I spotted this back when using oceanwind, and after testing it again tonight, it bizarrely still fails to work. All other positioning shorthand work as expected though.

**Comment by rschristian** [comment]
I'm far from familiar with this code base, but if I'm understanding correctly, `sticky` does seem to be treated like all other positional shorthands here: https://github.com/tw-in-js/twind/blob/main/src/twind/plugins.ts#L313-L317

**Comment by sastan** [comment]
Thanks for the report.

We have the following test cases [src/__tests__/prefix.test.ts:L39](https://github.com/tw-in-js/twind/blob/main/src/__tests__/prefix.test.ts#L39) and [src/__tests__/api.json:L31](https://github.com/tw-in-js/twind/blob/main/src/__tests__/api.json#L31). It seems as the prefixed version is not valid:

```css
.sticky {
  position:-webkit-sticky, sticky;
}
```

**Comment by sastan** [comment]
There is an open issue [tiny-css-prefixer#10](https://github.com/kitten/tiny-css-prefixer/issues/10)

**Comment by rschristian** [comment]
Wow, thanks for getting to the bottom of this so quickly!
