### ISSUE TITLE
Spaces don't work in immediate `calc()` like `m-[calc(1px + 1%)]` correctly

### ISSUE THREAD

**Issue by alker0** [tw-in-js/twind#370]
`m-[calc(1px + 1%)]` doesn't escape white-space in generated selector like:
```css
.m-\[calc\(1px \+ 1\%\)\]{margin:calc(1px + 1%)}
```
So this matches `1%)]` in `+` in `.m-[calc(1px` but not `m-[calc(1px + 1%)]`.
Removing spaces like `m-[calc(1px+1%)]` works.
In real CSS, you must insert spaces around `+`/`-` while according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/calc#notes) so `twind` should allow users to follow that rule, or documents this behavior.

**Comment by sastan** [comment]
You need to use an [underscore `_` within classnames](https://tailwindcss.com/docs/adding-custom-styles#handling-whitespace): `m-[calc(1px_+_1%)]`

In this case, you could omit the spaces because twind will figure out that it needs to insert spaces: `m-[calc(1px+1%)]`

**Comment by alker0** [comment]
Thank you for telling me the link to the section in document and sorry I'm overlook it.
