### ISSUE TITLE
Outline Rules are not recognized

### ISSUE THREAD

**Issue by RobertGeorgi** [tw-in-js/twind#372]
I'm currently trying to set an outline rule in a React project.

```jsx
<div className={tw`focus:outline-1`} />
```

and i receive the following warning in the dev console

`[UNKNOWN_THEME_VALUE] {"key":"outline.1"}`
`[UNKNOWN_DIRECTIVE] {"rule":"outline-1"}`

As it seems right now, all outline related styles are missing regardless of me using a custom theme or not.

**Comment by madouidesign** [comment]
Same issue here with lit-html 

`<input ...  class="${tw` ... focus:outline-blue-500 ..."`} />`

The color does not apply.

**Comment by sastan** [comment]
twind v0.16 (Tailwindcss v2 compat) only provides [three outline colors](https://v2.tailwindcss.com/docs/outline#outlines) out-of-the-box: `none`, `white`, and `black`.

with [twind v1.0.0-next.39](https://github.com/tw-in-js/twind/tree/next) (Tailwindcss v3 compat) [all colors are available](https://tailwindcss.com/docs/outline-color) out-of-the-box.
