### ISSUE TITLE
Reference docs search not working on https://twind.style -- impersonator website?

### ISSUE THREAD

**Issue by vintlucky777** [tw-in-js/twind#375]
# How I got here

1. Search "twind" in Duckduckgo <img width="838" alt="image" src="https://user-images.githubusercontent.com/3831006/191139789-7e5603ca-b0ff-42d8-9408-c845b9238ce1.png">
2. Open docs link at https://twind.style/docs/reference (third search link)
3. Try searching the docs - search doesn't work
4. Docs are outdated, for example it references `import { injectGlobal } from 'twind'` that does not work.

**Comment by tmikaeld** [comment]
Might be an early site for the "next" branch, the 1.0 version of Twind, which does have injectGlobal feature.

**Comment by rschristian** [comment]
Yep I'd assume it's the official docs for v1, just early and rough (as v1 still is).

Contains migration guide and changes from v0.16 to v1: https://twind.style/docs/migration

**Comment by sastan** [comment]
Yes that is the work-in-progress website for twind v1.
