### ISSUE TITLE
Next: Allow to collect unmatched classes/keys.

### ISSUE THREAD

**Issue by tmikaeld** [tw-in-js/twind#376]
We use Twind on the server side, it would be nice if we could collect the missing/invalid classes from the tw instance instead of catching the error as we currently have to do.

**Comment by sastan** [comment]
That would be nice. I plan to add something like that in the future. 

What I don't understand is: What do you mean by `instead of catching the error as we currently have to do`?

**Comment by sastan** [comment]
In v1.0.0 we added a new warning mechanism: https://github.com/tw-in-js/twind/blob/main/packages/core/CHANGELOG.md#100

Maybe this helps. Otherwise feel free to re-open.
