### ISSUE TITLE
`underline` should be `text-decoration-line:underline` instead of `text-decoration:underline`

### ISSUE THREAD

**Issue by kt3k** [tw-in-js/twind#377]
For compatibility to tailwind, `.underline` should be `text-decoration-line: underline` instead of `text-decoration: underline`
https://tailwindcss.com/docs/text-decoration

**Comment by sastan** [comment]
Thank you. Are you using twind@0.16? In that case `text-decoration: underline` is the correct one because twind@0.16 is for tailwindcss 2.x. If you want to use tailwindcss v3.x please try twind@1.0.0-next.39 (the [next  branch](https://github.com/tw-in-js/twind/tree/next))

**Comment by sastan** [comment]
Closing for now. Feel free to re-open.
