### ISSUE TITLE
twind@next with Deno/Fresh

### ISSUE THREAD

**Issue by aadamsx** [tw-in-js/twind#384]
I'm using Deno/Fresh.  Tried adding: https://esm.sh/twind@1.0.0-next.38 to the "twind" import_map.json 
```json
{
  "imports": {
    "$fresh/": "https://deno.land/x/fresh@1.1.1/",
    "preact": "https://esm.sh/preact@10.11.0",
    "preact/": "https://esm.sh/preact@10.11.0/",
    "preact-render-to-string": "https://esm.sh/*preact-render-to-string@5.2.4",
    "@preact/signals": "https://esm.sh/*@preact/signals@1.0.3",
    "@preact/signals-core": "https://esm.sh/*@preact/signals-core@1.0.1",
    "twind": "https://esm.sh/twind@1.0.0-next.38",
    "twind/": "https://esm.sh/twind@1.0.0-next.38/"
  }
}
```
and got the following: 
```javascript
Download https://esm.sh/twind@1.0.0-next.38/sheets
error: Uncaught (in promise) TypeError: Import 'https://esm.sh/twind@1.0.0-next.38/sheets' failed: 500 Internal Server Error
    at https://deno.land/x/fresh@1.1.1/plugins/twind.ts:1:30
  await import(entrypoint);
  ^
    at async dev (https://deno.land/x/fresh@1.1.1/src/dev/mod.ts:187:3)
    at async file:///Users/xyz/Projects/formspoint_website/dev.ts:5:1
```

As of fresh@1.1.1 Fresh references the folloiwng twind versions:
```json
    "twind": "https://esm.sh/twind@0.16.17",
    "twind/": "https://esm.sh/twind@0.16.17/"
```

feedback on this issue when posted to issue 346: 
https://github.com/tw-in-js/twind/issues/346#issuecomment-1264909829
https://github.com/tw-in-js/twind/issues/346#issuecomment-1264914478

**Comment by retraigo** [comment]
You are probably using the **twind plugin for fresh**. The plugin uses sheets which can be found in a different location in twind-next.

Even if you somehow make it work by tweaking some of the plugin's code, it depends on `Storage`, something not part of the virtual sheets in v3. Your best bet would be waiting for a `twind-next` plugin or writing your own plugin.

**Comment by sastan** [comment]
Initial work has been started here: https://github.com/denoland/fresh/pull/946

**Comment by lino-levan** [comment]
https://github.com/denoland/fresh/pull/946 has been merged (and released iirc). This issue can probably be closed.
