### ISSUE TITLE
[Bug]: tailwind classnames dont applied to SVG elements especially 'fill' key doesnt work.

### ISSUE THREAD

**Issue by shulgamalthael** [tw-in-js/twind#401]
### Reproduction

I wanted to isolate all styles and classes for shadowRoot element so they don't override other outer styles. I have nice result, but there is a once problem.

When im using twind/observe with shadowRoot in React project. All classes was applied, but there is a once that doesnt work, Its SVG element`s fill key. When i put to class field, for example: 'fill-blue-700', after compilation i cant see applied blue color on SVG Element.

**Code to reproduce:**
```
import React from 'react';
import ReactDOM from 'react-dom/client';

import { create, cssomSheet } from 'twind';
import { createObserver } from 'twind/observe';

const sheet = cssomSheet({ target: new CSSStyleSheet() });
const instance = create({ sheet });

const rootElement = document.getElementById('root');
const styledElement = document.createElement("div");
const shadow = styledElement.attachShadow({ mode: "open" });
shadow.adoptedStyleSheets = [sheet.target];
rootElement.append(styledElement);
const root = ReactDOM.createRoot(shadow);

createObserver(instance).observe(shadow);

root.render(
  <div className="h-10 w-10 bg-red-700">
		<svg
      viewBox="0 0 512 512"
			className="fill-blue-700"
      xmlns="http://www.w3.org/2000/svg"
    >
     {/* Font Awesome Icon */}
      <path d="M362.7 19.3L314.3 67.7 444.3 197.7l48.4-48.4c25-25 25-65.5 0-90.5L453.3 19.3c-25-25-65.5-25-90.5 0zm-71 71L58.6 323.5c-10.4 10.4-18 23.3-22.2 37.4L1 481.2C-1.5 489.7 .8 498.8 7 505s15.3 8.5 23.7 6.1l120.3-35.4c14.1-4.2 27-11.8 37.4-22.2L421.7 220.3 291.7 90.3z" />
    </svg>
	</div>
);

```

![image](https://user-images.githubusercontent.com/64535315/204270213-3ee6b21f-8ecf-4d23-88ce-2a34c86cf49f.png)

### Describe the bug

All steps descripted on the reproduction field. Just copy this code for reproducing.

### Severity

annoyance

### System Info

```sh
Twind/observe package.
```

### Additional Information

![image](https://user-images.githubusercontent.com/64535315/204271620-c33f2152-5373-476b-80cb-9c02f79b0224.png)
This problem arises only with SVG Elements.

**Comment by sastan** [comment]
fill seems to work in v1: https://next.twind-run.pages.dev/runny-respond-cafe

Could it be that this has something to do with shadow dom?
