### ISSUE TITLE
Support for tailwind @layer directive in Twind with Deno/Fresh

### ISSUE THREAD

**Issue by eduardobbrito** [tw-in-js/twind#406]
Hi, I'm trying to make some custom classes available to all components, using tailwind's "@ layer" directive and "@ apply" function.

In pure tailwind, this would look something like below, and can be seen [here in the Playground](https://play.tailwindcss.com/hZqfRA6E6C?file=css):

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components {
  .heading-1 {
    @apply font-bold text-2xl tracking-wide;
  }
}
```

However I can't seem to find a way to do this in Twind in a Deno/Fresh project.

Is there support to the "@ layer" directive when using Deno/Fresh?

**Comment by sastan** [comment]
The `@layer` rule is supported: https://next.twind-run.pages.dev/beauty-vienna-toga?file=script&result=css This example uses `injectGlobal` but it works with `css` or within rules as well.

Documentation is still lacking but here you find the available layer names: https://twind.style/reference#css-strings-and-objects

**Comment by mrtornado** [comment]
I'm searching to do the same thing as @eduardobbrito but I can't get it to work. I tried by importing a global css that looks like: 
`@twind base;
@twind components;
@twind utilities;

@layer components {
  .heading-1 {
    @apply font-bold text-2xl tracking-wide;
  }
}`

the injectGlobal is not available in the Fresh / Deno setup.  Was anybody able to define some global style ? :) I can do it in plane css but yea I want with twind.
