### ISSUE TITLE
[Bug]: (https://twind.style/) mobile version

### ISSUE THREAD

**Issue by Danielduel** [tw-in-js/twind#415]
### Reproduction

Go to https://twind.style/
Reduce width to be narrower than 1024px

### Describe the bug

It is caused by "Supporters" section being too wide
I can open PR for that if you like to get that fixed

### Severity

annoyance

### System Info

```sh
unrelated
```

### Additional Information

Have a nice day

**Comment by sastan** [comment]
Thank you very much for the report. If you have the time please create a PR to fix it. Greatly appreciated.

**Comment by Danielduel** [comment]
> Thank you very much for the report. If you have the time please create a PR to fix it. Greatly appreciated.

I feel assigned to this issue then ^^

**Comment by Danielduel** [comment]
@sastan do I have to sign any IPR statement?

**Comment by Danielduel** [comment]
Hmm... this sponsors node is svg with generated coordinates and I can't just change the config and regenerate it afaik.
I will go with css trick to crop it for mobile users and add it to head with comments.

**Comment by Danielduel** [comment]
But after I've dived into this issue... it is more sponsorskit generating stuff in very hardcoded way.
