### ISSUE TITLE
[Feature]: can add config to ignore observe some html tag

### ISSUE THREAD

**Issue by huijiewei** [tw-in-js/twind#424]
### Describe the problem

Because I use prismjs to highlight the code, prismjs will create a lot of classes.

thanks.

### Describe the proposed solution

maybe to ignore observe by attribute id or other way.

### Importance

nice to have

**Comment by sastan** [comment]
There is a `ignorelist` config option (array of string or regexp) to ignore certain classes. I once tried to allow not observing some elements but that might not work during SSR.

Still thinking about this feature because it is very useful in certain situations. It could be something like:

```html
<section class="border">
	<div twind-ignore>
      <!-- twind ignores all class attributes within this element -->
    </div>
</section>
```
