### ISSUE TITLE
[Feature]: daisyUI stylings are not supported?

### ISSUE THREAD

**Issue by esphoenixc** [tw-in-js/twind#427]
### Describe the problem

I would like to use twind and daisyUI. This would be so awesome

### Describe the proposed solution

twind can't read daisy UI classes :(

twind config needs a plugin option to give twind daisyUI!

### Importance

would make my life easier

**Comment by mortezasabihi** [comment]
I have the same problem. There is no `plugins` option.

**Comment by sastan** [comment]
daisyUI is tailwindcss plugin. tailwindcss plugins are currently not directly supported in twind. You could create a [daisy preset](https://twind.style/presets) — using [rules](https://twind.style/rules) and [variants](https://twind.style/variants).
