### ISSUE TITLE
[Bug]: subtraction followed by a variable not normalized properly

### ISSUE THREAD

**Issue by sibbng** [tw-in-js/twind#429]
### Reproduction

https://twind.run/baton-wound-radius?result=css

### Describe the bug

Hi @sastan, in https://github.com/tailwindlabs/tailwindcss/pull/4147 I contributed tailwindcss to fix some arbitrary values related issues. As I mentioned in the PR, I got this regex from twind project. But it has an edge case as reported in https://github.com/tailwindlabs/tailwindcss/issues/9832. I fixed this in https://github.com/tailwindlabs/tailwindcss/pull/10074. But I'm not sure if my solution is ideal or not. I wanted to let you know, the same issue also exists in twind. I can make a PR if you think my solution is good enough.

### Severity

annoyance

### System Info

```sh
-
```

**Comment by sastan** [comment]
Thanks for the heads-up. It would be really appreciated if you could create a PR to fix this in twind as well.

**Comment by ayame113** [comment]
Perhaps I ran into the same issue.
https://twind.run/denim-airline-vampire?result=css
