### ISSUE TITLE
Docs: Can only cycle through color schemes once

### ISSUE THREAD

**Issue by rschristian** [tw-in-js/twind#431]
### Documentation Is:

Not Sure?

### Please Explain in Detail...

You can only toggle through the color schemes once, after which it'll become locked on the last option. The user needs to refresh the page in order to go back.

So clicking once switches from Auto to Dark, clicking again goes from Dark to Light, but clicking a third time does nothing. The user is stuck on Light mode until they refresh the page.

### Your Proposal for Changes

Should be a loop, Auto -> Dark -> Light -> Auto (again)

### Misc

This isn't relevant to the issue, though I feel like I should mention it regardless: I personally find the dark mode color scheme to be quite impossible to read, to the point where I had to write up some user CSS in order to use the site.

This very well might just be a "me issue" but the blue-on-blue text mixed with the *very* bright highlight colors made it too much of a challenge to read.

I just thought I should mention it in case I'm not the only one. I'm quite happy with my workaround at the moment though so feel free to ignore.

**Comment by sastan** [comment]
I can confirm the issue and will try to fix it.
