### ISSUE TITLE
[Docs]: Remix with React 18 example not working as expected

### ISSUE THREAD

**Issue by lkwr** [tw-in-js/twind#442]
### Documentation Is:

Needed

### Link to relevant page or pages

https://github.com/tw-in-js/twind/blob/main/examples/with-remix_react-v18/app/entry.client.tsx#L2
https://github.com/tw-in-js/twind/blob/main/examples/with-remix_react-v18/app/twind.ts#L4

### Please Explain in Detail...

Twind got not installed on the client when using this example.

I think the line `import './twind'` in the `entry.client.tsx` got not executed, maybe because remix bundler omit this line because we don't import something.

Remix version: 1.11.1

### Your Proposal for Changes

I solved this for my project by changes the files to the following:

```typescript
// twind.ts
import install from '@twind/with-react';
import config from '../twind.config';

const tw = install(config);

export const setup = () => tw;
export default tw;
```

```typescript
// entry.client.tsx
import { setup } from './twind';
// ...other imports

setup();
// ...other code
```

Server entry is the same.

With this workaround the remix bundler doesn't omit the twind install.

**Comment by sastan** [comment]
Hey,

thanks for taking the time for creating the issue and providing a solution. I will update the example and documentation.
