### ISSUE TITLE
[Support]: How to convert tw.target to css object

### ISSUE THREAD

**Issue by chrisarts** [tw-in-js/twind#446]
Im trying to convert css to css object in a runtime that does not contain HTML, to post that convert that object to valid styles in my runtime, is there any way to do that?

currently im doing this:

```ts
tx(...classes);
const root = postcss.parse(tw.target);
const styleObject = postCssJS.objectify(root);
```

But IDK if there is a built in method to do it without postcss,

**Comment by sastan** [comment]
Internally twind already has such a method. We _just_ need to export it. It may look something like:

```js
tx(...classes);
const styleObject = objectify(tw.target);
```

**Comment by chrisarts** [comment]
That method will be great to have it for library authors, thanks for this lib it's a pleasure work with this.
