### ISSUE TITLE
[Feature]: Need headless-ui preset

### ISSUE THREAD

**Issue by devnomic** [tw-in-js/twind#452]
### Describe the problem

Right now i cannot use 
`ui-active` `ui-not-active` prefix to style tailwind headless ui

### Describe the proposed solution

Implementation headless ui plugin in twind
https://github.com/tailwindlabs/headlessui/tree/main/packages/%40headlessui-tailwindcss

<img width="818" alt="Screen Shot 2023-02-21 at 09 29 50" src="https://user-images.githubusercontent.com/101681592/220232410-cb3e76c7-31e1-470d-8203-94e9143ac4dd.png">

### Importance

would make my life easier

**Comment by danielweck** [comment]
You could try this in your Twind config:

```javascript
import { defineConfig, setup } from '@twind/core';

const prefix = 'ui';
/** @type {import('@twind/core').Variant<import('@twind/core').BaseTheme & import('@twind/core').ExtractThemes<import('@twind/core').BaseTheme, import('@twind/core').Preset[]>>[]} */
const variants = [];
['open', 'checked', 'selected', 'active', 'disabled'].forEach((state) => {
	// variants.push([`${prefix}-${state}`, `&[data-headlessui-state~="${state}"], :where([data-headlessui-state~="${state}"]):not(:has([data-headlessui-state])) &`]);
	variants.push([
		`${prefix}-${state}`,
		`&[data-headlessui-state~="${state}"], :where([data-headlessui-state~="${state}"]) &`,
	]);
	variants.push([
		`${prefix}-not-${state}`,
		`&[data-headlessui-state]:not([data-headlessui-state~="${state}"]), :where([data-headlessui-state]:not([data-headlessui-state~="${state}"])) &:not([data-headlessui-state])`,
	]);
});

// setup() or defineConfig():
setup({
	variants,
});
```

The above code is Javascript with TypeScript annotations, you might need to adjust due to type inference in the `setup()` and `defineConfig()`, for example if you use the Tailwind and Typography preset:

```javascript
/** @type {import('@twind/core').Variant<import('@twind/core').BaseTheme & import('@twind/core').ExtractThemes<import('@twind/core').BaseTheme & import('@twind/preset-tailwind').TailwindTheme & import('@twind/preset-typography').TypographyTheme, import('@twind/core').Preset[]>>[]} */
```

...or better even, use TypeScript instead of Javascript :)
