### ISSUE TITLE
Is it possible to extract stylesheets relative to components in a react component library?

### ISSUE THREAD

**Issue by AdsonCicilioti** [tw-in-js/twind#454]
We all know that Tailwind builds a single stylesheet based on the (final) HTML content that its utility classes use.

But in a lib of React UI components, where we will install the package but we will only use a Button and some Form Inputs, for example, the ideak would be for each component to bring its own style sheet.
Would it be possible to do this with Twind?🤞

**Comment by mfissehaye** [comment]
Would it be possible to use twind to style just the library components you are building? Please provide an example
