### ISSUE TITLE
[Docs]: What is twind.dev?

### ISSUE THREAD

**Issue by lino-levan** [tw-in-js/twind#456]
### Documentation Is:

Missing

### Link to relevant page or pages

Doesn't exist anymore: https://twind.dev/handbook/the-shim.html
Straight up wrong: https://twind.dev/handbook/styling-with-twind.html
Out of date: https://twind.dev/handbook/configuration.html

### Please Explain in Detail...

Essentially all of the information on the documentation is out of date. This is rather unfortunate in my opinion since it makes it really hard to use the latest version of this wonderful tool. 

### Your Proposal for Changes

Updating these docs with the changes in 1.0 would be fantastic. I would volunteer to do it but I genuinely have no idea how to use twind post 1.0 so I'm just waiting on someone more experienced to pick it up.

**Comment by lino-levan** [comment]
I realize now that twind.style is now where the docs are hosted... I kind of find it confusing that there are two places with documentation about tailwind

**Comment by cvladan** [comment]
By the way, I believe this project is inactive.
There is no response to anything.

**Comment by stevenalanstark** [comment]
I also burned more than a few hours on this, it is very confusing.

**Comment by lino-levan** [comment]
I'd honestly just recommend using UnoCSS. I've moved to it personally.

**Comment by alshdotme** [comment]
twind.dev is version 0.x.x of Twind. The API had a big re-write and now the most up-to-date docs are available at [twind.style](https://twind.style) for version 1.x.x

But yes, haven't seen Sastan active for some time. Hopefully all is well.
