### ISSUE TITLE
[Feature]: support for logical properties

### ISSUE THREAD

**Issue by a777med** [tw-in-js/twind#470]
### Describe the problem

Twind does not support logical properties.

### Describe the proposed solution

TailwindCSS v3.3 introduced logical properties. Like, `start-0`, `end-0`, `me-12`, `ps-0` etc. 

[https://tailwindcss.com/blog/tailwindcss-v3-3#simplified-rtl-support-with-logical-properties](url)

I tried using them in Twind and they did not work. It would be nice to have that feature.

### Importance

would make my life easier

**Comment by ishaiavrahami** [comment]
any fix?

**Comment by onemoreahmad** [comment]
+1

**Comment by onemoreahmad** [comment]
I just checked that Twind allows you to add your own rules 😍
https://twind.style/rules

So I added it to my config 

```
            rules: [
                ['ms-(\\d+)', (match) => ({ 'margin-inline-start': `${match[1] / 4}rem` })],
                ['me-(\\d+)', (match) => ({ 'margin-inline-end': `${match[1] / 4}rem` })],                
                ['ps-(\\d+)', (match) => ({ 'padding-inline-start': `${match[1] / 4}rem` })],
                ['pe-(\\d+)', (match) => ({ 'padding-inline-end': `${match[1] / 4}rem` })],
                ['rounded-s-', ({ $$ }) => `rtl:rounded-r-${$$} ltr:rounded-l-${$$}`],
                ['rounded-e-', ({ $$ }) => `rtl:rounded-l-${$$} ltr:rounded-r-${$$}`],
            ]
 
```

Now I can use `ms-(1,2 ..etc), me-*, ps-*, pe-*, rounded-s-(sm/lg..etc), rounded-e-* ` classess
