### ISSUE TITLE
[Bug]: Style is prepend, not append

### ISSUE THREAD

**Issue by volkandkaya** [tw-in-js/twind#474]
### Reproduction

Check any Twind site after v1.0, it is prepend to the top of the head, instead of appending to the bottom of the head.

### Describe the bug

`
If the cssomSheet is passed no target it looks for an style element with the id __twind. If no such element is found it will create one and append it to the document.head.
`
https://twind.dev/handbook/configuration.html#dark-mode

### Severity

serious, but I can work around it

### System Info

```sh
All
```

### Additional Information

For my use case I want to be able to override 3rd party styles, it being at the top means I have to use !static instead of static.

**Comment by rschristian** [comment]
Those are the v0 docs you're linking to. https://twind.style is the docs site for v1.

**Comment by volkandkaya** [comment]
Thanks. I still wonder why it was changed.

**Comment by rschristian** [comment]
Can't say for certain, but higher in the head does decrease the chances of FOUC and it looks like there might've been some SSR/resumability issues according to the blame?

https://github.com/tw-in-js/twind/commit/b223e5bb9f701db03c30e14d3f7b84b705d43ef0#diff-817ceb9c4f65e54c2c1f2f4436d127237ce4d9bff7f4c314415ee4bb0a2aefdf
