### ISSUE TITLE
[Bug]: Twind Intellisense is not working when I create project using fresh

### ISSUE THREAD

**Issue by agnosticoder** [tw-in-js/twind#479]
### Reproduction

I am using deno fresh

### Describe the bug

deno run -A -r https://fresh.deno.dev

project created using above command don't have the twind intellisense

### Severity

annoyance

### System Info

```sh
I am using deno
```

**Comment by Sfxrlz** [comment]
[twind does not yet seem to support ts v5 ](https://github.com/tw-in-js/vscode-twind-intellisense/issues/22)
also see [here](https://github.com/tw-in-js/vscode-twind-intellisense/issues/24)

Deno --version returns 
```shell
deno 1.34.2
typescript 5.0.4
``` 
and my vscode instance uses 5.1.3.

I got around it by installing pre 5~ version typescript globally through npm and pointing my __workspace tsdk setting__ to the `lib` folder of that installation.

![grafik](https://github.com/tw-in-js/twind/assets/42067578/a3b753aa-9f2c-442c-9a05-9ed0f8ab3f66)

**Comment by afifurrohman-id** [comment]
Yes the issues is twind not support typescript v5.

**Alternative solution in fresh issues** https://github.com/denoland/fresh/issues/1519
