### ISSUE TITLE
API consideration: return `tw` from `setup` function

### ISSUE THREAD

**Issue by itsMapleLeaf** [tw-in-js/twind#49]
So one issue I notice with the way the API works, is that you have to manually ensure tw is only called after setup. Integrating twind in my Next.js project and having followed the examples, even then, I'm still getting some "late setup call" errors, which I think is a sign that this constraint can't be reliably followed

Suggestion: when needing a config override, the user should create their own `tw` file which includes the `setup` call. Setup returns the `tw` function, which is then imported throughout the app for styling. Logically, this ensures that `setup` _can't_ be called after `tw`. To clarify:
```ts
// tw.ts
import { setup } from "twind"

export const tw = setup({
	theme: { colors: { palevioletred: "palevioletred" } },
})

// Button.tsx
import { tw } from "./tw"

export const Button = () => (
	<button type="button" className={tw`p-3 rounded bg-blue-500 text-white`}>
		hi
	</button>
)
```

With the current API, it's true that one could also reexport `tw` from the `tw.ts` file. My suggestion is to make this API change to possibly _enforce_ using the returned `tw` function, and/or document that usage

**Comment by sastan** [comment]
Thanks for the report. Could you share a repo where this happens?

We should make it more clear that `setup` should be called in the main entry file. The idea is that the `setup` export modifies the `tw` export to allow libraries to use `import { tw } from 'twind'` while the application is _may_ configure `tw` using `setup`.

What you are trying is already possible using the yet undocumented `create` export (see [Web Components](https://github.com/tw-in-js/twind/blob/main/docs/examples.md#web-components---custom-elements-and-shadow-dom) example):

```
// tw.ts
import { create } from "twind"

export const { tw } = create({
	theme: { colors: { palevioletred: "palevioletred" } },
})
```

I hope that helps...

**Comment by sastan** [comment]
@itsMapleLeaf Would it be ok with you if i move this to Discussion Q&A for other to read?

**Comment by itsMapleLeaf** [comment]
Yeah, that's fine. I can post my repo over there

**Comment by itsMapleLeaf** [comment]
Moved here https://github.com/tw-in-js/twind/discussions/50

**Comment by sastan** [comment]
Thanks!
