### ISSUE TITLE
Is there a way to make tailwind-scrollbar plugin to work with twind?

### ISSUE THREAD

**Issue by mfissehaye** [tw-in-js/twind#491]
https://github.com/adoxography/tailwind-scrollbar/issues/84

**Comment by rschristian** [comment]
As mentioned in the linked issue, Twind does not support the Tailwind plugin API. You could probably port it without too much trouble though.

**Comment by mfissehaye** [comment]
@rschristian thanks for the reply. Can you drop a few tips on how to do that. How to get started

> As mentioned in the linked issue, Twind does not support the Tailwind plugin API. You could probably port it without too much trouble though.
