### ISSUE TITLE
`justify-self-start` not working, resulting class with empty rule

### ISSUE THREAD

**Issue by rockmandash** [tw-in-js/twind#55]
Please see this minimum example

```html
<section class="grid grid-cols-3 gap-2 place-items-center h-screen w-screen">
  <div class="bg-pink-500 text-white justify-self-start">1</div>
  <div class="bg-pink-500 text-white">2</div>
  <div class="bg-pink-500 text-white">3</div>
  <div class="bg-pink-500 text-white">4</div>
  <div class="bg-pink-500 text-white">5</div>
  <div class="bg-pink-500 text-white">6</div>
</section>
```

[Tailwind Play](https://play.tailwindcss.com/w1xXi6g7Hy)

Correct Result

![image](https://user-images.githubusercontent.com/7580792/103453481-722aed80-4d15-11eb-82dc-d83838a736af.png)

But in `twind`, it's not working

[Code Sandbox](https://codesandbox.io/s/justify-self-start-yiopb?file=/src/index.js)

![image](https://user-images.githubusercontent.com/7580792/103453492-9ab2e780-4d15-11eb-8dd3-04334ba90b6b.png)

![image](https://user-images.githubusercontent.com/7580792/103453502-b1f1d500-4d15-11eb-9222-60a424ebead0.png)

Official Docs [here](https://tailwindcss.com/docs/justify-self)

**Comment by sastan** [comment]
Another good catch! Thanks a lot.
