### ISSUE TITLE
TypeScript Issues with Styled API for React

### ISSUE THREAD

**Issue by gojutin** [tw-in-js/twind#60]
I've noticed a few TypeScript issues with the `styled` API for React:

- Props that should be allowed are not (ex. `type` prop on Input )
- Props argument for inline functions is not strongly typed (`any`)
- Props that are not defined in the type definitions are not being caught

I’ve included a minimal example that demonstrates each of these issues. It also includes a `styled-components` implementation for comparison. 

Codesandbox Link: https://codesandbox.io/s/twind-styled-typescript-by9l4

**Comment by sastan** [comment]
I'm aware of these. I just hadn't the time to properly type html props. If you like you can try to fix these and i incorporate them in to the PR.

I have some family things to take of this week... But i want this merged soon.

**Comment by sastan** [comment]
Another week passed.... I thought a lot about the direction we want to go with this. @mattrossman (https://github.com/tw-in-js/twind/pull/7#issuecomment-752716310) had a some of ideas too.

As we have already an initial working draft i'm thinking about creating a "spec"/discussion to iron out the API. What currently bugs me most is how inheritance (`styled(parent)`...`) should work.

I hope i can implement something next week.
-

**Comment by sastan** [comment]
I'd like to move the effort into #102.
