### ISSUE TITLE
Concurrent async SSR

### ISSUE THREAD

**Issue by ggoodman** [tw-in-js/twind#62]
Hi all, fantastic work on `twind`!

I was looking into integrating this into an experiment of mine that brings full async SSR but noticed that `twind`'s SSR docs appear to assume that only one concurrent render operation can be in effect at once. Are there any tricks I'm missing that would allow me to potentially:

1. Start rendering page A
2. Start rendering page B
2. Start rendering page C
4. Finish rendering page A and generate static stylesheet
3. Finish rendering page C and generate static stylesheet
4. Finish rendering page B and generate static stylesheet

The potential for interleaving and out-of-order completion has me a bit worried.

**Comment by lukejacksonn** [comment]
Hey @ggoodman 👋 thanks for the comment, glad you are enjoying twind!

I can't take credit for any of the SSR implementation tbh (that is @sastan's department 😅) he is currently a little occupied with some personal matters at the moment so might take a little longer to get back to you on this.. however I'm very curious to hear about this use case!

I believe the implementation works on [promise introspection](https://docs.google.com/document/d/1rda3yKGHimKIhg5YeoAmCOtyURgsbTH_qaYR79FELlk/edit) and would assume that you could thus await for any amount of promises to resolve (or pages to load, like in your example) so long as they use the same sheet (where `const sheet = asyncVirtualSheet()`). The sheet itself in combination with the compiler ensures proper ordering of generated rules. If you just want each page to have its own stylesheet then just ensure that a new `asyncVirtualSheet` is created before rendering each page, there will be duplication across stylesheets this way but that is the tradeoff there I guess.

Hope that helps!

**Comment by sastan** [comment]
As Luke said you need an [asyncVirtualSheet](https://github.com/tw-in-js/twind/blob/main/docs/ssr.md#asynchronous-ssr) and call `sheet.reset()` before starting rendering a new page. You do _not_ need to create a new sheet for each rendering! This should work for nodejs >= v12.

Could you post an example of your code?

**Comment by ggoodman** [comment]
This was actually _WAY_ easier than I thought it would be. I didn't reach for `asyncVirtualSheet` and wonder what context I might be missing that would make me want to use that....

Instead, I did the following:

```ts
  const target: string[] = [];
  const customSheet: Sheet<string[]> = {
    target,
    insert(rule, index) {
      // rule: the CSS rule to insert
      // index: the rule's position
      target.splice(index, 0, rule);
    },
  };

  const { tw } = create({
    sheet: customSheet,
    mode: strict,
    prefix: true,
  });

  const markup: string = shim(
    await renderToStringAsync(
      <LazyContext.Provider value={chunkCtx}>
        <React.Suspense fallback={<Loading />}>
          <StaticRouter location={path} context={context}>
            <App />
          </StaticRouter>
        </React.Suspense>
      </LazyContext.Provider>
    ),
    tw
  );
  const initialRules = target.join('\n');
```

I was hoping that creating this sort of simple 'virtual' sheet would be enough for my use case. Note: I don't think I want to have a single setup and a shared sheet across multiple renders but may have misunderstood the `twind` way.

**Comment by sastan** [comment]
The sheet is not really shared. Each async context has its own sheet. The async sheet provides a facade like object to the current sheet instance. Think of it like an [AsyncLocalStorage](https://nodejs.org/api/async_hooks.html) for styles.

I do not understand where your problem is. Are you using asyncVirtualSheet and its not working? Or did you try your code above and it does not work?

**Comment by sastan** [comment]
PS. Your custom sheet looks like the builtin virtualSheet. see docs/ssr.md

Did you have any problems using that one?

**Comment by ggoodman** [comment]
I did first try the built in sheet but no styles were being collected 🤔

**Comment by sastan** [comment]
Could you provide a repo to reproduce the issue?

**Comment by ggoodman** [comment]
I will circle back when I have something that can be shared!

**Comment by ggoodman** [comment]
> The sheet is not really shared. Each async context has its own sheet. The async sheet provides a facade like object to the current sheet instance. Think of it like an [AsyncLocalStorage](https://nodejs.org/api/async_hooks.html) for styles.
> 
> I do not understand where your problem is. Are you using asyncVirtualSheet and its not working? Or did you try your code above and it does not work?

What sort of use-cases was `asyncVirtualSheet` created for?

Here's my hypothesis: `twind` has promoted a setup whereby it operates as a pseudo-global having module-level state. This works perfectly for synchronous rendering where a virtual sheet can be pushed prior to rendering and popped upon completion but is unpredictable when rendering may span multiple micro ticks / event loops (such as Promises, timers or I/O). To address this, some trickery is needed to track the async continuation in which sheet styles are being referenced so that these can be associated with the correct virtual sheet.

If that's correct, would I be safe using an approach as described above, where I'm relying on the server-side `shim` with a render-local `tw` instance and `sheet`? What am I losing with that approach (some memoization maybe?).

Also, I notice that the server-side `shim` relies on html parsing. Have you seen any approach that might be able to hook into React's own markup-generation process? I notice that React also assumes a sort of singleton world where it would be hard to thread per-render hooks.

**Comment by ggoodman** [comment]
@sastan I've been able to clean up and publish the code. You can see that I continue to use my `customSheet` as dropping in `virtualSheet()` continues to result in an empty rule-set.

See: https://github.com/ggoodman/nostalgie/blob/d9728e976e97ea44793a5d511c53bb1af539cb89/runtime/server/ssr.tsx#L16-L42

**Comment by sastan** [comment]
> 
> @sastan, what sort of use-cases was `asyncVirtualSheet` created for?
> 
> Here's my hypothesis: `twind` has promoted a setup whereby it operates as a pseudo-global having module-level state. This works perfectly for synchronous rendering where a virtual sheet can be pushed prior to rendering and popped upon completion but is unpredictable when rendering may span multiple micro ticks / event loops (such as Promises, timers or I/O). To address this, some trickery is needed to track the async continuation in which sheet styles are being referenced so that these can be associated with the correct virtual sheet.

Perfect. That's exactly why.

The important thing in both modes (sync and async) is `sheet.reset()`. This allows to reset/restore tw internal caches and the collected styles. In the async mode reset additionally creates a new virtualSheet and associates it with the current async context. On each async context switch we restore the state.

> 
> If that's correct, would I be safe using an approach as described above, where I'm relying on the server-side `shim` with a render-local `tw` instance and `sheet`? What am I losing with that approach (some memoization maybe?).

You are right again. Some things can be cached  regardless of the current context.

Looking at your example it might be because of `await` within the shim call. I currently have limited time but could you try the following:

** Sync Example**
```js
import { tw, setup } from 'twind'
import { virtualSheet, getStyleTag, shim } from 'twind/server'

const sheet = virtualSheet()

setup({ ...sharedOptions, sheet })
// Or use create as in your example

export async function renderAppOnServer(App: React.ComponentType, path: string) {
  // This assumes you are not using `tw` in any components
  const html =  await renderToStringAsync(
      <LazyContext.Provider value={chunkCtx}>
        <StaticRouter location={path} context={context}>
          <App />
        </StaticRouter>
      </LazyContext.Provider>
    )

  // Reset the sheet AFTER the async rendering
  sheet.reset()

  const markup: string = shim(html, tw);

  return {
    preloadScripts: [...chunkCtx.chunks],
    // Create the style tag with all generated CSS rules
    headTags: [getStyleTag(sheet)],
    markup,
  };
}
```

** Async Example**
```js
import { tw, setup } from 'twind'
import { asyncVirtualSheet, getStyleTag, shim } from 'twind/server'

const sheet = asyncVirtualSheet()

setup({ ...sharedOptions, sheet })
// Or use create as in your example

export async function renderAppOnServer(App: React.ComponentType, path: string) {
  // Reset the sheet for a new rendering and associate with current async context
  sheet.reset()

  const markup: string = shim(
   await renderToStringAsync(
      <LazyContext.Provider value={chunkCtx}>
        <StaticRouter location={path} context={context}>
          <App />
        </StaticRouter>
      </LazyContext.Provider>
    ), tw);

  return {
    preloadScripts: [...chunkCtx.chunks],
    // Create the style tag with all generated CSS rules
    headTags: [getStyleTag(sheet)],
    markup,
  };
}
```

> 
> Also, I notice that the server-side `shim` relies on html parsing. Have you seen any approach that might be able to hook into React's own markup-generation process? I notice that React also assumes a sort of singleton world where it would be hard to thread per-render hooks.

That was my first idea but couldn't get it to work reliably. And we want to be as framework agnostic as possible. Maybe we can integrate that in https://github.com/tw-in-js/twind.macro as that is already react/preact specific or create an twind/shim/react module.

**Comment by sastan** [comment]
@ggoodman Could we help to resolve your issue?

**Comment by ggoodman** [comment]
@sastan thanks for circling back. I retried using `sheet.reset()` _immediately_ before walking the html and that seems to have worked! 🎉
