### ISSUE TITLE
Docs: Broken demo

### ISSUE THREAD

**Issue by mateomorris** [tw-in-js/twind#63]
I'd submit a pr for this but it involves the live demo for [observe](https://github.com/tw-in-js/twind/blob/main/docs/observe.md) so it probably needs to be updated there. 

It works again when 
`import { observe } from 'twind/observe'`
is changed to 
`import { observe } from 'https://cdn.skypack.dev/twind/observe'`

**Comment by sastan** [comment]
Thank you for the report.

The cool thing about https://esm.codes/ (another great project by @lukejacksonn) is that the code is encoded in the url and you can copy-paste the url. I have fixed that in 0d5f526. If you find more issues with the docs please keep opening issues or create PRs.

**Comment by mateomorris** [comment]
Oh cool, good to know. will do!
