### ISSUE TITLE
container doesn't work correctly with max-w set

### ISSUE THREAD

**Issue by JLarky** [tw-in-js/twind#66]
here https://codesandbox.io/s/busy-moon-ypndy?file=/src/App.tsx:96-118 I set class `container md:max-w-3xl` which works in tailwind like that: it uses container class for screens smaller than md and uses fixed width on md and bigger.

You can test that it works in tailwind as expected if you comment this line
https://codesandbox.io/s/busy-moon-ypndy?file=/public/index.html:1033-1110
and uncomment this one
https://codesandbox.io/s/busy-moon-ypndy?file=/public/index.html:1114-1238

**Comment by sastan** [comment]
Thanks for the report.

I could reproduce this with: https://codesandbox.io/s/fervent-bush-pyd8b

It seems like the container responsive styles have a higher precedence that the responsive max-width styles. I'll look into that.

**Comment by sastan** [comment]
@JLarky It seems to be fixed  with #67 for me. Could you please give it a try: https://github.com/tw-in-js/twind/pull/67#issuecomment-756118832

**Comment by JLarky** [comment]
Yep, thank you, can confirm that it works as expected in my app now :)
