### ISSUE TITLE
customize the generated class name prefix

### ISSUE THREAD

**Issue by sastan** [tw-in-js/twind#76]
Emotion uses [labels](https://emotion.sh/docs/labels) for that.

```js
let style = css`
  color: hotpink;
  label: some-name;
`
```

If twind would support labels, or className prefixes, we could do something similar. That way it could even work when adding labels inside the className with the shim.

pseudo:
```
<button class="label:PurpleButton py-4 px-8 />
```

And
```
compose`
  label:PurpleButton
  py-4 px-8 
  rounded-lg 
  bg-purple-600`
// -> .PurpleButton-XXXX 
```

The separator could be either a `:` (label:x) to be like emotion, or a `-` (label-x) to be more tailwind like. 

Based on https://github.com/tw-in-js/twind/issues/73#issuecomment-757557808 and https://github.com/tw-in-js/twind/issues/73#issuecomment-757554118

**Comment by sastan** [comment]
Idea from https://github.com/tw-in-js/twind/issues/190#issuecomment-866807470: Concat labels

> I figured the cleanest way to do this would be a utility plugin-type thing to allow classnames like label:btn, which my hash fn would then look for to generate out something like btn::[css hash]. For handling the apply, my hash fn would also look for the :: (or whatever separator I use) and concat any newly found labels on. So if I was adding on a set of styles that include label:ghost to the generated-from-apply btn::[hash], I'd concat them into something like btn-ghost::[new(?) hash].

**Comment by sastan** [comment]
Implemented in twind v1.

- inline apply: styles are generated in order they are declared
  - `@(underline font-bold)` -> `@(underline,font-bold)`
  - `Link@(underline font-bold)` -> `Link#12345`
- inline shortcut: style are generated as defined by twind — same as if they where used alone
  - `~(underline font-bold)` -> `~(underline,font-bold)`
  - `Link~(underline font-bold)` -> `Link#abcdef`

Please give it a try. Here are some links to get you started:

- [The v1 branch](https://github.com/tw-in-js/twind/tree/next)
- [Reference](https://github.com/tw-in-js/twind/blob/next/documentation/40-reference/README.md) until the website is ready
- [Examples](https://github.com/tw-in-js/twind/tree/next/examples) — the [CDN example](https://github.com/tw-in-js/twind/tree/next/examples/twind-cdn) could be a good start

Closing this for now. Feel free to re-open.

**Comment by HowieG** [comment]
Hi @sastan I'm trying to add a custom prefix like we can here https://tailwindcss.com/docs/configuration#prefix
Is this possible in twind? I'm injecting my component into an existing site and getting style leakage that I hope can be prevented with this prefix
