### ISSUE TITLE
Ring gets override by parent shadow.

### ISSUE THREAD

**Issue by rockmandash** [tw-in-js/twind#84]
Please see this minimum markup and watch the different result between Tailwind Play and twind:

```html
<div class="w-screen h-screen flex justify-center items-center">
  <div class="shadow-lg w-24 h-24 bg-white rounded flex justify-center items-center">
    <button class="rounded p-1 ring-1 ring-red-500">Click</button>
  </div>
</div>
```

Result:

![image](https://user-images.githubusercontent.com/7580792/104679175-15bdca00-5728-11eb-9edc-6fd974a4b7c3.png)

Code:

[Tailwind Play](https://play.tailwindcss.com/Zl7wpzsGta)
[twind](https://codesandbox.io/s/ring-gets-override-owtju?file=/src/index.js)

Twind's ring gets override by parent shadow.

My first thought was adding `shadow-none` to revert this, but watch what happen when I add `shadow-none`:

```html
<div class="w-screen h-screen flex justify-center items-center">
  <div class="shadow-lg w-24 h-24 bg-white rounded flex justify-center items-center">
    <button class="shadow-none rounded p-1 ring-1 ring-red-500">Click</button>
  </div>
</div>
```

![image](https://user-images.githubusercontent.com/7580792/104679389-882eaa00-5728-11eb-9fe6-1fb03de8222a.png)

Tailwind Play is still the same, but twind's ring color disappears!

**Comment by sastan** [comment]
Thanks for detailed report. I'll look into it.

**Comment by sastan** [comment]
@rockmandash Thanks for all the issues you have been finding, the great reproduction examples and the detailed descriptions which helps me a lot to solving these!

Could you please take a look at #85 if that fixes all the addressed issues. You can install the PR package: https://github.com/tw-in-js/twind/pull/85#issuecomment-761065132

**Comment by rockmandash** [comment]
@sastan Thank you for your fast support!

Can confirm my issue is gone by using this PR package in my project.

Thank you so much!
