### ISSUE TITLE
css consumes theme value

### ISSUE THREAD

**Issue by DylanVann** [tw-in-js/twind#95]
Hello, thanks for making Twind, it's really great!

I think I came across one bug in a complicated situation, if `css`, `tw`, and `apply` are used like this:

```
tw(
  css({
    h1: apply`bg-accent`
  })
)
```

(which I think is how they're supposed to be used if you want to get a `className` to use)

After calling that `bg-accent` no longer takes effect in normal `tw` usage.

Reproduction: https://codesandbox.io/s/twind-bug-css-consumes-theme-value-jnnrm?file=/src/App.js:232-283

Thank you!

**Comment by sastan** [comment]
Thanks for the report. Confirmed and working on it.

**Comment by sastan** [comment]
@DylanVann Fixed in 0.14.1. Thanks for the fast report.
